### ISSUE TITLE
REST Server?

### ISSUE THREAD

**Issue by mzeidhassan** [OpenNMT/OpenNMT-tf#107]
Hello ONMT team,

Does the Tensorflow version of OpenNMT come with a ready-to-use REST Server?

Thanks,
mzeid

**Comment by guillaumekln** [comment]
Hello,

We recommend using [TensorFlow Serving](https://www.tensorflow.org/serving/) which is the standard choice to serve TensorFlow models via a remote API. Here are some documentation related to OpenNMT-tf but you might want to get information directly from TensorFlow:

* http://opennmt.net/OpenNMT-tf/serving.html
* https://github.com/OpenNMT/OpenNMT-tf/tree/master/examples/serving

**Comment by mzeidhassan** [comment]
Thanks @guillaumekln for your reply. 
Which version do you recommend for a real production environment? OpenNMT LUA or OpenNMT TF?

Thanks

**Comment by guillaumekln** [comment]
TensorFlow is designed for production so I recommend OpenNMT-tf.
