### ISSUE TITLE
Error of Empty lines caused by '\r' in the  tutorial of Transformer

### ISSUE THREAD

**Issue by IdiosyncraticDragon** [OpenNMT/OpenNMT-tf#108]
I was trying the scripts under scripts/wmt .  The preprocessing was succeful, but when I running the training, there appeared this error:
`InvalidArgumentError (see above for traceback): Invalid content in data/wmtende.vocab: empty line found at position 283470.`

The environment I used is :
python==3.5.2;
tensorflow-gpu==1.7.0;
OpenNMT-tf==1.1.0;
sentencepiece== the latest version in github

**Comment by vince62s** [comment]
if you used this script: https://github.com/OpenNMT/OpenNMT-tf/blob/master/scripts/wmt/prepare_data.sh
the last lines are supposed to remove the empty lines of the vocab.
In my case it was a "tab" that created an empty line, and I scripted the removal.
check if this applies to you.
cheers.

**Comment by vince62s** [comment]
In my file wmtende.vocab date Feb 27, I also have the chinese character, this is normal, it is the uncleaned version of the corpus.
@guillaumekln did you upload another version ?

**Comment by guillaumekln** [comment]
No I did not. However, I found an invalid vocabulary in the exported model, maybe that is the one he is referring to.

**Comment by IdiosyncraticDragon** [comment]
I am using Linux (inside a docker container, the docker image is tensorflow/tensorflow:nightly-gpu-py3, this image can be directly download from docker hub)
**Linux version 4.4.0-112-generic (buildd@lgw01-amd64-010)
Ubuntu 16.04
gcc version 5.4.0 20160609
python==3.5.2;
tensorflow-gpu==1.7.0;
OpenNMT-tf==1.1.0;
sentencepiece== the latest version in github** 

It seems the problem is '\r' in the .vocab file. This cannot be replaced by 's/\n\n/\n\t\n/' (At the end of prepare_data.sh). And if I replace '\r' to '\t', there will be a conflict (a '\t' is added by 's/\n\n/\n\t\n/' at some place else in .vocab) when the hash table is building.
![image](https://user-images.githubusercontent.com/3750460/39283073-ff8f266a-493e-11e8-9833-93e42218de39.png)

I checked the raw data, and fond there were '\r' in news-commentary-v11.de-en.en/de. After I deleted those '\r',  I could run ./run_wmt_ende_1gpu.sh **successfully**.

By the way, I found I can not run the pre-trained model using the data processed by my machine, the error is : 
![image](https://user-images.githubusercontent.com/3750460/39284163-874b02cc-4944-11e8-978a-3cf002f04bd1.png)
 But I think my problem may be solved, at least I can run the tutorial ^_^.
