### ISSUE TITLE
Reranking

### ISSUE THREAD

**Issue by mattiadg** [OpenNMT/OpenNMT-tf#119]
Hi all,

is it possible, or you plan to implement, the reranking of an N-best list?
It is done for example here: http://www.statmt.org/wmt17/pdf/WMT30.pdf

If it's not possible now, and I would like to do it, what files should I work on?

best,

Mattia

**Comment by guillaumekln** [comment]
Hi, sorry for the delay.

I have a related unfinished development that I just pushed on GitHub after your comment, see https://github.com/OpenNMT/OpenNMT-tf/pull/121. It adds a `score` run type that simply scores existing translations in the following format:

```
<score> |||| <translation>
```

where `<score>` is the negative log likelihood of the translation.

As you can already output the N-best list during inference, this seems to cover your use case. Let me know what you think.

**Comment by mattiadg** [comment]
Hi, sorry for the very late answer.

This is exactly the use case I was thinking about, but then I got stuck in an implementation and I have not use it anymore. 
Sorry about that.
