### ISSUE TITLE
Decode error in Docker

### ISSUE THREAD

**Issue by luozhouyang** [OpenNMT/OpenNMT-tf#126]
I started a docker to use OpenNMT-tf. The image of docker container is Ubuntu:16.04.  
I ran this command to do inference:
```bash  
onmt-main infer --config config/sample.yml --features_file infer.txt
```  
but an error occurs:
```bash
Traceback (most recent call last):
  File "/usr/local/bin/onmt-main", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/opennmt/bin/main.py", line 133, in main
    checkpoint_path=args.checkpoint_path)
  File "/usr/local/lib/python3.5/dist-packages/opennmt/runner.py", line 186, in infer
    self._model.print_prediction(prediction, params=self._config["infer"], stream=stream)
  File "/usr/local/lib/python3.5/dist-packages/opennmt/models/sequence_to_sequence.py", line 241, in print_prediction
    print_bytes(tf.compat.as_bytes(sentence), stream=stream)
  File "/usr/local/lib/python3.5/dist-packages/opennmt/utils/misc.py", line 27, in print_bytes
    text = str_as_bytes.decode(encoding) if encoding != "ascii" else str_as_bytes
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 0: ordinal not in range(128)
```  

I read the source code following the traceback and found that in `opennmt/runner.py line186`:
```bash
if predictions_file:
    stream = io.open(predictions_file, encoding="utf-8", mode="w")
else:
    stream = sys.stdout
```  
If I do not pass a `--predictions_file` argument, onmt just print the inference results to std output, and this may caused the problem.  
So I add `--predictions_file` argument, and no errors:
```bash
onmt-main infer --config config/sample.yml --features_file infer.txt --predictions_file infer_out.txt
```  
But write to a file is not what I need.

I am using tensorflow serving to serve my model. When I make a request from client. I just received bytes arrays like:
```bash 
\xe9\xbb\x84\xe6\xb5\xb7\xe8\x8a\xb1\xe5\x9b\xad
```  
What should I do to solve this problem?

**Comment by guillaumekln** [comment]
I think this is because locales are not properly set within the Docker container. Try setting the `LANG` environment variable, for example in your Dockerfile:

```
ENV LANG C.UTF-8
```
