### ISSUE TITLE
The Transformer performance

### ISSUE THREAD

**Issue by lkluo** [OpenNMT/OpenNMT-tf#140]
Good job. The codes are much more readable than Google's. 
Is the performance of Transformer comparable to Tensor2Tensor? Anyone make the comparison?

**Comment by guillaumekln** [comment]
Yes, the [WMT scripts](https://github.com/OpenNMT/OpenNMT-tf/tree/master/scripts/wmt) achieve results on par with Tensor2Tensor when trained with similar configurations. Also see the slide 13 of [this presentation](https://github.com/OpenNMT/Presentations/blob/master/ONMT-WorkshopParis2018/03-VincentNguyen-OpenNMT_Evaluation.pdf) for the actual comparison.

**Comment by lkluo** [comment]
@guillaumekln Thanks for your promoted response. There is RNNPlusEncoder, but it seems that the full model described in https://arxiv.org/abs/1804.09849 is still under construction?

**Comment by guillaumekln** [comment]
Correct, the RNMT+ decoder is currently not available. For now, we rely exclusively on modules from `tf.contrib.seq2seq` to decode with RNNs. However, this new architecture requires custom developments, most likely a new type of RNN cell.

In addition to the RNMT+ encoder from the paper, it also possible to train with a "Cascaded Encoder" (using a [`SequentialEncoder`](http://opennmt.net/OpenNMT-tf/package/opennmt.encoders.encoder.html#opennmt.encoders.encoder.SequentialEncoder)) or a "Multi-Column Encoder" (using a [`ParallelEncoder`](http://opennmt.net/OpenNMT-tf/package/opennmt.encoders.encoder.html#opennmt.encoders.encoder.ParallelEncoder)).
