### ISSUE TITLE
Predict estimator is super slow

### ISSUE THREAD

**Issue by lockder** [OpenNMT/OpenNMT-tf#146]
Sorry I've found so many issues and I had to open so many issues
it looks like to me the infer prediction is super super slow. its not real time, I find out the system, recreates the graph also it looks like we recreate all the datasets setups again.

Isn't there any way to make the predictions real time? Since I'm predicting one sentence at the same time should be fast if the graph and datasets weren't recreated all the time

**Comment by guillaumekln** [comment]
Inference is designed to infer from test files (which usually contain few hundreds or thousands examples). Looks like you want to serve your model instead. See the documentation for more information:

http://opennmt.net/OpenNMT-tf/serving.html

**Comment by lockder** [comment]
Thank you so much!

Enviado desde mi iPhone

**Comment by mohammedayub44** [comment]
@guillaumekln  @lockder  I noticed a significant delay during serving as well. There is a 2-3 sec for each inference sentence I pass. I'm running this on m5x.large AWS instance. 
My guess was the serving model uses only CPU's for inference. Is there any advantage of serving this on GPU ? Any other optimizations that are helpful in this case from Tensorflow/hardware side of things. Appreciate any help.

Thanks !

**Comment by guillaumekln** [comment]
For CPU you can try to grab a TensorFlow Serving binary compiled with Intel MKL, see for example their [`Dockerfile.mkl`](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.mkl). However, a GPU will definitely help. As you are running on AWS you can easily test a GPU instance and see how it compares.

Regarding the OpenNMT-tf model itself,

* run batch inference if possible, either by sending multiple sentences at once or [configuring TensorFlow Serving](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/serving_config.md#batching-configuration) to batch incoming requests (might be tricky to configure correctly/efficiently)
* export your model with a recent OpenNMT-tf version: beam search decoding was largely improved in 1.22.0

**Comment by mohammedayub44** [comment]
Great. I'm currently using 1.22.0 model exports and using batching parameters. I will try the MKL binaries and GPU instance suggestions as well. 

Thanks !

**Comment by mohammedayub44** [comment]
@guillaumekln 
Testing on GPU instance with tensorflow 1.12.0 does not seem straight forward. I ran into issues like below - ` could not dlopen libcuda.so.1 ... no such file or directory ...`

![Cuda_error](https://user-images.githubusercontent.com/7122670/62947002-c2677f80-bdaf-11e9-9fae-78ce62331355.PNG)

Seems like the docker containers requires 1.13.0 or above. Even after updating and trying the latest tensorflow serving docker, that is `1.14.0-rc0-gpu` and installing the latest versions of `tensorflow== 1.14.0` , `tensorflow-gpu==1.14.0 `and `tensorflow-serving-api==1.14.0` . it still gives me the same error. I have tried this with other tensorflow versions in between like 1.13.0rc0 etc. the docker container just exits. 

I was wondering if you can replicate and verify if this is happening on your end as well. Any assistance to resolve it. 

Below are the GPU instance details I have: 

![image](https://user-images.githubusercontent.com/7122670/62947485-9bf61400-bdb0-11e9-903f-910d59fe6067.png)

![image](https://user-images.githubusercontent.com/7122670/62947662-ebd4db00-bdb0-11e9-81d7-da98993c8a5b.png)

**Comment by guillaumekln** [comment]
Are you using nvidia-docker?

**Comment by mohammedayub44** [comment]
Presently I run a docker-compose command like below with the following Compose file

Command:  This builds the image and starts it 
`docker-compose -f docker-compose_gpu.yml up --build` 
Compose File: 
[docker-compose_gpu.yml.txt](https://github.com/OpenNMT/OpenNMT-tf/files/3501738/docker-compose_gpu.yml.txt)
[Dockerfile_gpu.txt](https://github.com/OpenNMT/OpenNMT-tf/files/3501744/Dockerfile_gpu.txt)
I have no problem running this on my CPU's 

I'm not sure how to try the above setup using `nvidia-docker`, I try the following but I get some errors.
1) Build the images with docker-compose with `--no-start` tag.
2) Start mongodb  container separately ` docker container start mongodb`  
3) Starting the NMT container with nvidia-docker as below gives me error  
Command : `nvidia-docker run -it -p 8080:8080 nmtwebimage_gpu:latest /bin/bash`
![image](https://user-images.githubusercontent.com/7122670/63028788-74b94880-be7d-11e9-887c-ea12fafd3ec3.png)

Seems like something is broken.

**Comment by guillaumekln** [comment]
You probably want to check the documentation of nvidia-docker: https://github.com/NVIDIA/nvidia-docker/wiki

**Comment by mohammedayub44** [comment]
Thanks @guillaumekln  
I updated the driven version to 410.104 using instructions from [NVIDIA's driven downloads site](https://www.nvidia.com/download/driverResults.aspx/143674/en-us) and got away with that error. Also, i realized that if you have nvidia-docker version 2.x you can directly use docker commands with `runtime` argument like below ( which also works) Runs perfectly fine.

`docker run --runtime=nvidia -d --rm -p 8500:8500 --mount type=bind,source=/home/ubuntu/LanguageTranslation/Serving/nfpa_models/,target=/models/nfpa_models -t tensorflow/serving:latest-gpu --model_config_file=/models/nfpa_models/models.config`

However, the above is true only when you run it locally on you GPU, but when you try to create a docker image on top of `tensorflow/serving:latest-gpu` and try running it from docker-compose using `runtime: nvidia` it successfully adds the GPU instance but now throws this error 
`ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory` and exits 

Dockercompose File:
[docker-compose_gpu_v2.3.yml.txt](https://github.com/OpenNMT/OpenNMT-tf/files/3507051/docker-compose_gpu_v2.3.yml.txt)

DockerFile: (same as above)
Log File:  [docker_logs_gpu_v2_3.txt](https://github.com/OpenNMT/OpenNMT-tf/files/3507054/docker_logs_gpu_v2_3.txt)

I'm not sure why its not able to pick up this file from my docker image.

**Comment by guillaumekln** [comment]
Not sure about `tensorflow/serving:latest-gpu`. Can you try with `tensorflow/serving:1.14.0-gpu` instead?

**Comment by mohammedayub44** [comment]
Yeah still gives me the same error as above with `tensorflow/serving:1.14.0-gpu`. 
I tried with `1.11.0-gpu` as it seemed to work fine. Not sure why so.
LogFile - [docker_logs_gpu_1_11.txt](https://github.com/OpenNMT/OpenNMT-tf/files/3517413/docker_logs_gpu_1_11.txt)

**Comment by guillaumekln** [comment]
If you manually install a TensorFlow package, it should be the same version as the Serving image. Looks like you installed a version <= 1.12 in the 1.14 image.

**Comment by mohammedayub44** [comment]
My bad , I forget I override it in my requirements.txt file which auto generates from the local environment. That fixed it for all versions on GPU. 
![image](https://user-images.githubusercontent.com/7122670/63313506-b2c9c880-c2d2-11e9-9a5a-cb2bb3feac1e.png)

and also for the custom mkl binaries which I was getting the same error.
![image](https://user-images.githubusercontent.com/7122670/63314832-ee669180-c2d6-11e9-9343-a26789cc4fbe.png)

Thanks 👍
