### ISSUE TITLE
Same File Error

### ISSUE THREAD

**Issue by halidziya** [OpenNMT/OpenNMT-tf#147]
https://github.com/OpenNMT/OpenNMT-tf/blob/0434902d871bf435134829f9071208ef08dca54e/opennmt/inputters/text_inputter.py#L41

This line generates same file error if vocabulary file path set in model folder. 

Suggesting: 
if (vocabulary_file!=destination):

**Comment by guillaumekln** [comment]
Thanks for pointing this out!
