### ISSUE TITLE
Inference is too slow

### ISSUE THREAD

**Issue by luozhouyang** [OpenNMT/OpenNMT-tf#150]
I exported the pre-trained model and serve it in tf serving. I did some test and think it's too slow to use it in production. It takes **100~200 ms** to inference a **single** sequence.
Does this problem related to the model? And how can I improve the performance?

**Comment by guillaumekln** [comment]
Do you run TensorFlow Serving on the CPU? If so, that is somewhat an expected latency.

For building TensorFlow Serving for GPU, see for example:

**Comment by guillaumekln** [comment]
The TensorFlow Serving team now maintain official GPU images: https://hub.docker.com/r/tensorflow/serving/tags/
