### ISSUE TITLE
Use customized word embedding while testing

### ISSUE THREAD

**Issue by IdiosyncraticDragon** [OpenNMT/OpenNMT-tf#151]
The constructor of WordEmbedder allows user to use customized word embedding before training. If I want to replace the values of word embedding vectors for a pre-trained model, like Transformer, what should I do? Is there any convenient method to do this?

**Comment by guillaumekln** [comment]
There is nothing in OpenNMT-tf that allows you to do this out of the box.

However, there should be ways with TensorFlow to replace variable inside the checkpoint, or mutate the variable when [restored](https://github.com/OpenNMT/OpenNMT-tf/blob/v1.5.0/opennmt/inputters/text_inputter.py#L367). Did you consider investigating this?

**Comment by IdiosyncraticDragon** [comment]
Thank you for your advice. I have tried and met some strange errors.  I just want to make sure there is not a convenient way existed in OpenNMT-tf.
