### ISSUE TITLE
Multi-GPU synchronous training

### ISSUE THREAD

**Issue by guillaumekln** [OpenNMT/OpenNMT-tf#16]
Distributed training is currently asynchronous. It should also support a local multi-GPU synchronous mode.

**Comment by guillaumekln** [comment]
Here is an implementation to consider: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/estimator/python/estimator/replicate_model_fn.py

It should come in a future release.

**Comment by gsoul** [comment]
It seems like TF has RC0 for version 1.5, so it's not far away from release (2-4 weeks). @guillaumekln could you please share examples for running OpenNMT-tf on multiple GPUs in synchronous mode with this tool, if you have any.

**Comment by qiuyedyc** [comment]
Yes, the same for running OpenNMT-tf on multiple GPUs in asynchronous mode

**Comment by guillaumekln** [comment]
@gsoul Unfortunately I did not have time to work on this. If other people are willing to take a look that would also be great.

@qiuyedyc Asynchronous training is already supported. See the [documentation](http://opennmt.net/OpenNMT-tf/training.html#distributed).

**Comment by guillaumekln** [comment]
To update on this, local multi GPU was finally implemented using a simple in-graph replication over visible devices. This is for example the approach implemented in [tensor2tensor](https://github.com/tensorflow/tensor2tensor) and seems suited to the Transformer model. Some more experiments and tuning might be required though.

For traditional RNN-based sequence-to-sequence models, asynchronous distributed training is the recommended option for now.

For more information, see the [documentation](http://opennmt.net/OpenNMT-tf/training.html).
