### ISSUE TITLE
Doubts in Multi source inputs execution

### ISSUE THREAD

**Issue by R1j1t** [OpenNMT/OpenNMT-tf#160]
So I am working on a translation mechanism where I have multiple source files and a corresponding translation files. The total number of source files is 52.  The reason for not merging these files is because the target file length varies and is not constant with respect to source file length. Below is my multi_source_nmt.py file

```py
"""Defines a multi source sequence to sequence model. Source sequences are read
from 2 files, encoded separately, and the encoder outputs are concatenated in
time.
"""

import tensorflow as tf
import opennmt as onmt

def model():
  return onmt.models.SequenceToSequence(
      source_inputter=onmt.inputters.ParallelInputter([
	                onmt.inputters.WordEmbedder(
              vocabulary_file_key="source_words_vocabulary",
              embedding_size=512,
              tokenizer=onmt.tokenizers.CharacterTokenizer()),
          onmt.inputters.WordEmbedder(
              vocabulary_file_key="source_words_vocabulary",
              embedding_size=512,
              tokenizer=onmt.tokenizers.CharacterTokenizer()),
         .... (52 times)]),
      target_inputter=onmt.inputters.WordEmbedder(
			  vocabulary_file_key="target_words_vocabulary",
			  embedding_size=512,
			  tokenizer=onmt.tokenizers.CharacterTokenizer()),
      encoder=onmt.encoders.ParallelEncoder([
          onmt.encoders.BidirectionalRNNEncoder(
                  num_layers=2,
                  num_units=100,
                  reducer=onmt.layers.ConcatReducer(),
                  cell_class=tf.contrib.rnn.LSTMCell,
                  dropout=0.3,
                  residual_connections=False),
          onmt.encoders.BidirectionalRNNEncoder(
                  num_layers=2,
                  num_units=100,
                  reducer=onmt.layers.ConcatReducer(),
                  cell_class=tf.contrib.rnn.LSTMCell,
                  dropout=0.3,
                  residual_connections=False),
         ................ (52 times)],
          outputs_reducer=onmt.layers.ConcatReducer(axis=1)),
      decoder=onmt.decoders.AttentionalRNNDecoder(
          num_layers=2,
          num_units=100,
          bridge=onmt.layers.DenseBridge(),
          attention_mechanism_class=tf.contrib.seq2seq.LuongAttention,
          cell_class=tf.contrib.rnn.LSTMCell,
          dropout=0.3,
          residual_connections=False))

```
Now here are 3 question I have:

1. Why is there a check for [same size on source files](https://github.com/OpenNMT/OpenNMT-tf/blob/d3a4ec4cfe171ad03b36233d7070e3f8f8e2c755/opennmt/inputters/inputter.py#L303)? 

     My files have different sizes and hence I skipped this check by returning the total file size like this
```
 dataset_size = dataset_sizes[0]
    for size in dataset_sizes:
	    dataset_size += size
#      if size != dataset_size:
#        raise RuntimeError("The parallel data files do not have the same size")
    return dataset_size
```
2.  I cannot have parallel input for target files. 
     So the method mentioned abpve is the right way to provide multi source and coresponding multi target files?

3.  After making the changes in the inputter.py the model is being trained but I am but I am not able to make infrerence on the trained model. I keep getting the error `The number of input lines does not match the file inputters`.

Would really appreciate help on this topic.

**Comment by guillaumekln** [comment]
1. As the sentence is the training unit of a sequence-to-sequence model, all training files must be aligned (and thus, have the same size). I'm not sure how one could define multi-source training without aligned source files.

2. Multi target file is not supported. If you could describe the nature of your task, that could be helpful to understand your need. For example, what are those 52 source files and how are they related? Training 52 encoders in parallel seems a bit much, both for memory usage and the convergence of the training. There could be data preparation tricks that simulate multi-source training.

3. Is this the actual error reported by OpenNMT-tf? I don't seem to find it in the code.

**Comment by R1j1t** [comment]
Thanks for the reply.

1. So my use case is similar to the example where I have 52 chapters of a book and have a translation of each chapter in a particular language. Because of this, the file length is not constant. In both the files (source and target) they have 1 sentence per line. But in few files, 1 sentence in the source is equivalent to 2 sentences (and hence 2 lines) in the target file. I think this is where the problem might be. These 52 target files are all in one language and after reading your reply, I realize that in NLP multi-source training mean having source files in different languages.

The exact error was 
```py
  File "c:\programdata\anaconda3\lib\site-packages\opennmt\inputters\inputter.py
", line 288, in make_dataset
    raise ValueError("The number of data files must be the same as the number of
 inputters")
ValueError: The number of data files must be the same as the number of inputters
```

Just to summarize: 
52 source files in 1 language
52 target files in 1 langauge (different from source)
Because of the nomenclature and not knowing about something called multi-source training was actually for multiple languages I made this mistake.

I think I will have to manually correct the files, then merge them and then train using NMTSmall or NMTMedium.

**Comment by guillaumekln** [comment]
Indeed, that is not the use case for multi-source training which is more about enhancing the representation of a main source (e.g. with rough translations or some sort of annotations).

On the other hand, your task is more about preparing a parallel dataset from translated content.

**Comment by R1j1t** [comment]
I understand but thanks for the quick reply, I really appreciate your help.
