### ISSUE TITLE
Question: Distributed training on multiple servers 

### ISSUE THREAD

**Issue by lockder** [OpenNMT/OpenNMT-tf#163]
I’m trying to run a distributed training on multiple servers, but I’ must be doing something wrong, the documentation is not well explained or I don’t understand it fully.
I tried to do run the next command

on host 0
CUDA_VISIBLE_DEVICES=0 onmt-main train […] 
–ps_hosts host0:2222 
–chief_host host0:2223 
–worker_hosts host1:2224 
–task_type ps 
–task_index 0

then in another terminal
CUDA_VISIBLE_DEVICES=0 onmt-main train […] 
–ps_hosts host0:2222 
–chief_host host0:2223 
–worker_hosts host1:2224 
–task_type chief 
–task_index 0

on host 1

CUDA_VISIBLE_DEVICES=0 onmt-main train […] 
–ps_hosts host0:2222 
–chief_host host0:2223 
–worker_hosts host1:2224 
–task_type worker 
–task_index 0

also I tried to run only with chief and worker but always the last sencente of the system is " INFO:tensorflow:Graph was finalized. "

Then the terminal remaings waiting to forever. What I ’ am doing wrong?

**Comment by guillaumekln** [comment]
I should verify that the distributed training is correctly setup but we are mostly populating environment variables and then let TensoFlow do the actual job.

Did you also read the documentation at: https://www.tensorflow.org/api_docs/python/tf/estimator/train_and_evaluate?

**Comment by lockder** [comment]
What i see I’m missing model dir shared between workers.
What I’m not sure if a machine can be chief, worker and ps at the same time and another machine just a worker since for now i have only 2 machines

Enviado desde mi iPhone

**Comment by lockder** [comment]
Also I tried to do it on the same machine with multiple gpu to check if the issue was the shared folder but it didn't work either. So something is missing or I'm doing it wrong.
What I see when the training starts is tensorflow saying _train_distribute : None

**Comment by lockder** [comment]
now its working, that was the issue 💃

**Comment by guillaumekln** [comment]
Do you mean the evaluation during `train_and_eval`? If so, I think it should run on the chief instance.

**Comment by lockder** [comment]
I mean the eval mode, you can do it separated like the train.
I guess it will not work because looks like distributed training works only with train and eval

Enviado desde mi iPhone

**Comment by guillaumekln** [comment]
I think only `train_and_eval` works in distributed settings. However, there is a task type `evaluator` (just like `chief` or `worker`) but this is scarcely documented in TensorFlow.

**Comment by lockder** [comment]
yes I saw that. Thank you so much for your help!
