### ISSUE TITLE
Pretrained word embeddings: Is there a tutorial on where to get started?

### ISSUE THREAD

**Issue by miikargh** [OpenNMT/OpenNMT-tf#164]
Hi!

I'm trying to train a Finnish-to-English translation model and it works great with the CLI. The problem is that I want to add pretrained word embeddings (Fasttext) to get better results but can't find how to do that with the CLI so I'm looking to build a new training script using OpenNMT-tf as a library.

I wonder if there is a tutorial for doing such a thing that you could point me to?

Cheers!

**Comment by guillaumekln** [comment]
Hello,

You can use the CLI to add pretrained word embeddings but you need to provide a custom model file to the `--model` command line option.

Some model files are available in the `config/models` directory on GitHub (some configurations simply invokes the [model catalog](https://github.com/OpenNMT/OpenNMT-tf/blob/master/opennmt/models/catalog.py)).

For example, the `SeqTagger` is defined with pretrained embeddings:

https://github.com/OpenNMT/OpenNMT-tf/blob/v1.5.0/opennmt/models/catalog.py#L109-L136

You should then set in your run configuration:

```yml
data:
  words_embedding: /path/to/pretrained/embeddings.txt
```

See also the [`WordEmbedder` documentation](http://opennmt.net/OpenNMT-tf/package/opennmt.inputters.text_inputter.html#opennmt.inputters.text_inputter.WordEmbedder) for a complete list a pretrained embeddings options.

**Comment by miikargh** [comment]
Hi,

Thanks for the swift reply!

How will I differentiate between the target words_embedding and source words_embedding?

Something like this?
```yaml
data:
  target_words_embedding: /path/to/target_embeddings.txt
  source_words_embedding: /path/to/source_embeddings.txt
```

**Comment by guillaumekln** [comment]
That's what the argument `embedding_file_key` of `WordEmbedder` is for: you can set it to whatever key you want to use in the training configuration.
