### ISSUE TITLE
Possibly incorrect init of ROUGEEvaluator

### ISSUE THREAD

**Issue by cholakov** [OpenNMT/OpenNMT-tf#165]
Hi –

I was having problems running the ROUGE Evaluator. After some digging, I believe there is a small bug. Do you think this line should change

from:

`super(ROUGEEvaluator, self).__init__(labels_file=output_dir, output_dir=output_dir)`

to:

`super(ROUGEEvaluator, self).__init__(labels_file=labels_file, output_dir=output_dir)`

https://github.com/OpenNMT/OpenNMT-tf/blob/b6bfbf178b8d39307848f6e011a6b3b8ce1625ee/opennmt/utils/evaluator.py#L73

**Comment by guillaumekln** [comment]
Hi,

Yes, that's a mistake. Do you mind sending a PR? Thanks.

**Comment by cholakov** [comment]
Not all. Just sent you a PR. Thanks.

**Comment by guillaumekln** [comment]
Fixed by #166.
