### ISSUE TITLE
Self-attention decoding is slow

### ISSUE THREAD

**Issue by guillaumekln** [OpenNMT/OpenNMT-tf#17]
Self-attention decoding is slow by design. However, some tricks were implemented in [Tensor2Tensor](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/models/transformer.py) to make the decoding faster. We should learn about those tricks and implement similar optimizations.

**Comment by gsoul** [comment]
As for the speed of Transformer decoder, SalesForce published a new paper yesterday: https://einstein.ai/research/non-autoregressive-neural-machine-translation
where they suggest to decode all the words in parallel

**Comment by guillaumekln** [comment]
Thanks for the paper; we should keep an eye on related developments.

I'm closing this issue as the decoding is now way faster than before.
