### ISSUE TITLE
GPU memory utilization question

### ISSUE THREAD

**Issue by ptamas88** [OpenNMT/OpenNMT-tf#175]
Hello everone!

We are trying to optimize the models for best results, and create the smartest(biggest?) possible model.
I have tried to decide which parameters effects the GPU memory allocation and I am pretty sure that in model config file
- encoder and decoder layer numbers (num_layers)
- encoder and decoder unit numbers (num_units)

not so sure of the sample buffer size in train config file (sample_buffer_size)
and really cant decide about the maximum feature/label size (maximum_features_length,maximum_labels_length)

Can you help me what have I missed?
Thanks

**Comment by guillaumekln** [comment]
Hello,

Here are some configurations that impact the GPU memory usage:

* Model size, i.e. the number of trainable parameters (`num_layers`, `num_units`, etc.)
* Vocabulary size
* Batch size
* Maximum sequence lengths

The sample buffer size only impacts the CPU memory.

**Comment by ptamas88** [comment]
Thanks for the quick response!
How much the vocab size matters? eg. 20k or 30k vocab is how much difference?

**Comment by guillaumekln** [comment]
It's difficult to answer as it depends on all the other settings listed above.
