### ISSUE TITLE
PyramidalRNN (LAS model) reduction computations

### ISSUE THREAD

**Issue by robertodessi** [OpenNMT/OpenNMT-tf#176]
While inspecting the code for ListenAttendSpell model I checked the reduction hops done by the encoder and there's something that I do not understand:

1) shouldn't the total reduction factor be 8 in case of a 3 layer encoder? In the code seems like it is 4
https://github.com/OpenNMT/OpenNMT-tf/blob/4322933336a63cb17851d8d54097213375f8b22b/opennmt/encoders/rnn_encoder.py#L285

2) in the paper they mention a 3 layers pBLSTM on top of a BLSTM, it seems to me that in the code there's only the pBLSTM and not the bottom BLSTM, is that correct?

**Comment by guillaumekln** [comment]
Thanks for your question. It seems the implementation is a bit misleading relative to the paper.

The implemented `PyramidalEncoder` is already the combination of the "pBLSTM" and "BLSTM" as described in the paper. As the reduction is applied to the input of each layer (excluding the first), there are `len(self.layers) - 1` reductions.

So if you set the number of layers to 3, you effectively get the encoder shown in *Figure 1*:

![image](https://user-images.githubusercontent.com/4805513/42831628-1c76d2f0-89ef-11e8-8e87-3d711ecbc65c.png)

Hope that clarifies the difference.

**Comment by robertodessi** [comment]
Thanks for your quick reply!

I understand your explanation but it still doesn't make sense with what I understood about the paper:

One BLSTM layer of the some length of the input (e.g. 16) and thus no reduction. On top of a this a 3 layers pBLSTM with reduction of a factor of 2 before each layer (thus a 2**3=8 reduction factor on the initial input) and emitting a vector of length 2 from the final layer of the encoder in this toy example.

I'm now thinking that setting num_layers=4 would reproduce the paper more closely, would that work?

From the code it also seems that on the decoder side only the first layer makes use of an attention mechanism, is there a reason for this? 
And why is LuongMonotonicAttention used rather than LuongAttention? 

Thanks a lot again!

**Comment by guillaumekln** [comment]
Maybe you are just confused with input vs output reductions?

Take a look at the figure above. The bottom layer is the BLSTM layer that operates on the full input, no reduction. On top of that, there is a 2-layer pBLSTM where each layer reduces its input by a factor of 2 (total reduction = 2*2). This is what you get in OpenNMT-tf when you use a `PyramidalEncoder` with `num_layers=3`.

> I'm now thinking that setting num_layers=4 would reproduce the paper more closely, would that work?

That is correct.

> From the code it also seems that on the decoder side only the first layer makes use of an attention mechanism, is there a reason for this?

As far as I know, this is what is used in the paper (see the "Speller" in *Figure 1*).

> And why is LuongMonotonicAttention used rather than LuongAttention?

For this task, we know that there is no reordering so why not include this knowledge in the model.

---

Bottom-line: the implementation may not be 100% equivalent to the paper but we had success training this model  in the past with the LuaTorch implementation of OpenNMT.

**Comment by robertodessi** [comment]
> Maybe you are just confused with input vs output reductions?
> 
> Take a look at the figure above. The bottom layer is the BLSTM layer that operates on the full input, no reduction. On top of that, there is a 2-layer pBLSTM where each layer reduces its input by a factor of 2 (total reduction = 2*2). This is what you get in OpenNMT-tf when you use a PyramidalEncoder with num_layers=3.

Ok I get it now. I wasn't sure I understood the paper correctly or it was the implementation that was slightly different.

> For this task, we know that there is no reordering so why not include this knowledge in the model.

I see, it makes a lot of sense actually.

> As far as I know, this is what is used in the paper (see the "Speller" in Figure 1).

Again, as far as I understood in the paper they used a 2 layer decoder. In case of a 3 layer decoder (like the one in OpenNMT-tf) did you experiment with the attention mechanism on every layer or do you think it could be somehow beneficial? 

Another question, I trained the LAS model on a 170k samples train set and evaluated on a 1k dev set working on character level for a speech translation task. Other than being a bit slow (no less than 5 mins for 100 steps), after 22k steps it outputs translation that are all the same (or maybe some minor difference on a couple of sentences) for every single sample in the dev set. Then at around 24k, after shuffling the train data (500k buffer dimension), the process gets killed showing no error message of any kind. Any idea.

Thanks a lot for your help!

**Comment by guillaumekln** [comment]
> In case of a 3 layer decoder (like the one in OpenNMT-tf) did you experiment with the attention mechanism on every layer or do you think it could be somehow beneficial?

I did not conduct such experiment. Should be easy to do though.

> Other than being a bit slow (no less than 5 mins for 100 steps), after 22k steps it outputs translation that are all the same (or maybe some minor difference on a couple of sentences) for every single sample in the dev set.

Are you training with a GPU?
Also I'm not sure if 22k steps is enough to train this model.

**Comment by robertodessi** [comment]
> I did not conduct such experiment. Should be easy to do though.

yes I'll give it a try, maybe reproducing the paper with 4 layers on the encoder side and 2 layers for the decoder.

> 
> Are you training with a GPU?
> Also I'm not sure if 22k steps is enough to train this model.

Yes, I am using a GPU.
I've also done multiple runs with multi gpus (2 and 4).
I did not get passed 24k steps due to the crash so I am trying to understand what's causing it.

**Comment by guillaumekln** [comment]
Closing this issue. I think the architecture that is implemented in OpenNMT-tf was clarified.
