### ISSUE TITLE
Deploying trained model in Azure DSVM model management as Web Service.

### ISSUE THREAD

**Issue by santoshchanveer** [OpenNMT/OpenNMT-tf#177]
I have trained the NMT model in azure DSVM. Now i want to deploy this model into Azure Model Management.  I am completely new for this so i need some help.

Thanks.

**Comment by guillaumekln** [comment]
Did you read this entrypoint in the documentation:

http://opennmt.net/OpenNMT-tf/serving.html

**Comment by santoshchanveer** [comment]
hello guillaumekln,
thanks for interest, yes i gone through it. Now i just want to deploy  the trained  model in azure model managent environment " https://docs.microsoft.com/en-us/azure/machine-learning/desktop-workbench/tutorial-classifying-iris-part-3" . I have completed all the prerequisite installation. I am facing problem in deploying web service.

**Comment by guillaumekln** [comment]
Is there an issue with OpenNMT-tf specifically? Looks like it's more about how to use Microsoft Azure and it's not the right place to ask (I never used this service).

A standard way of serving your trained model is to grab a [TensorFlow Serving Docker image](https://hub.docker.com/r/tensorflow/serving/) and run it on any cloud instance.

**Comment by santoshchanveer** [comment]
yes i was facing the issue with docker. While building the docker the build getting failed.

**Comment by guillaumekln** [comment]
If you have issues with TensorFlow Serving you should head to [their GitHub repository](https://github.com/tensorflow/serving) and open an issue there.
