### ISSUE TITLE
Problem in quickstart example

### ISSUE THREAD

**Issue by mattgittings** [OpenNMT/OpenNMT-tf#18]
I am following the toy example in the Quickstart section, and receive:

`TypeError: __init__() got an unexpected keyword argument 'model_dir'`

at main.py line 256 when trying to train the model in step 2.

**Comment by gsoul** [comment]
Please provide the exact command that you use to run the script. And please check if "model_dir" parameter is set in one of the *.yml config files that you pass to the script as parameters.

Like the first line here:
https://github.com/OpenNMT/OpenNMT-tf/blob/master/config/data/toy-ende.yml

**Comment by mattgittings** [comment]
I use `python -m bin.main train --model config/models/nmt_small.py --config config/opennmt-defaults.yml config/data/toy-ende.yml` from step 2.

the model_dir in toy-ende.yml is set to "model_dir: toy-ende" - this file is unchanged.

**Comment by guillaumekln** [comment]
The required TensorFlow version is 1.4. Make sure that your installation is up-to-date.

**Comment by mattgittings** [comment]
Whoops - got confused between my virtual environments. This resolved my issue. Thank you!
