### ISSUE TITLE
Distributed Training, Parameter Server doesn't end when the work is done

### ISSUE THREAD

**Issue by lockder** [OpenNMT/OpenNMT-tf#181]
I have been searching and this is an issue from tensorflow itself. There are some workarounds but that means the library should have the changes to make it work.

I'm not sure if could I try to do it myself and send you the code somehow or this would be implemented in some future

I add the link below with the solution proposed by the community:
https://stackoverflow.com/questions/39810356/shut-down-server-in-tensorflow/40186129#40186129

**Comment by guillaumekln** [comment]
Yes, this is a TensorFlow issue, not OpenNMT-tf.

**Comment by guillaumekln** [comment]
If you think that is an issue, you should first open an issue on the [TensorFlow repository](https://github.com/tensorflow/tensorflow). The TensorFlow team will then review it.
