### ISSUE TITLE
average_last_checkpoints crashes in distributed training

### ISSUE THREAD

**Issue by lockder** [OpenNMT/OpenNMT-tf#183]
1.5.0 (2018-06-08)
New features
Training option average_last_checkpoints to automatically average checkpoints at the end of the training

 Reading the new features I found on 1.5.0 an amazing new parameter to automatically do the avg of the checkpoints  but when I try to use I get this message.

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/ubuntu/NaturalLanguageRecognition/NaturalLanguageManager/src/Intent_Classification/model/model.ckpt-369
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_INT64, DT_FLOAT, DT_INT64], _device="/job:ps/replica:0/task:0/device:CPU:0"](_recv_save/Const_0_S1, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[Node: save/restore_all/NoOp_1_S8 = _Recv[client_terminated=false, recv_device="/job:chief/replica:0/task:0/device:GPU:0", send_device="/job:ps/replica:0/task:0/device:CPU:0", send_device_incarnation=8143571150034301869, tensor_name="edge_247_save/restore_all/NoOp_1", tensor_type=DT_FLOAT, _device="/job:chief/replica:0/task:0/device:GPU:0"]()]]

I went to the console and did the ls inside the folder

ubuntu@mltraining:~/NaturalLanguageRecognition/NaturalLanguageManager/src/Intent_Classification/model$ ls
checkpoint  events.out.tfevents.1532590583.mltraining  graph.pbtxt        model.ckpt-369.meta    projector_config.pbtxt  src_word_vocab.txt
eval        events.out.tfevents.1532591278.mltraining  model.ckpt-0.meta  model_description.pkl  src_char_vocab.txt

Then I went to the checkpoint file and took a look:

model_checkpoint_path: "model.ckpt-369"
all_model_checkpoint_paths: "model.ckpt-0"
all_model_checkpoint_paths: "model.ckpt-369"

looks like its trying to find the name inside the checkpoint but its saved with the extension .meta
The weird thing its the restore training works very well its just when doing the average of the checkpoints

**Comment by guillaumekln** [comment]
Are you using distributed training? I'm not sure checkpoint averaging is correctly supported in this scenario. Thanks for reporting.

**Comment by lockder** [comment]
yes I'm using distributed training , looking to the code, its checking if its a chief machine before doing the avg. Also I tried to run the script manually and its happening the same thing

**Comment by guillaumekln** [comment]
Thanks. Not sure how to handle correctly this case yet so I need to investigate. Feel free to share any insights.

**Comment by lockder** [comment]
I will try to train it without distributed training and see what happens. if I find the fix I will send it to you

**Comment by lockder** [comment]
also using non distributed training 
checkpoints_path = tf.train.get_checkpoint_state(model_dir).all_model_checkpoint_paths
is returning a list of strings with the path of the file
Instead on distributed is returning an object. RepeatedScalarContainer with the path of the meta files

**Comment by lockder** [comment]
Well Its not a fix but if you setup the chief and ps machine the same. then it will work since it will have all the files on the same machine and the other pc can be setup as workers

**Comment by guillaumekln** [comment]
> Well Its not a fix but if you setup the chief and ps machine the same. then it will work since it will have all the files on the same machine and the other pc can be setup as workers.

I think that is the expected behavior. I also read that one should consider using a shared filesystem to properly load a checkpoint produced by a distributed training.

With all this information, I don't think there is anything to change in OpenNMT-tf.

**Comment by lockder** [comment]
Well it will only work if you have on the same machine all files :) but it will not work if you setup a different ps machine to free up gpu memory so you can have a bigger model or bigger batch size. I tried to setup the ps on a cpu machine but it was more slow.
and I'm not sure if you have more than 1 ps server what will happen jejeje

The other issue is the code its finding only the last checkpoint not sure why even if there are more than one checkpoint , so its getting the last one, and not doing and avg

**Comment by guillaumekln** [comment]
HDFS could be used to share a filesystem across separate machines. Not sure if it requires code change or not.

> The other issue is the code its finding only the last checkpoint not sure why even if there are more than one checkpoint , so its getting the last one, and not doing and avg

What value did you set to `average_last_checkpoints`?

**Comment by lockder** [comment]
I see, for the readme I was adding true instead a number :P my mistake! thanks

**Comment by guillaumekln** [comment]
According to me, the only action required by this issue is to better support remote/shared filesystems like HDFS or S3. The PR above improves the support of such configurations for the model directory and data files.

Closing for now.
