### ISSUE TITLE
Crash loading parallel inputs with --data_dir

### ISSUE THREAD

**Issue by lockder** [OpenNMT/OpenNMT-tf#187]
I found the next issue if I follow the tutorial and try to do

data:
  train_features_file:
    - train_source_1.records
    - train_source_2.txt
    - train_source_3.txt

in main.py at the method _prefix_paths
new_path = os.path.join(prefix, path) 
will crash because paths is a list and join can't be done on a list.

The fix should be just check the instance type at paths and iterate

**Comment by lockder** [comment]
Sure, tomorrow i will be back to the office and i can send it to you if you tell me how to do it

**Comment by lockder** [comment]
not sure how to send you the code.

its just substitute inside main.py

_prefix_paths with this method

def _prefix_paths(prefix, paths):
  """Recursively prefix paths.

  Args:
    prefix: The prefix to apply.
    data: A dict of relative paths.

  Returns:
    The updated dict.
  """
  if isinstance(paths, dict):
    for key, path in six.iteritems(paths):
      paths[key] = _prefix_paths(prefix, path)
    return paths
  elif isinstance(paths, list):
      fixedPaths = list()

      for path in paths:
        fixedPaths.append(_prefix_paths(prefix,path))

      return fixedPaths
  else:
    path = paths
    new_path = os.path.join(prefix, path)
    if os.path.isfile(new_path):
      return new_path
    else:
      return path

**Comment by guillaumekln** [comment]
I will fix it. Note that it only happens when you use the `--data_dir` command line option.
