### ISSUE TITLE
Some translations return more than one </s>

### ISSUE THREAD

**Issue by jordimas** [OpenNMT/OpenNMT-tf#188]
When requesting a translation using the nmt_client.py with a generated model some translations return a `</s>` at the end. nmt_client.py  removes one `</s>` but some results contains two `</s></s>`

You can reproduce the problem using this model:

https://github.com/jordimas/nmt-softcatala/tree/master/models/1531713563

Making this change to nmt_client.py :

@@ -69,7 +69,7 @@ def main():
   stub = prediction_service_pb2.beta_create_PredictionService_stub(channel)
 
   batch_tokens = [
-      ["Hello", "world", "!"],
+      ["The", "line", "join", "style", "to", "use"],
       ["My", "name", "is", "John", "."],
       ["I", "live", "on", "the", "West", "coast", "."]]

Tensorflow serving:
tensorflow_model_server --port=9000 --enable_batching=true --batching_parameters_file=batching_parameters.txt --model_name=1531713563 --model_base_path=$(realpath ../models)

Asking for the translation of sentence using:
python3 nmt_client.py --host=localhost --port=9000 --model_name=1531713563

The translation returned for 'The line join style to use' is ' L'estil de línia a utilitzar`</s>`'

Extra details:
- I have been unable to determine why some translations return more than one `</s>`
- I have been able to reproduce this with any model that I generate
- I use TensorFlow 1.8, Python 3 and Ubuntu

**Comment by guillaumekln** [comment]
Do you get the same output when you `infer` from a training checkpoint?

**Comment by guillaumekln** [comment]
So it's a model issue and not related to TensorFlow Serving.

What beam width are you using? There may be a bug in the TensorFlow beam search code as the returned length should only include the final `</s>`. A simple workaround would be to print up to the first `</s>`.

That being said, we never faced this issue on non toy datasets.

**Comment by jordimas** [comment]
I'm using the default opennmt-defaults.yml what set "beam_width: 5"

When I get the translations I removed all the </s> and this works but I think that it's good that you know about the issue

**Comment by weiwancheng** [comment]
I have the same problem, the beam search not end with 'eos' symbol. So, there are  same sentences generated by beam search. this condition is  resulted from many 'eos' symbol in one sentence. who can explain this problem about the tf beam search code?

**Comment by guillaumekln** [comment]
Which decoder type are you using?

**Comment by weiwancheng** [comment]
@guillaumekln Thank your reply. I use api as follow:
`
inference_decoder = BeamSearchDecoder( cell=self.decoder_cell, embedding=embed_and_input_proj, start_tokens=start_tokens, end_token=end_token, initial_state=self.decoder_initial_state, beam_width=self.beam_width, output_layer=self.decoder_output_projection, )
...
 (self.decoder_outputs_decode,self.final_state,_ )= (seq2seq.dynamic_decode(
                    decoder=inference_decoder,
                    output_time_major=self.time_major,
                    # impute_finished=True,	# error occurs
                    maximum_iterations=max_decode_step,
                    # parallel_iterations=self.parallel_iterations,
                    swap_memory=True,
                    scope=decoder_scope
                ))
`

**Comment by weiwancheng** [comment]
@guillaumekln Thank your reply. I use api as follow:

inference_decoder = BeamSearchDecoder( cell=self.decoder_cell, embedding=embed_and_input_proj, start_tokens=start_tokens, end_token=end_token, initial_state=self.decoder_initial_state, beam_width=self.beam_width, output_layer=self.decoder_output_projection, ) 
... 
(self.decoder_outputs_decode,self.final_state,_ )= (seq2seq.dynamic_decode( decoder=inference_decoder, output_time_major=self.time_major, # impute_finished=True, # error occurs maximum_iterations=max_decode_step, # parallel_iterations=self.parallel_iterations, swap_memory=True, scope=decoder_scope ))

**Comment by guillaumekln** [comment]
As these are pure TensorFlow APIs, you should probably open an issue on the TensorFlow repository.

**Comment by weiwancheng** [comment]
Yes, I have done, but nobody help. so I just want to ask if someone has encountered this problem here.

**Comment by guillaumekln** [comment]
Let's close this issue as it is fundamentally a TensorFlow bug. However, if someone is still facing the issue and is able to send me a checkpoint and files to reproduce, I can take another look.
