### ISSUE TITLE
Continued training in OpenNMT-tf

### ISSUE THREAD

**Issue by raymondhs** [OpenNMT/OpenNMT-tf#190]
Hi, in order to do a continued training with a new data (fine tuning), can I simply change the "data" configuration in YAML file to point to a new set of training and dev sets and keep the vocab files the same? In OpenNMT-py version, there is a -train_from parameter for this. Thanks.

**Comment by guillaumekln** [comment]
Hello, yes you can just change the data files and run the same training command line.

**Comment by raymondhs** [comment]
Great, thanks for your help!
