### ISSUE TITLE
Which library would be best to make OpenNMT a JS/offline service?

### ISSUE THREAD

**Issue by Extarys** [OpenNMT/OpenNMT-tf#196]
If I were to make OpenNMT offline, with which library should I start playing with?

Also, how can I help train the AI to help you?
I'm very new to AI I'm sorry.
Thanks

**Comment by guillaumekln** [comment]
OpenNMT-tf uses TensorFlow so you should read about what TensorFlow has to offer on this aspect:

https://www.tensorflow.org/

**Comment by Extarys** [comment]
Yes but as a requirement it also state python. That is why I was asking the question. I started playing with TensorFlow, it's awesome.

**Comment by guillaumekln** [comment]
There are multiple frontends available for TensorFlow. See the API documentation: https://www.tensorflow.org/api_docs/

But whatever is your language requirement, it's always possible to start a local TensorFlow server that is queried by your application.
