### ISSUE TITLE
How to run training on a specific GPU?

### ISSUE THREAD

**Issue by hadiasheri** [OpenNMT/OpenNMT-tf#200]
I am running the training procedure on a machine with multiple GPUs.
However, I want to use just a specific GPU, eg with id 1.
I can't find any option to do this. The `--num_gpus` option doesn't explicitly determine the GPU id.
I'd be grateful if anyone could help.

**Comment by guillaumekln** [comment]
Set the environment variable `CUDA_VISIBLE_DEVICES` to the GPU ID you want to use, e.g.:

```bash
CUDA_VISIBLE_DEVICES=1 onmt-main [...]
```
