### ISSUE TITLE
About this paper and RNMTPlus

### ISSUE THREAD

**Issue by lockder** [OpenNMT/OpenNMT-tf#213]
Reading papers about RNN I found this paper
https://arxiv.org/pdf/1804.09849.pdf
I see is the same paper used to implement RNMTPlus encoder.
What I don't see the Decoder implemented, as an usable decoder. I see exist the MultiAttentionalRNNDecoder but I don't the first pass where the paper says they use a RNN unidirectional and those outputs are used to feed the MultiAttentionalRNNDecoder and concat the results with the results of the RNN unidirectional.
Am I right?

**Comment by guillaumekln** [comment]
Yes, we are currently missing the decoder that is presented in the paper.

The main reason is that OpenNMT-tf is currently using the high-level TensorFlow module `tf.contrib.seq2seq` that does not make this implementation easy. I'm thinking about replacing it but I would like to wait for TensorFlow 2.0 and see if they make improvements on this aspect.

**Comment by lockder** [comment]
Great. Thank you for your response!

**Comment by guillaumekln** [comment]
FYI, I just added the RNMT+ decoder on master. There is not everything to reproduce the paper yet, but it's a nice alternative to standard RNN decoders. A good experiment would be to use a `SelfAttentionEncoder` + `RNMTPlusDecoder`.

**Comment by lockder** [comment]
Wow you are amazing, thanks so much!

Enviado desde mi iPhone
