### ISSUE TITLE
How to output model with Saved Model Directory format

### ISSUE THREAD

**Issue by mohammedayub44** [OpenNMT/OpenNMT-tf#223]
Hi,

I'm running into an issues with the output files. I need to read the model output into another application for processing. I need the model output to be in the Tensorflow SavesModel Directory structure mentioned here: https://www.tensorflow.org/guide/saved_model#structure_of_a_savedmodel_directory 
Is this straight forward to achieve this ? or what changes to I need to do ?

Thanks !

Mohammed Ayub

**Comment by guillaumekln** [comment]
Hi,

The documentation has a page on this: http://opennmt.net/OpenNMT-tf/serving.html

Let me know if you did not find the relevant/sufficient information in this page.

**Comment by mohammedayub44** [comment]
Hi @guillaumekln 

I did export the model successfully. I'm running a simple Quickstart example from the Documentation site. I have to specify the Outputs of my model to execute it (this application that I'm importing into needs it that way) It gives me the drop down to specify the Outputs, however I'm slightly confused which tensors should I use as the model outputs from the Tensorboard graph below:

![image](https://user-images.githubusercontent.com/7122670/46963403-8ec6a680-d073-11e8-826c-5b78cf293546.png)

![tensorboard_output](https://user-images.githubusercontent.com/7122670/46963515-dd744080-d073-11e8-9185-fb995b20dbbf.png)

**Comment by guillaumekln** [comment]
The documentation that I linked above also mentions the `saved_model_cli` that can be used to show details on the input and output nodes of a model. Can you try to run it?

It should output something like this:

```
The given SavedModel SignatureDef contains the following input(s):
  inputs['length'] tensor_info:
      dtype: DT_INT32
      shape: (-1)
      name: Placeholder_1:0
  inputs['tokens'] tensor_info:
      dtype: DT_STRING
      shape: (-1, -1)
      name: Placeholder:0
The given SavedModel SignatureDef contains the following output(s):
  outputs['length'] tensor_info:
      dtype: DT_INT32
      shape: (-1, 5)
      name: transformer/decoder_1/Sum:0
  outputs['log_probs'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, 5)
      name: transformer/decoder_1/Select_1:0
  outputs['tokens'] tensor_info:
      dtype: DT_STRING
      shape: (-1, 5, -1)
      name: transformer/index_to_string_Lookup:0
Method name is: tensorflow/serving/predict
```

where `name` is the name you are looking for.

In any case, the current names are not very meaningful. I will look to improve that.

**Comment by mohammedayub44** [comment]
@guillaumekln  That solved it. 
Although I could not see `seq2seq/index_to_string_Lookup:0` output tensor in my drop down. Nothing wrong on OpenNMT side, something to troubleshoot on the other application.

Appreciate your timely help. 

Mohammed Ayub
