### ISSUE TITLE
Where is the page that shows 4 lines to train small ONMT model with data in toy-en-de ?

### ISSUE THREAD

**Issue by elacsoft** [OpenNMT/OpenNMT-tf#237]
I've working with small onmt model to train my own data now, my model is trained now I need to test my model but the commands shown previously are suddenly gone.
Please, share that page again.

**Comment by guillaumekln** [comment]
It has been moved to the documentation: http://opennmt.net/OpenNMT-tf/quickstart.html

**Comment by elacsoft** [comment]
Yes I found it in docs, Thank you so much.
