### ISSUE TITLE
Test BLEU Score

### ISSUE THREAD

**Issue by MukundKhandelwal** [OpenNMT/OpenNMT-tf#238]
@guillaumekln 
Hi,
I want to know if there is an option to get the BLEU score on test data set. For example, the training step (shown below) evaluates the BLEU score on the evaluation data set.
onmt-main train_and_eval --model_type Transformer --config data.yml --auto_config --num_gpus 4
However, I need to check the accuracy on my test data set as well. Could you please provide some insight on how I can check that.
Thanks.

**Comment by guillaumekln** [comment]
Hi,

Usually people will run the `infer` step on the test file, detokenize the output, and invoke the [`multi-bleu-detok.perl`](https://raw.githubusercontent.com/OpenNMT/OpenNMT-tf/master/third_party/multi-bleu-detok.perl) script (or similar) on the detokenized translation and reference.

**Comment by MukundKhandelwal** [comment]
Hi,
So I ran the inference using the following command. Based on the documentation, my understanding is that **features_file** is the test file for which we want the translations and **predictions_file** is the name of file in which we want to write the output.
onmt-main infer \
    --config data.yml \
    --features_file nmt_test.en \
    --predictions_file infer_output.txt \
    --auto_config
After running the inference, this is how my predictions_file looks (infer_output.txt):
![image](https://user-images.githubusercontent.com/31802591/47235445-12033780-d3a7-11e8-8ae1-4257017fd5bb.png)
 
Now here are my questions:
![image](https://user-images.githubusercontent.com/31802591/47235560-6a3a3980-d3a7-11e8-8cf0-817809ea8712.png)
- The assets folder is empty in my case. Is it because I didn't use any tokenizer in the first place and hence my outputs are also detokenized? (referring to point 1)
 - You said to invoke multi-bleu-detok.perl. I assume that by using *BLEU-detok* as external_evaluators in data.yml, it should automatically invoke the script. Please correct if I am wrong. (referring to point 2)
- Where exactly should I give the *actual translations file* for the process to compare my test outputs (i,e. infer_output.txt) with actual translations and generate the BLEU-detok values?

Thank you for the help.

**Comment by guillaumekln** [comment]
You have 2 choices when in comes to tokenization:

**1\. Tokenize the data files with your own tokenization tools.**
In this mode, OpenNMT-tf expects and generates a space-separated list of tokens. To evaluate the result, you should then:

* manually detokenize the output
* run an external script like `multi-bleu-detok.perl`

*This is the recommended approach when getting started as you can carefully control what will be passed to the model.*

**2\.Configure a tokenization as described in [Tokenization](http://opennmt.net/OpenNMT-tf/tokenization.html).**
In this mode, OpenNMT-tf expects raw sentences and produces detokenized translation. Thus, it's the only mode where the `BLEU-detok` integrated evaluator makes sense.

---

> The assets folder is empty in my case. Is it because I didn't use any tokenizer in the first place and hence my outputs are also detokenized? (referring to point 1)

Unless you want to serve your model in production settings, you should not care about the assets directory.

**Comment by guillaumekln** [comment]
You should have all information needed to evaluate your model. If you are still struggling with this process, I suggest opening a thread on the [forum](http://forum.opennmt.net) instead.
