### ISSUE TITLE
problem with debugging the opennmt-tf 

### ISSUE THREAD

**Issue by wingsyuan** [OpenNMT/OpenNMT-tf#241]
@guillaumekln
Hi
I am looking foward to debug opennmt-tf to get a clearer understanding of the process of opennmt-tf training; for example, the process of converting the inputs to  embeddings in inputter.py, 
the  process of the embeddings in the model's encoder or decoder.
 when I debug the program,i use the command below:
 python -m pdb ../bin/main.py train_and_eval --model_type NMTSmall --auto_config --config data.yml,
and turned around  in the tensorflow package,can't find the way to the code in the inputter.py or transformer.py...

Is there any convenient way to locate the funtion in the  inputter.py,  transformer.py when debugging and view  the values of variables? 

Thank you for your attention...

**Comment by guillaumekln** [comment]
Hi,

* If you want to find you way into the code, I suggest following a top-down approach and starting from `Model.input_fn()` and `Model.model_fn()`. This methods return a callable that is invoked by the high-level [Estimator](https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator) object.
* If you want to debug values, I suggest using [`tf.Print`](https://www.tensorflow.org/api_docs/python/tf/Print) on a `tf.Tensor`. TensorFlow also provided [an actual debugger](https://www.tensorflow.org/guide/debugger) but I don't know anything about the one.

**Comment by guillaumekln** [comment]
You can find them in the `Model` base class:

* https://github.com/OpenNMT/OpenNMT-tf/blob/v1.10.1/opennmt/models/model.py#L107
* https://github.com/OpenNMT/OpenNMT-tf/blob/v1.10.1/opennmt/models/model.py#L349

**Comment by wingsyuan** [comment]
Hi,
thanks for your  kind reply!
when i run the next file:
https://github.com/OpenNMT/OpenNMT-tf/blob/master/opennmt/tests/model_test.py
and error occur.

2018-10-24 22:21:10.052531: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/device:GPU:1 with 9930 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:03:00.0, compute capability: 6.1)
E.
======================================================================
ERROR: testSequenceToSequenceTraining (__main__.ModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "model_test.py", line 88, in testSequenceToSequenceTraining
    self._testSequenceToSequence(tf.estimator.ModeKeys.TRAIN)
  File "model_test.py", line 73, in _testSequenceToSequence
    features, labels, model.auto_config()["params"], mode, None)
  File "/home/zhangshaoyuan/anaconda3/lib/python3.6/site-packages/opennmt/models/model.py", line 112, in _model_fn
    every_n_steps=config.save_summary_steps,
AttributeError: 'NoneType' object has no attribute 'save_summary_steps'

----------------------------------------------------------------------
Ran 5 tests in 10.914s

what happened?

**Comment by guillaumekln** [comment]
Looks like you are running tests against an older version of OpenNMT-tf? #236 might be relevant.

**Comment by wingsyuan** [comment]
but  i am running against the version :OpenNMT-tf-1.10.1...

**Comment by guillaumekln** [comment]
This test file is not part of 1.10.1 so my assumption above was correct.

**Comment by wingsyuan** [comment]
Thank you for your help!
I install the version 1.11.0, That solved it. , I apologise for the confusion.

**Comment by guillaumekln** [comment]
Let's close this issue. I think you have now several pointers to get started. Feel free to open issues you encounter other specific problems.

**Comment by wingsyuan** [comment]
fa

**Comment by wingsyuan** [comment]
thanks a lot!!!@guillaumekln
