### ISSUE TITLE
the details about the multi-source trainning and multi_features trainning

### ISSUE THREAD

**Issue by wingsyuan** [OpenNMT/OpenNMT-tf#247]
Hi,
@guillaumekln
in README.md, you mention  the multi-source training:e.g. source text and Moses translation as inputs for machine translation.
and I found the codes in the multi-source-nmt.py, i change it into the catalog.py as a new model:

here is my question:
Can you tell me why to start a multi-source trainning(can you recommend some papers? ), and more details about  preparing the two src data ?
my emai address: yuanwings@gmail.com , may i contect you some time?
thanks a lot!!!

**Comment by guillaumekln** [comment]
Hi,

It depends on your task really. Here is an example that uses French and German as inputs and English in target: https://arxiv.org/pdf/1601.00710.pdf

**Comment by guillaumekln** [comment]
This paper for example: https://arxiv.org/pdf/1606.02892.pdf

**Comment by wingsyuan** [comment]
thanks a lot!!!
wish you all the best!

**Comment by wingsyuan** [comment]
Thanks very much for your help!
best wishes!!!

Guillaume Klein <notifications@github.com> 于2018年10月29日周一 下午5:33写道：
