### ISSUE TITLE
How to limit gpu usage

### ISSUE THREAD

**Issue by wingsyuan** [OpenNMT/OpenNMT-tf#248]
Hi,

Maybe I have the same problem below:
 http://forum.opennmt.net/t/how-to-limit-gpu-usage/1856

Here is my question:
Could i limit every gpu memory usage to 50% when i run my translation task by adding some command-line arguments? or changing the config file ?

thanks very much!!!
wingsyuan

**Comment by guillaumekln** [comment]
Hi,

See the documentation to configure the TensorFlow session: http://opennmt.net/OpenNMT-tf/configuration.html#tensorflow-session

In your case, you should replace `allow_growth: true` by `per_process_gpu_memory_fraction: 0.5`.

**Comment by wingsyuan** [comment]
thanks very much!@guillaumekln

**Comment by xustev75** [comment]
@guillaumekln the link does not contain the information you described. Was it because of version?

**Comment by guillaumekln** [comment]
Right, the page has changed.

Since version 2, there is no option to set a GPU memory limit. But you can set the command line option `--gpu_allow_growth` so that TensorFlow allocates the memory as needed.
