### ISSUE TITLE
CUDA Error while training

### ISSUE THREAD

**Issue by MukundKhandelwal** [OpenNMT/OpenNMT-tf#249]
Hi,

Initially, I successfully trained a Transformer model on roughly 13 million sentences and a vocab of 200K and got the results.

However, when I added some more sentences, I got the following error:
![image](https://user-images.githubusercontent.com/31802591/47801117-e4ea4980-dd03-11e8-9989-3c36c09b3e13.png)

I am using an AWS machine and I didn't change any configuration whatsoever.

**Here are the commands I am using for tokenization and train/eval:**

cat train_eng.txt | onmt-tokenize-text --tokenizer OpenNMTTokenizer --tokenizer_config /home/ubuntu/mukund_onmt_v2/token_config.yml > train_eng_token.txt

onmt-main train_and_eval --model_type Transformer --config config.yml --auto_config --num_gpus 1 2>&1 | tee output.log

Here are the snapshots of token_config.yml and config.yml:

![image](https://user-images.githubusercontent.com/31802591/47801549-c6d11900-dd04-11e8-9aa9-3df36fc0966f.png)

![image](https://user-images.githubusercontent.com/31802591/47801608-e7996e80-dd04-11e8-99ec-4a6277307c31.png)

Can someone please help me with this error.

Thanks.

**Comment by guillaumekln** [comment]
Hi,

Which TensorFlow version are you using? Does the message appear consistently at the beginning of each training or does it look random?

**Comment by MukundKhandelwal** [comment]
Hi,

It looked random to me. It didn't appear the next time when I trained the models.
Tensorflow version is 1.10

Thanks again.

**Comment by guillaumekln** [comment]
Do you still face this issue?
