### ISSUE TITLE
question about multi_features_nmt trainning

### ISSUE THREAD

**Issue by wingsyuan** [OpenNMT/OpenNMT-tf#250]
Hi,

in multi_features_nmt.py, you refer to  "vocabulary_file_key="feature_1_vocabulary","and " vocabulary_file_key="feature_2_vocabulary"," 

Here is my question:
How to generate the fearure file and two vocabulary above?
I read the "Linguistic Input Features Improve Neural Machine Translation", but I still can not get more details about ,can you give me some sample files ? 

thanks very much!
wings yuan

**Comment by guillaumekln** [comment]
What are the features you plan to use? For example, if the feature is part of speech tags then your input files should look like this:

```
$ head -1 train-features-1.txt
Pierre Vinken , 61 years old , will join the board as a nonexecutive director Nov. 29 .
$ head -1 train-features-2.txt
NNP NNP , CD NNS JJ , MD VB DT NN IN DT JJ NN NNP CD .
```

and vocabulary 1 is the standard word vocabulary and vocabulary 2 is the vocabulary of the POS tags.

**Comment by wingsyuan** [comment]
Hi,
@guillaumekln 
thanks for your help!
I want to use morph features 、POS tags、dependency labels , but I have no idea of how to generate these feature files， is there any detail process such as some  scripts? and i want to try an multi_features_nmt trainning demo?  is there a quick start about data processing?

**Comment by wingsyuan** [comment]
Hi,
@guillaumekln 

I use the scripts  to gennerate four feature file（subword tag， lemma, part of speech tag, depparse）:
![image](https://user-images.githubusercontent.com/39689891/47964801-d42a3280-e079-11e8-8284-ffdf036f55f1.png)
Can i just modify the code  in the multi_features_nmt.py, like below:

def model():
  return onmt.models.SequenceToSequence(
      source_inputter=onmt.inputters.ParallelInputter([
          onmt.inputters.WordEmbedder(
              vocabulary_file_key="source_words_vocabulary",
              embedding_size=512),
          onmt.inputters.WordEmbedder(
              vocabulary_file_key="feature_1_vocabulary",
              embedding_size=16),
          onmt.inputters.WordEmbedder(
              vocabulary_file_key="feature_2_vocabulary",
              embedding_size=64),
          onmt.inputters.WordEmbedder(
              vocabulary_file_key="feature_3_vocabulary",
              embedding_size=?),
          onmt.inputters.WordEmbedder(
              vocabulary_file_key="feature_4_vocabulary",
              embedding_size=?)],

can you tell me why the embedding_size is seted to 16 or 64? if now four feature files how to set the embedding_size?

Thanks very much!
wings yuan

**Comment by guillaumekln** [comment]
The embedding size is a hyperparameter that depends on the feature and the number of possible values it can take. See for example:

https://www.quora.com/How-do-I-determine-the-number-of-dimensions-for-word-embedding

**Comment by wingsyuan** [comment]
Hi,
as the paper say feature vector concatenation, can i set the total  vector size =512 below?
 def model():
  return onmt.models.SequenceToSequence(
      source_inputter=onmt.inputters.ParallelInputter([
          onmt.inputters.WordEmbedder(
              vocabulary_file_key="source_words_vocabulary",
              embedding_size=282),
          onmt.inputters.WordEmbedder(
              vocabulary_file_key="feature_1_vocabulary",
              embedding_size=10),
          onmt.inputters.WordEmbedder(
              vocabulary_file_key="feature_2_vocabulary",
              embedding_size=200)，
          onmt.inputters.WordEmbedder(
              vocabulary_file_key="feature_3_vocabulary",
              embedding_size=10),
          onmt.inputters.WordEmbedder(
              vocabulary_file_key="feature_4_vocabulary",
              embedding_size=10)],
          reducer=onmt.layers.ConcatReducer()),
      target_inputter=onmt.inputters.WordEmbedder(
          vocabulary_file_key="target_words_vocabulary",
          embedding_size=512),

**Comment by guillaumekln** [comment]
Yes, this configuration looks reasonable.

**Comment by wingsyuan** [comment]
@guillaumekln 
but the source word  is reduce from 512 to 282,   hopefule  no problem...

**Comment by wingsyuan** [comment]
thanks a lot!

**Comment by guillaumekln** [comment]
The configuration looks good to me. The code uses the value of `vocabulary_file_key` to locate the correct vocabulary file in the data configuration.

**Comment by wingsyuan** [comment]
@guillaumekln 
thanks!

**Comment by wingsyuan** [comment]
Hi,

So sorry to disturb you again，same issue,when I try the muti-feature trainning, as I use the config file below , the error occur， I don't know what happed.
![image](https://user-images.githubusercontent.com/39689891/48069703-091cbd80-e211-11e8-9226-b86177537518.png)
![image](https://user-images.githubusercontent.com/39689891/48069743-2782b900-e211-11e8-91b5-2b04bef1a558.png)


INFO:tensorflow:loss = 1.6738138, step = 58900 (30.648 sec)
INFO:tensorflow:words_per_sec/features: 19633.4
INFO:tensorflow:words_per_sec/labels: 17588.9
INFO:tensorflow:Saving checkpoints for 58933 into run/model.ckpt.
INFO:tensorflow:Loss for final step: 1.7185309.
Traceback (most recent call last):
  File "/anaconda3/bin/onmt-main", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.6/site-packages/opennmt/bin/main.py", line 161, in main
    runner.train_and_evaluate()
  File "/anaconda3/lib/python3.6/site-packages/opennmt/runner.py", line 216, in train_and_evaluate
    tf.estimator.train_and_evaluate(self._estimator, train_spec, eval_spec)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 447, in train_and_evaluate
    return executor.run()
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 531, in run
    return self.run_local()
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 681, in run_local
    eval_result, export_results = evaluator.evaluate_and_export()
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 886, in evaluate_and_export
    hooks=self._eval_spec.hooks)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 453, in evaluate
    input_fn, hooks, checkpoint_path)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1346, in _evaluate_build_graph
    model_fn_lib.ModeKeys.EVAL))
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 985, in _get_features_and_labels_from_input_fn
    result = self._call_input_fn(input_fn, mode)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1074, in _call_input_fn
    return input_fn(**kwargs)
  File "/anaconda3/lib/python3.6/site-packages/opennmt/models/model.py", line 483, in <lambda>
    maximum_labels_length=maximum_labels_length)
  File "/anaconda3/lib/python3.6/site-packages/opennmt/models/model.py", line 369, in _input_fn_impl
    feat_dataset, feat_process_fn = self._get_features_builder(features_file)
  File "/anaconda3/lib/python3.6/site-packages/opennmt/models/model.py", line 318, in _get_features_builder
    dataset = self.features_inputter.make_dataset(features_file)
  File "/anaconda3/lib/python3.6/site-packages/opennmt/inputters/inputter.py", line 300, in make_dataset
    raise ValueError("The number of data files must be the same as the number of inputters")
ValueError: The number of data files must be the same as the number of inputters

**Comment by guillaumekln** [comment]
You should also list the factors files in `eval_features_file`.

**Comment by wingsyuan** [comment]
really appreciate your help @guillaumekln 
thanks
