### ISSUE TITLE
OpenNMT-tf - how to use alignments and phares tables 

### ISSUE THREAD

**Issue by mohammedayub44** [OpenNMT/OpenNMT-tf#252]
Hi,

I could not find any extensive tutorial on how to create/use guided alignments or phrase tables for training the out of box models from catalog.py. All I could manage to find was a small section on 'Alignments' in this page - http://opennmt.net/OpenNMT-tf/data.html 
I'm really new to this, so here are couple of questions I have - 

1) What's the best way to start using/generating alignments and/or phrase tables. ?

2) I have a collection of domain specific phrases both in source and target language that I want the model to use while training, how do I add them to the training ? 

Any guidance is appreciated. @guillaumekln 
I posted this in OpenNMT Forum too, if it helps. http://forum.opennmt.net/t/opennmt-tf-how-to-use-alignments-and-phares-tables/2209

Thanks !

Mohammed Ayub

**Comment by guillaumekln** [comment]
Hi,

Thanks for posting on the forum. Let's move the discussion there as it does not highlight a bug specifically.
