### ISSUE TITLE
 problem with the size of vocabulary

### ISSUE THREAD

**Issue by wingsyuan** [OpenNMT/OpenNMT-tf#257]
Hi,

@guillaumekln

when i run onmt-main train_and_eval --model_type Transformer --config data.yml --auto_config --session_config gpuconfig --num_gpus 2

if  the size of vocabulary  were over 60000, if 650000,errors occurs , What should i do if I want to set  bigger vocabulary?

***************************************____
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: Ran out of GPU memory when allocating 956701080 bytes for 
	 [[Node: transformer/parallel_0/transformer/softmax_cross_entropy_with_logits = SoftmaxCrossEntropyWithLogits[T=DT_FLOAT, _class=["loc:@optim...s_grad/mul"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](transformer/parallel_0/transformer/softmax_cross_entropy_with_logits/Reshape, transformer/parallel_0/transformer/softmax_cross_entropy_with_logits/Reshape_1)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[Node: optim/gradients/AddN_grad/tuple/ArithmeticOptimizer/ArithmeticOptimizer/ArithmeticOptimizer/RemoveIdempotent_RemoveIdempotent_RemoveIdempotent_control_dependency/_4959 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:1", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_12839...dependency", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:1"]()]]

Thanks very much!

**Comment by guillaumekln** [comment]
Hi,

> What should i do if I want to set bigger vocabulary?

One solution is to buy a GPU with a larger memory. Otherwise, you should unfortunately set a smaller vocabulary size so that it can fit in your GPU memory.

**Comment by wingsyuan** [comment]
ok,thanks
