### ISSUE TITLE
Question about functions in Decoder class

### ISSUE THREAD

**Issue by atebbifakhr** [OpenNMT/OpenNMT-tf#265]
Hi,

Could you please give me a description about the functions you have added to the Decoder class? I mean decode_from_inputs, greedy_decode, and step_fn.

I'm trying to use Reinforcement Learning techniques during the training, and I need to use model's prediction during training instead of choosing words from the reference translation. Is there any possibility to use these functions?

Cheers

**Comment by guillaumekln** [comment]
Hi,

* `Decoder.step_fn` is the lowest level API available, it returns a callable and an initial state to run the decoder step by step, for example:

```python
step_fn, state = decoder.step_fn(...)
step = tf.constant(0)

# Run 1 step in training mode:
inputs = tf.nn.embedding_lookup(ids)
outputs, state = step_fn(step, inputs, state, tf.estimator.ModeKeys.TRAIN)
logits = tf.layers.dense(outputs, vocab_size)
```

This is typically wrapped in a `tf.while_loop` for dynamic decoding. This could be of interest for you.

* `Decoder.decode_from_inputs` forwards the full reference translation into the decoder. This is typically used during the training and can be implemented in terms of calling the step function several times (some decoders don't do that for clear performance reason, e.g. self attention can execute everything at once).

* `greedy_decode` is not a new function and simply generates a sequence using the argmax at each step.

Does that make sense? I'm still in the process of improving the decoder API. Ideally, a custom decoder could minimally implement `step_fn` and all decoding logics are implemented in the base decoder class.

**Comment by atebbifakhr** [comment]
Thanks for the detailed description, the API is improved too much from my last check!
