### ISSUE TITLE
Parellel Encoder 

### ISSUE THREAD

**Issue by claudiusalp** [OpenNMT/OpenNMT-tf#266]
I tried multi_source_nmt.py  with SequnenceRecordInputter, but in eval mode it gives me an error. ValueError: Trying to share variable seq2seq/decoder/dense/kernel, but specified shape (512, 2892) and found shape (4096, 4096). I want to encode two different sources separately, than concat them and make transformation for 2048 to 512 for decoder initial.

**Comment by guillaumekln** [comment]
Can you post the full model configuration you used?

**Comment by claudiusalp** [comment]
`import tensorflow as tf
import opennmt as onmt

def model():
  return onmt.models.SequenceToSequence(
      source_inputter=onmt.inputters.ParallelInputter([
          onmt.inputters.SequenceRecordInputter(),
          onmt.inputters.SequenceRecordInputter()]),
      target_inputter=onmt.inputters.WordEmbedder(
          vocabulary_file_key="target_words_vocabulary",
          embedding_size=512),
      encoder=onmt.encoders.ParallelEncoder([
          onmt.encoders.BidirectionalRNNEncoder(
              num_layers=2,
              num_units=512,
              reducer=onmt.layers.ConcatReducer(),
              cell_class=tf.contrib.rnn.LSTMCell,
              dropout=0.3,
              residual_connections=False),
          onmt.encoders.BidirectionalRNNEncoder(
              num_layers=2,
              num_units=512,
              reducer=onmt.layers.ConcatReducer(),
              cell_class=tf.contrib.rnn.LSTMCell,
              dropout=0.3,
              residual_connections=False)],
          outputs_reducer=onmt.layers.ConcatReducer()),
      decoder=onmt.decoders.AttentionalRNNDecoder(
          num_layers=4,
          num_units=512,
          bridge=onmt.layers.DenseBridge(),
          attention_mechanism_class=tf.contrib.seq2seq.LuongAttention,
          cell_class=tf.contrib.rnn.LSTMCell,
          dropout=0.3,
residual_connections=False))
`

**Comment by claudiusalp** [comment]
Thanks for quick reply.

**Comment by guillaumekln** [comment]
If you rely on the pip package, I pushed the version 1.13.1 that includes the fix.
