### ISSUE TITLE
Parellel Encoder Bridge

### ISSUE THREAD

**Issue by claudiusalp** [OpenNMT/OpenNMT-tf#270]
```python
import tensorflow as tf
import opennmt as onmt

def model():
  return onmt.models.SequenceToSequence(
      source_inputter=onmt.inputters.ParallelInputter([
          onmt.inputters.SequenceRecordInputter(),
          onmt.inputters.SequenceRecordInputter()]),
      target_inputter=onmt.inputters.WordEmbedder(
          vocabulary_file_key="target_words_vocabulary",
          embedding_size=256),
      encoder=onmt.encoders.ParallelEncoder([
          onmt.encoders.UnidirectionalRNNEncoder(
              num_layers=4,
              num_units=512,
              cell_class=tf.contrib.rnn.GRUCell,
              residual_connections=True,
              dropout=0.3),
          onmt.encoders.UnidirectionalRNNEncoder(
              num_layers=4,
              num_units=512,
              residual_connections=True,
              cell_class=tf.contrib.rnn.GRUCell,
              dropout=0.3)],
          outputs_reducer=onmt.layers.ConcatReducer(axis=2)),
      decoder=onmt.decoders.AttentionalRNNDecoder(
          num_layers=4,
          num_units=1024,
          bridge=onmt.layers.CopyBridge(),
          attention_mechanism_class=tf.contrib.seq2seq.LuongAttention,
          cell_class=tf.contrib.rnn.GRUCell,
          dropout=0.3,
residual_connections=True))
```
Hi,
This is my model. I want to encode two different source and concat them for each layer. for example, encoder 1 first layer last hidden + encoder 2 first layer last hidden which is 512 + 512 = 1024 elements. Do this for each layer and feed decoder with this 4 1024 elements. This gives error as ConcatReducer makes them a tuple with 8 elements with 512 size.

 ValueError: The two structures don't have the same nested structure.

First structure: type=tuple str=(<tf.Tensor 'seq2seq/parallel_0/seq2seq/decoder_1/MultiRNNCellZeroState/DropoutWrapperZeroState/GRUCellZeroState/zeros:0' shape=(?, 1024) dtype=float32>, <tf.Tensor 'seq2seq/parallel_0/seq2seq/decoder_1/MultiRNNCellZeroState/ResidualWrapperZeroState/DropoutWrapperZeroState/GRUCellZeroState/zeros:0' shape=(?, 1024) dtype=float32>, <tf.Tensor 'seq2seq/parallel_0/seq2seq/decoder_1/MultiRNNCellZeroState/ResidualWrapperZeroState_1/DropoutWrapperZeroState/GRUCellZeroState/zeros:0' shape=(?, 1024) dtype=float32>, <tf.Tensor 'seq2seq/parallel_0/seq2seq/decoder_1/MultiRNNCellZeroState/ResidualWrapperZeroState_2/DropoutWrapperZeroState/GRUCellZeroState/zeros:0' shape=(?, 1024) dtype=float32>)

Second structure: type=tuple str=(<tf.Tensor 'seq2seq/parallel_0/seq2seq/encoder_1/encoder_0/rnn/while/Exit_3:0' shape=(?, 512) dtype=float32>, <tf.Tensor 'seq2seq/parallel_0/seq2seq/encoder_1/encoder_0/rnn/while/Exit_4:0' shape=(?, 512) dtype=float32>, <tf.Tensor 'seq2seq/parallel_0/seq2seq/encoder_1/encoder_0/rnn/while/Exit_5:0' shape=(?, 512) dtype=float32>, <tf.Tensor 'seq2seq/parallel_0/seq2seq/encoder_1/encoder_0/rnn/while/Exit_6:0' shape=(?, 512) dtype=float32>, <tf.Tensor 'seq2seq/parallel_0/seq2seq/encoder_1/encoder_1/rnn/while/Exit_3:0' shape=(?, 512) dtype=float32>, <tf.Tensor 'seq2seq/parallel_0/seq2seq/encoder_1/encoder_1/rnn/while/Exit_4:0' shape=(?, 512) dtype=float32>, <tf.Tensor 'seq2seq/parallel_0/seq2seq/encoder_1/encoder_1/rnn/while/Exit_5:0' shape=(?, 512) dtype=float32>, <tf.Tensor 'seq2seq/parallel_0/seq2seq/encoder_1/encoder_1/rnn/while/Exit_6:0' shape=(?, 512) dtype=float32>)

**Comment by claudiusalp** [comment]
Thanks for reply. I tried with ConcatReducer(axis=2) which seems appropriate. But did not work. So tried all axises and joinreducer. They do not work also. ConcatReducer concat in time or in dimension space. But I see 512 in encoder output tuples. Should ConcatReducer(axis=2) make it 512 + 512 = 1024.

**Comment by claudiusalp** [comment]
OK. I will try and inform here.

**Comment by claudiusalp** [comment]
First structure: type=tuple str=(<tf.Tensor 'seq2seq/parallel_0/seq2seq/decoder_1/MultiRNNCellZeroState/DropoutWrapperZeroState/GRUCellZeroState/zeros:0' shape=(?, 1024) dtype=float32>, <tf.Tensor 'seq2seq/parallel_0/seq2seq/decoder_1/MultiRNNCellZeroState/ResidualWrapperZeroState/DropoutWrapperZeroState/GRUCellZeroState/zeros:0' shape=(?, 1024) dtype=float32>, <tf.Tensor 'seq2seq/parallel_0/seq2seq/decoder_1/MultiRNNCellZeroState/ResidualWrapperZeroState_1/DropoutWrapperZeroState/GRUCellZeroState/zeros:0' shape=(?, 1024) dtype=float32>, <tf.Tensor 'seq2seq/parallel_0/seq2seq/decoder_1/MultiRNNCellZeroState/ResidualWrapperZeroState_2/DropoutWrapperZeroState/GRUCellZeroState/zeros:0' shape=(?, 1024) dtype=float32>)

Second structure: type=Tensor str=Tensor("seq2seq/parallel_0/seq2seq/encoder_1/concat_1:0", shape=(4, ?, 1024), dtype=float32, device=/device:GPU:0)

I tried to concat in depth, but different from outputs, it makes a tensor from them. Actually, first one is 4 element tuple, second is 4 element tensor. But there is a type problem. Sorry for forgetting states, but why they are merged differently. Outputs are taken into tuple but states are taken into tensor. Another option, first error is coming from states so I cannot see the outputs error so I assume outputs are merged as I want.

**Comment by guillaumekln** [comment]
It should be:

```python
states_reducer=onmt.layers.ConcatReducer(axis=-1)
```

to concat in depth.

**Comment by claudiusalp** [comment]
outputs_reducer=onmt.layers.ConcatReducer(axis=2),
          states_reducer= onmt.layers.ConcatReducer(axis=-1))`
`

**Comment by guillaumekln** [comment]
Indeed, it does not work correctly with reducers different than `JoinReducer`. I will look to push a fix.

In the meantime, as your model definition is Python code you could define your own states reduction logic by creating a class inheriting from [`Reducer`](http://opennmt.net/OpenNMT-tf/package/opennmt.layers.reducer.html#opennmt.layers.reducer.Reducer).

**Comment by guillaumekln** [comment]
Actually we can't easily define the concat semantic for the states in case of multi encoders. There are no guarantees that all encoders produce the same state structure which is a requirement for the concat reducer.

In your case, you should either use a `DenseBridge` or define your own reducer as proposed above.
