### ISSUE TITLE
Tokenizing data based on fastText tokenization 

### ISSUE THREAD

**Issue by MukundKhandelwal** [OpenNMT/OpenNMT-tf#280]
Hi,

I wanted to know if there is any way I could tokenize my data files using **similar tokenizing methods** that are used in fastText embeddings for English and Spanish. This will help in the effective lookup between training data and embeddings. 

Link: 
[https://fasttext.cc/docs/en/crawl-vectors.html](url)

Thanks for all the help.

**Comment by guillaumekln** [comment]
Hi,

Just use whatever tokenization tool that fastText is using. By default, OpenNMT-tf expects space-separated tokens which is what most tools would generate.

**Comment by MukundKhandelwal** [comment]
Alright. Thank you.
