### ISSUE TITLE
Sharing parameter of encoder-decoder layers 

### ISSUE THREAD

**Issue by surafelml** [OpenNMT/OpenNMT-tf#287]
Hi, 

I see sharing encoder-decoder embedding is already implemented (share_embeddings). 

There are also interesting papers that aim to share encoder and decoder parameters. For instance, this recent [paper](http://papers.nips.cc/paper/8019-layer-wise-coordination-between-encoder-and-decoder-for-neural-machine-translation.pdf):
 
- "coordinates the learning of hidden representations of the encoder and decoder together layer by layer"
- "share the parameters of each layer between the encoder and decoder " 

Could this be a short-term plan to include it in OpenNMT-tf ?  Any guidance on how to proceed with the implementation would also be appreciated! 

Thanks a lot!
P.S.: #272  supports sharing parameters between parallel encoders. I think this creates some intuition for sharing params between encoder and decoder.

**Comment by guillaumekln** [comment]
Hi,

> P.S.: #272 supports sharing parameters between parallel encoders. I think this creates some intuition for sharing params between encoder and decoder.

Yes it should be similar.

In addition, if you set `reuse=tf.AUTO_REUSE` in the variable scope, it should reuse all existing variables while still creating new ones for decoder-specific parameters. If you are trying this, let me know if it works, we could add it in the main codebase.

**Comment by surafelml** [comment]
Thanks! for the tip. I will let you know as soon as possible about the progress.
