### ISSUE TITLE
Convolutional sequence to sequence

### ISSUE THREAD

**Issue by guillaumekln** [OpenNMT/OpenNMT-tf#3]
Add a new encoder-decoder model to implement "Convolutional Sequence to Sequence Learning" (https://arxiv.org/abs/1705.03122).

**Comment by guillaumekln** [comment]
Yes it does. You can provide a model configuration that looks like this:

```python
import tensorflow as tf
import opennmt as onmt

def model():
  return onmt.models.SequenceToSequence(
      source_inputter=onmt.inputters.WordEmbedder(
          vocabulary_file_key="source_words_vocabulary",
          embedding_size=512),
      target_inputter=onmt.inputters.WordEmbedder(
          vocabulary_file_key="target_words_vocabulary",
          embedding_size=512),
      encoder=onmt.encoders.ConvEncoder(
          num_layers=4,
          num_units=1024,
          kernel_size=3,
          dropout=0.3,
          position_encoder=onmt.layers.PositionEmbedder(maximum_position=128)),
      decoder=onmt.decoders.AttentionalRNNDecoder(
          num_layers=4,
          num_units=1024,
          bridge=onmt.layers.DenseBridge(),
          attention_mechanism_class=tf.contrib.seq2seq.LuongAttention,
          cell_class=tf.contrib.rnn.LSTMCell,
          dropout=0.3,
          residual_connections=False))
```

See the [documentation](http://opennmt.net/OpenNMT-tf/package/opennmt.html) for more information about each building blocks.

**Comment by abhishekvermasg** [comment]
but does it support the original implementation of paper because i don't see a convolutional decoder in the api and that should be there.

**Comment by guillaumekln** [comment]
No, the original implementation is not supported (that's why this issue is still open). However, this will probably not happen as I don't see good reasons to not use a Transformer model instead.
