### ISSUE TITLE
Compiling OpenNMT-tf for ppc64le

### ISSUE THREAD

**Issue by ticlazau** [OpenNMT/OpenNMT-tf#302]
Hello, 

I will like to compile OpenNMT-tf for IBM AC922 running on RedHat Linux 7.5. However, I don't find any instructions on how I can compile this from the ground. 
Can anyone point me to the documentation?

Thx,
T

**Comment by guillaumekln** [comment]
Hi,

OpenNMT-tf is pure Python code, so I guess you are looking to compile TensorFlow on this architecture? If so, you should go to the TensorFlow support page instead.

A quick search on Google gives this result:

https://hub.docker.com/r/ibmcom/tensorflow-ppc64le/tags

**Comment by ticlazau** [comment]
Hi,
TF is already installed. However, I have a problem with  pyonmttok failing installing with this error:

Python.cc:5:28: fatal error: onmt/Tokenizer.h: No such file or directory
     #include <onmt/Tokenizer.h>
                                ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/home/coredump/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-t_5qiso_/pyonmttok/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-g6gvzrnl/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-t_5qiso_/pyonmttok/

:(

**Comment by guillaumekln** [comment]
The `pyonmttok` package is only built for Linux. However, this package is optional and OpenNMT-tf can run without it.

**Comment by ticlazau** [comment]
I am on RedHat Linux and when pip install OpenNMT-tf this is a prereq.

**Comment by guillaumekln** [comment]
Sorry, I meant Linux x86_64. Could you try to install OpenNMT-tf without dependencies and manually install the dependencies expect pyonmttok?

**Comment by Dagamies** [comment]
I managed to get it to work on ppc64le. If I recall correctly I first had to compile Tokenizer library and install it. Then it required some changes to setup.py as follows:
(I just hard coded paths to get it to work on my installation)
```
~/tf/Tokenizer/bindings/python$ diff setup.py setup.py.bak 
7,8c7,8
< include_dirs = ["/home/ari/tf/Tokenizer/include","/home/ari/tf/Tokenizer/build","/home/ari/tf/sentencepiece/src"]
< library_dirs = ["/usr/lib/powerpc64le-linux-gnu","/home/ari/tf/Tokenizer/build"]
---
> include_dirs = []
> library_dirs = []
32,39c32,34
<               os.getenv("BOOST_PYTHON_LIBRARY",
<                   "boost_python-py35"),
<               "OpenNMTTokenizer"])
< 
<     #libraries=[
<     #    os.getenv("BOOST_PYTHON_LIBRARY",
<     #              "boost_python-py%d%d" % (sys.version_info[0], sys.version_info[1])),
<     #    "OpenNMTTokenizer"])
---
>         os.getenv("BOOST_PYTHON_LIBRARY",
>                   "boost_python%d%d" % (sys.version_info[0], sys.version_info[1])),
>         "OpenNMTTokenizer"])

```
This worked on ppc64le in Ubuntu 16.04....

**Comment by ticlazau** [comment]
Thx @Dagamies I will give a try on my RHEL.
Can you tell me what Cmake version have you used?

**Comment by guillaumekln** [comment]
Looks like this has been resolved.
