### ISSUE TITLE
Question about using conv1d instead dense layer.

### ISSUE THREAD

**Issue by Sanghyuk-Choi** [OpenNMT/OpenNMT-tf#305]
https://github.com/OpenNMT/OpenNMT-tf/blob/da89eb2a74fb45ac375de212c93069458ccfc63c/opennmt/layers/transformer.py#L310

In my experiment,
`tf.layers.conv1d` speed(build time) is slower than `tf.layers.dense` about 3times 
and uses slightly more memory while backpropagate.

(GPU=1080ti, cuda9.2, cudnn=7.2.1,
tensorflow version=12.0)

I think if kernel size=1, the results are the same.
is there any reason such as performance to use conv1d instead dense?

Thank you.
Sanghyuk Choi.

**Comment by guillaumekln** [comment]
Thanks for the question.

According to my experiment, at runtime it is slightly faster than `dense` layers after disabling [TensorFlow's layout optimizer](https://github.com/OpenNMT/OpenNMT-tf/blob/v1.17.1/opennmt/runner.py#L99-L113).

However, I do plan to replace conv1d by dense layers in a future version as it is clearer and less prone to be incorrectly optimized by the TensorFlow backend.

**Comment by Sanghyuk-Choi** [comment]
Thank you for the kind answer.
