### ISSUE TITLE
Make vocabulary for numerical features

### ISSUE THREAD

**Issue by Aha6988** [OpenNMT/OpenNMT-tf#306]
Hi, 
I have some numerical features in my sequence labeling task, for example the probability of getting a special label for each word. 
But I don’t know how to make vocabularies for these fearures. Actually, I think it is not meaningful to build vocabulary for such a feature which can get any real number. 
I really appreciate any help.

**Comment by guillaumekln** [comment]
Hi,

Can you give an example of what it looks like?

**Comment by Aha6988** [comment]
We want to tag every words of the sentences of the test data with one of our two labels (as an example A and B) by considering the word and its features. One of our features is p(A|pos) that pos is the part of speech of the word. We compute these probabilities based on our training data. So, this feature has real values between 0 and 1.
Thanks

**Comment by guillaumekln** [comment]
Do you need to transform these probabilities in some way? Currently it is possible to pass:

* A sequence of vectors: http://opennmt.net/OpenNMT-tf/package/opennmt.inputters.record_inputter.html#opennmt.inputters.record_inputter.SequenceRecordInputter
* A parallel input feature: http://opennmt.net/OpenNMT-tf/package/opennmt.inputters.inputter.html#opennmt.inputters.inputter.ParallelInputter

So in some way, you could pass this feature without changing the code, at the cost of some data preparation and configuration.

**Comment by Aha6988** [comment]
I have to try it
  
  
Thank you
  
  

  
  

  
  
>
