### ISSUE TITLE
prediction output makes no sense at all

### ISSUE THREAD

**Issue by AyaNsar** [OpenNMT/OpenNMT-tf#307]
So I tried training with both the py and tf versions of the openNMT. the py version had a very clear reasonable output, however, with tf, it was all a bunch of words with very long sentences. The input files for training were source and validation text files of sentences separated by new line, both for source and target. For the infer process, I used a test-file also consisted of sentences in the same format. What am I missing here? 
I also assumed that 1 epoch = number of sentences/batch size. Is that correct?

**Comment by guillaumekln** [comment]
> I also assumed that 1 epoch = number of sentences/batch size. Is that correct?

It depends if you configured the batch as a number of tokens or sentences.

What is your configuration and training command line?

**Comment by AyaNsar** [comment]
data.yml:
train:
  batch_size: 64
  batch_type: examples
  save_checkpoints_steps: 1000
  keep_checkpoint_max: 30
  train_steps: 22000
  single_pass: false
infer:
  batch_size: 64
  with_score: true

and the command:
   onmt-main train_and_eval --model_type NMTSmall --auto_config --config data.yml

**Comment by guillaumekln** [comment]
22000 training steps is not a lot. How does the evaluation loss look like?

**Comment by AyaNsar** [comment]
That I can't tell because I don't have the output now of evaluation now. Plus, the evaluation process was a little bit troublesome because It would stop training every time it saves a checkpoint, giving this error:
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence [[Node: IteratorGetNext = IteratorGetNext[output_shapes=[[?,?], [?], [?,?], [?,?], [?,?], [?], [?,?]], output_types=[DT_INT64, DT_INT32, DT_STRING, DT_INT64, DT_INT64, DT_INT32, DT_STRING], _device="/job:localhost/replica:0/task:0/device:CPU:0"](Iterator)]].
OSError: [WinError 193] %1 is not a valid Win32 application "opennmt"

so i had to disable this option since it was not very crucial to me at the moment. 

22000 would make the number of epochs that I need for my analysis, if my assumption about how to calculate 1 epoch is correct.

**Comment by AyaNsar** [comment]
The sentences that I have contain not only words, but mathematical symbols and numbers, would that affect the results?

**Comment by guillaumekln** [comment]
If these symbols are included in the vocabulary that is not an issue.

Did you run TensorBoard to monitor the training? You should have more information on the training loss and gradient norm to better debug this.

**Comment by AyaNsar** [comment]
Okay, I will retrain again and see how it goes.

**Comment by guillaumekln** [comment]
Closing. Feel free to reopen if you think your problem has not been solved.
