### ISSUE TITLE
Can we extract sentence level BLEU scores ?

### ISSUE THREAD

**Issue by mohammedayub44** [OpenNMT/OpenNMT-tf#313]
Hi @guillaumekln 

We want to do some custom evaluation of predicted sentences from our NMT models and was wondering are there routines in OpenNMT to get sentence level BLEU scores in the output ? 
Otherwise, Can i run it through NLTK or something similar ?

Thanks !

- Mohammed Ayub

**Comment by guillaumekln** [comment]
Hi,

Take a look at [sacreBLEU](https://github.com/mjpost/sacreBLEU).

https://github.com/mjpost/sacreBLEU/blob/v1.2.12/sacrebleu.py#L999

**Comment by mohammedayub44** [comment]
Thanks. Let me take a look at this.

**Comment by mohammedayub44** [comment]
`import sacrebleu`
`print(sacrebleu.sentence_bleu(hyp, ref))`

Solves it.
