### ISSUE TITLE
How to use SeqTagger model

### ISSUE THREAD

**Issue by ashleycheng** [OpenNMT/OpenNMT-tf#337]
Hello,

I am using `SeqTagger` model to perform a POS tagging task. But I am not sure in words vocabulary and chars vocabulary these two files which are required for training. Is there any running example for generating those files? Also, for training word embeddings, should I add pos tag to its training data ?

Thanks

**Comment by guillaumekln** [comment]
Hi,

You can use the `onmt-build-vocab` to generate vocabulary files. See the [relevant section](http://opennmt.net/OpenNMT-tf/data.html#vocabulary) in the documentation. For the character based vocabulary, you should pass the option `--tokenizer CharacterTokenizer` to the script.

Word embeddings should be trained on the training text file directly (no POS). Pretrained embeddings help but they are not mandatory. You can create a [custom model definition](http://opennmt.net/OpenNMT-tf/configuration.html#usage) to not use them:

```python
import tensorflow as tf
import opennmt as onmt

def model():
  return onmt.models.SequenceTagger(
        inputter=onmt.inputters.MixedInputter([
            onmt.inputters.WordEmbedder(
                vocabulary_file_key="words_vocabulary",
                embedding_size=100),
            onmt.inputters.CharConvEmbedder(
                vocabulary_file_key="chars_vocabulary",
                embedding_size=30,
                num_outputs=30,
                kernel_size=3,
                stride=1,
                dropout=0.5)],
            dropout=0.5),
        encoder=onmt.encoders.BidirectionalRNNEncoder(
            num_layers=1,
            num_units=400,
            reducer=onmt.layers.ConcatReducer(),
            cell_class=tf.nn.rnn_cell.LSTMCell,
            dropout=0.5,
            residual_connections=False),
        labels_vocabulary_file_key="tags_vocabulary",
        crf_decoding=True)
```

**Comment by ashley-cheng** [comment]
I can successfully perform training now. Thanks!

**Comment by ashleycheng** [comment]
I can successfully perform training now. Thanks!
