### ISSUE TITLE
Link to documentation is hidden

### ISSUE THREAD

**Issue by gsoul** [OpenNMT/OpenNMT-tf#34]
At http://opennmt.net/ you can't scroll down the left menu block, and the links to Tensorflow version of OpenNMT do not appear on the screen.

**Comment by guillaumekln** [comment]
Thanks. This has been fixed in the website repository:

https://github.com/OpenNMT/opennmt.github.io/commit/37cd09a6984e087363fbfcd7d74426f13e924f6d
