### ISSUE TITLE
Making changes in the source code

### ISSUE THREAD

**Issue by SimlaBurcu** [OpenNMT/OpenNMT-tf#342]
Hi,
When I change the source code (like adding `print('test')` to opennmt/bin/main.py), I cannot see the changes. I run the [code in scripts/wmt](https://github.com/OpenNMT/OpenNMT-tf/tree/master/scripts/wmt) with the model in Lazy run. After changing main.py, I run `python setup.py install install_lib install_headers install_scripts`, then [run](https://github.com/OpenNMT/OpenNMT-tf/tree/master/scripts/wmt) `./eval_wmt_ende.sh raw_data`. 
It worked once (I was able to see the changes), however I cannot make it work right now.

**Comment by guillaumekln** [comment]
Hi,

Did you install OpenNMT-tf with `pip install OpenNMT-tf`? If yes, it is the installed version that is run, not the one cloned with Git.

**Comment by SimlaBurcu** [comment]
No I installed it via git clone

**Comment by guillaumekln** [comment]
Are you running `python setup.py install` each time you change `main.py`?

**Comment by SimlaBurcu** [comment]
Yes. It worked once so I can see my old changes, but now I cannot see the new ones.

**Comment by guillaumekln** [comment]
Usually for development it's easier to directly invoke the script and not run the installation. For example, when you are at the root of the OpenNMT-tf directory, you can run:

```bash
python -m opennmt.bin.main -h
```

If you are not in the root directory, you should also set `PYTHONPATH=/path/to/OpenNMT-tf/`.

**Comment by SimlaBurcu** [comment]
Okay, but I run the inference code:
`onmt-main infer --config config/wmt_ende.yml --auto_config --checkpoint_path=$runconfig/avg --features_file data/$testset-src.$sl > data/$testset-src.hyp.$tl`
inside eval_wmt_ende.sh with `./eval_wmt_ende.sh raw_data` command.
So opennmt.bin.main will definitely run since onmt-main keyword stands for it. But why I can't see any of my changes?

**Comment by guillaumekln** [comment]
So replace `onmt-main` by `PYTHONPATH=/path/to/OpenNMT-tf python -m opennmt.bin.main` in `eval_wmt_ende.sh`.

That's more like a Python question than a OpenNMT-tf issue. You have now all information needed to run the script you modified.
