### ISSUE TITLE
Using the Ner Tagger Can I force a prediction for unknown sentences ?

### ISSUE THREAD

**Issue by lockder** [OpenNMT/OpenNMT-tf#343]
I would like if the sentence is all full of unknown words to have a predictable result(like unk), right know sometimes i have a prediction with no sense because all the words inside the sentence are unknown. Is there any solution?

**Comment by lockder** [comment]
I have been looking into the code but I'm not sure how can I know what is the "unk" tag.

i found constants.UNKNOWN_TOKEN but I believe its for sequence to sequence, may I'm wrong?

**Comment by lockder** [comment]
its done on the reverse but not in the normal vocabulary_lookup
```
  def vocabulary_lookup_reverse(self):
    """Returns a lookup table mapping index to string."""
    return tf.contrib.lookup.index_to_string_table_from_file(
        self.vocabulary_file,
        vocab_size=self.vocabulary_size - self.num_oov_buckets,
        default_value=constants.UNKNOWN_TOKEN)
```
```
  def vocabulary_lookup(self):
    """Returns a lookup table mapping string to index."""
    return tf.contrib.lookup.index_table_from_file(
        self.vocabulary_file,
        vocab_size=self.vocabulary_size - self.num_oov_buckets,
        num_oov_buckets=self.num_oov_buckets)
```

**Comment by guillaumekln** [comment]
You should probably add such examples in your training data.

1. Add a UNK token in your tag vocabulary 
2. Add sentences with words that are out of vocabulary and tag the OOV words with the UNK tag.

**Comment by lockder** [comment]
I see index_to_string_table_from_file use UNK as default_value. I guess vocabulary_lookup_reverse will not change. so its great way to do it. thank you so much!
I didn't know if I add inside my vocabulary the UNK tag will have a conflict with the default_value from the index_to_string_table_from_file
