### ISSUE TITLE
How to initiate input for serving tensorflow version SeqTagger

### ISSUE THREAD

**Issue by ashleycheng** [OpenNMT/OpenNMT-tf#347]
Hello,

I'am using TensorFlow Serving to serve saved `SeqTagger` model via RESTful API. I want to create a service that takes a sentence as request, and return a sequence of POS tags. But I’m not sure in how to specify request format for [PredictAPI](https://www.tensorflow.org/tfx/serving/api_rest#predict_api) to perform predictions.  I have used [Model Metadata API](https://www.tensorflow.org/tfx/serving/api_rest#model_metadata_api) to check the inputs of request body and there are three inputs: tokens, chars and length. Are all of these values required? Could you provide some running example for request? 

Thanks.

**Comment by guillaumekln** [comment]
Hi,

> Are all of these values required?

Yes, they are all required. In a future version, "chars" will be generated from "tokens" via a in-graph transformation but for now they are required as inputs.

> Could you provide some running example for request?

Did you try something already? With the serving documentation and the model inspection, you have actually all information needed to define the request format.

I don't remember the REST syntax exactly. Let me know if you are stuck, I will need to work it out again, just like you. You can also find a gRPC request example [here](https://github.com/OpenNMT/OpenNMT-tf/blob/master/examples/serving/ende_client.py).

**Comment by ashleycheng** [comment]
Hello,

I have been using REST syntax; however I am now stuck since I am not sure whether the data types of the three input parameters(lengths, chars, tokens) are the same as I thought.

My task is to analyze Chinese data. Here is an input example that I have tried:
`curl -d '{"inputs": {"chars":["你", "好", "嗎", "？"], "tokens":["你", "好", "嗎", "？"], "length”:4} }' -X POST http://localhost:8501/v1/models/half_plus_three:predict`

Error message:
{ "error": "slice index 1 of dimension 0 out of bounds.\n\t [[{{node seqtagger/encoder/inputter_1/strided_slice_1}} = StridedSlice[Index=DT_INT32, T=DT_INT32, _output_shapes=[[]], begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device=\"/job:localhost/replica:0/task:0/device:CPU:0\"](seqtagger/encoder/inputter_1/Shape, seqtagger/encoder/bidirectional_rnn/fw/fw/strided_slice_2/stack, seqtagger/generator/dense/Tensordot/axes, seqtagger/encoder/bidirectional_rnn/fw/fw/strided_slice_2/stack)]]" }

Do you know where the problem is?

**Comment by guillaumekln** [comment]
The metadata output tells you that "tokens" is 2D tensor, "chars" is a 3D tensor, and "length" a 1D tensor. You should adapt the dimension accordingly in your request:

`{"inputs": {"chars":[[["你"], ["好"], ["嗎"], ["？"]]], "tokens":[["你", "好", "嗎", "？"]], "length":[4]} }`

**Comment by ashley-cheng** [comment]
I just test this format and successfully receive the output from serving model. 
Thank you very much!

**Comment by ashleycheng** [comment]
I just test this format and successfully receive the output from serving model. 
Thank you very much!
