### ISSUE TITLE
Hello, How much time should the train process take as it took from me more than 10 days ( and still running) to train one corpus (About 1 million and two hundreds thousands words) ??  

### ISSUE THREAD

**Issue by M-HaDyS** [OpenNMT/OpenNMT-tf#349]

**Comment by guillaumekln** [comment]
This is very broad question that depends on the model, the training configuration, and the hardware. Please give more information.

**Comment by M-HaDyS** [comment]
The PC hardware is 8 G Ram , 2 G GPU (Nvidia) with I7 Intel processor and the training configuration is the default I didn't change anything

**Comment by guillaumekln** [comment]
There is no good answer to this but 1 week is usually the upper bound. As an example, the WMT training script takes about 4 days if I remember correctly. Good results can already be obtained in a few hours.

**Comment by M-HaDyS** [comment]
Fine, I will look again at my training configuration hoping to reach a good answer to that issue.
Thanks for your support :) :)
