### ISSUE TITLE
TensorBoard Integration - Visualizing Sentences from Transformer Model

### ISSUE THREAD

**Issue by mohammedayub44** [OpenNMT/OpenNMT-tf#352]
Hi @guillaumekln,

Maybe this is a partial TensorBoard partial OpenNMT question. 
I'm trying to visualize a Transformer model we have trained for English to Spanish. I'm trying to generate some custom visualizations (either using Embedding Projector or any other plugin) -  

Currently I have something like below from my TensorBoard:

![image](https://user-images.githubusercontent.com/7122670/53432278-3065e900-39c0-11e9-8c3e-fc4d0ea3093a.png)
 
I want to include functionality like below:

- Show source English, source Spanish and predicted Spanish sentences in the Embedding projector (or any other plugin).

- Add supervised tags (like which 'topic' the source pair sentences belongs to etc.) and that way we can visualize/filter by color etc.  This is for our team to do custom model evaluation with respect to some domain topics. 

I have seen the Google Team in this [paper](https://www.aclweb.org/anthology/Q/Q17/Q17-1024.pdf) do something similar but not sure if they made this code Open source.

From OpenNMT-tf perspective how easy/difficult is this to achieve. What changes will I have to make to your TensorBoard integration. ?

Any pointers/directions would be appreciated.

Thanks !

Mohammed Ayub

**Comment by guillaumekln** [comment]
Hi,

Is TensorBoard a requirement here? I think it should be easier to implement that externally.

For example, when running `train_and_eval` with this configuration:

```yaml
eval:
  save_eval_predictions: true
```

translations of the validation data are saved on disk which can be used to achieve 1.

For 2., you could preprocess your target sentences to begin with a domain tag, for example:

```text
__generic Hello world !
```

than you just need to filter the predictions on the first token.

**Comment by mohammedayub44** [comment]
Hi @guillaumekln 

> Is TensorBoard a requirement here? I think it should be easier to implement that externally.

You mean, after we get the translations, source and target files. Create a TSV to visualize it in python ? Could you elaborate or any helpful links. 
I was originally going for TensorBoard as its 3D viz and has other color/filter options. Not sure of any other similar tool.

> For 2., you could preprocess your target sentences to begin with a domain tag, for example:

to clarify, therefore anything with `__<tagname><space>` would then be ignored by the `train_and_eval` and be treated as a metadata field in the tensor ? where can i read more about adding such domain tags, any links would be helpful.

Mohammed Ayub

**Comment by guillaumekln** [comment]
> You mean, after we get the translations, source and target files. Create a TSV to visualize it in python ?

For example. But the point is it will be easier to build something using this approach compared to a TensorBoard integration (both will require custom development). TensorBoard mostly targets visual data, not text data.

> to clarify, therefore anything with `__<tagname><space>` would then be ignored by the `train_and_eval` and be treated as a metadata field in the tensor ? where can i read more about adding such domain tags, any links would be helpful.

Actually in case of model evaluation, you know the validation set in advance so you can statically map a line index to a domain. Then using the translation file generated in 1., you can display your data however you want.

So I suggest to rely on the validation translation and build something around it that is tailored to your needs.

**Comment by mohammedayub44** [comment]
@guillaumekln 
I guess that makes sense. Also, either way we might need to do some custom development. Thanks for your suggestions. 

Closing for now. Will post if we find a good solution.

Mohammed Ayub
