### ISSUE TITLE
Specific preparation to Arabic corpus 

### ISSUE THREAD

**Issue by M-HaDyS** [OpenNMT/OpenNMT-tf#354]
Dears,

Is the any specific preparation can I perform before start to train and translate Arabic corpus ?? 

Thanks in advance.

**Comment by guillaumekln** [comment]
You could try tokenizing your corpus with SentencePiece which is language independent. All instructions are on the GitHub page: 

https://github.com/google/sentencepiece

**Comment by mohammedayub44** [comment]
@M-HaDyS  did you happen to successfully run Arabic <-> English experiments using this Repo. I'm planning to do the same. Any suggestions you wan to shed some light on ? 

Thanks !

**Comment by Raamyy** [comment]
@mohammedayub44 Currently I also need to use openNMT to translate into arabic, did you try? :D
