### ISSUE TITLE
Crash after saving checkpoint (Check failed: work_element_count > 0)

### ISSUE THREAD

**Issue by Dobatymo** [OpenNMT/OpenNMT-tf#368]
Training will crash after saving a checkpoint

```
OpenNMT-ft 1.21.2
tensorflow 1.13.1
tensorflow-gpu  1.13.1
CUDA 10.0
Python 3.6.7 [GCC 8.2.0] on linux
Ubuntu 18.04
```

```
INFO:tensorflow:Saving checkpoints for 323 into model-tf/model.ckpt.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/metrics_impl.py:363: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
INFO:tensorflow:Starting evaluation at 2019-03-06T02:44:57Z
INFO:tensorflow:Graph was finalized.
2019-03-06 02:44:58.321242: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2019-03-06 02:44:58.321292: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-03-06 02:44:58.321300: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
2019-03-06 02:44:58.321308: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
2019-03-06 02:44:58.322089: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 30555 MB memory) -> physical GPU (device: 0, name: Tesla V100-PCIE-32GB, pci bus id: 0000:3b:00.0, compute capability: 7.0)
INFO:tensorflow:Restoring parameters from model-tf/model.ckpt-323
INFO:tensorflow:Running local_init_op.
2019-03-06 02:44:59.089043: I tensorflow/core/kernels/lookup_util.cc:376] Table trying to initialize from file vocab.txt is already initialized.
INFO:tensorflow:Done running local_init_op.
2019-03-06 02:45:04.202115: F ./tensorflow/core/util/cuda_launch_config.h:126] Check failed: work_element_count > 0 (-1902919456 vs. 0)
./tf-train.sh: line 1: 56673 Aborted                 (core dumped) onmt-main train_and_eval --model_type Transformer --auto_config --config config.linux.yml --session_config session_config.txt
```

The config file only specifies the data files and the session config only `gpu_options.allow_growth: true`.

**Comment by guillaumekln** [comment]
Is there an empty line in your evaluation data?

**Comment by Dobatymo** [comment]
I checked both training and testing data. Neither contains any empty lines or lines which only consist of whitespace.

**Comment by guillaumekln** [comment]
What is your vocabulary size?

**Comment by Dobatymo** [comment]
50000. I create the file like this. `onmt-build-vocab --size 50000 --save_vocab vocab.txt left.train right.train`

**Comment by guillaumekln** [comment]
Ok, so most likely there is something wrong on your system. Check your driver and CUDA installations first.

**Comment by Dobatymo** [comment]
I reinstalled CUDA and tensorflow. Still same problem. This might be related https://github.com/tensorflow/models/issues/6305.

**Comment by guillaumekln** [comment]
Yes, looks similar. It could be a hidden out of memory error but with your 32GB GPU memory that is likely not the case.

What is your driver version?

**Comment by Dobatymo** [comment]
My Driver Version is 418.39

**Comment by guillaumekln** [comment]
Any update on this?

**Comment by Dobatymo** [comment]
No, I still cannot get it to work. I reinstalled everything, pulled the latest versions and so on. But I have the same experience with OpenNMT-tf and OpenNMT-py.
It trains fine at first but then fails the first validation pass.
My CUDA installation seems to be fine, all the official samples compile and run without problem and various other Python tensorflow and pytorch code works as well.

**Comment by guillaumekln** [comment]
Can you try with another validation set, or a subset of the current validation set? If a similar error occurs on 2 different toolkits with very different internals, it's either a data issue or a system issue.

**Comment by Dobatymo** [comment]
I regenerated the datasets and now it works. Not sure what the problem was. I did some superficial validation of the training and tests sets before (tokenization, empty lines and so on) but I didn't find any problems except for some lines with lots of tokens.

Could that be a problem? Having a few lines with a 1000 tokens when the average is more like 10-20?
In any case, it would be great to have a better error message to figure out where the problem is.

Thanks for your help!

**Comment by guillaumekln** [comment]
So it was likely an out of memory issue. The validation set is not filtered and long sentences can make the memory usage to explode.

> In any case, it would be great to have a better error message to figure out where the problem is.

For this particular exit condition, we have no way to catch it within OpenNMT-tf. It's on TensorFlow to raise a proper Python exception for this error case.

**Comment by eduamf** [comment]
Same error following the first steps to use OpenNMT-tf in http://opennmt.net/OpenNMT-tf/quickstart.html :
# python 3.6

```
pip install --upgrade pip
pip install OpenNMT-tf
```
....
```
wget https://s3.amazonaws.com/opennmt-trainingdata/toy-ende.tar.gz
tar xf toy-ende.tar.gz
cd toy-ende
```
....
```
onmt-build-vocab --size 50000 --save_vocab src-vocab.txt src-train.txt
onmt-build-vocab --size 50000 --save_vocab tgt-vocab.txt tgt-train.txt
....

Message in both cases:
"illegal instruction (core dumped)"
No more information.

**Comment by guillaumekln** [comment]
How is it the same error? Illegal instruction usually happens when you run a binary using an instruction set that your CPU does not support (e.g. AVX).
