### ISSUE TITLE
How to output the the initial hidden state in the decoding layer

### ISSUE THREAD

**Issue by wingsyuan** [OpenNMT/OpenNMT-tf#370]
as title...
Hi, when I try to translate the src sentence using the pre-trained transformer model with opennmt decoder, and I want to output the initial hidden state of the tgt sentence in the decoding layer, How to do it , where to modify the code?
Thanks very much..

**Comment by guillaumekln** [comment]
Hi,

Hidden state is a RNN terminology. Are you looking to get the decoder output of the first timestep?

**Comment by wingsyuan** [comment]
Hi, @guillaumekln 
yes , Can you tell me how to get the decoder output of the first timestep? thanks a lot!

**Comment by guillaumekln** [comment]
I'm not sure what sentence embedding you are looking for (this is typically ask for source sentences, not target). Can you specifically tell which layer output you are interested in? Do you have any paper for reference?

**Comment by wingsyuan** [comment]
Hi,@guillaumekln
Thanks for your kindly help, I will contact you by email later.
