### ISSUE TITLE
Training stopped (hung)

### ISSUE THREAD

**Issue by Dagamies** [OpenNMT/OpenNMT-tf#376]
An interesting thing happened last night; about 1:00 AM training got stuck after 42000 iterations. GPU reports 0% load and GPU memory is still used by python process. Python process is still using CPU. This training instance is on TF 1.13.1 (built from sources) and using OpenNMT-tf 1.12.3.

Is there any way to troubleshoot this or should I just kill the instance and continue from the checkpoint and write this off as rare anomality?

**Comment by guillaumekln** [comment]
Difficult to tell, this could be a temporary system issue. Did you end up killing the process?

**Comment by Dagamies** [comment]
It is still stuck, but I think I will kill it now and write this off as Tensorflow related isssue
