### ISSUE TITLE
How to use conditional GPT-2 when inference?

### ISSUE THREAD

**Issue by BigFishMaster** [OpenNMT/OpenNMT-tf#384]
The original paper shows that one can use conditions to product related sequence.  Can you support this implement?

**Comment by guillaumekln** [comment]
You should run the `infer` command and pass a file containing the conditional sequences to `--features_file`, e.g.:

```bash
onmt-main infer --model config/models/gpt_2.py --config data.yml --auto_config --features_file conditional.txt
```

where `conditional.txt` has the same format of the training file.

By default, it decodes using the argmax but it is also possible to sample from the output distribution:

http://opennmt.net/OpenNMT-tf/inference.html#sampling

Let me know how it goes.

**Comment by lqniunjunlper** [comment]
Where can i find the gpt_2.py file?

**Comment by guillaumekln** [comment]
The model is now defined in the library itself (see [here](https://github.com/OpenNMT/OpenNMT-tf/blob/v2.12.1/opennmt/models/catalog.py#L318-L355)).

It can be used by setting `--model_type GPT2Small` on the command line.

**Comment by lqniunjunlper** [comment]
@guillaumekln Thanks a lot!
