### ISSUE TITLE
OpenNMT-tf Transformer model, usage of pre-trained embeddings

### ISSUE THREAD

**Issue by krushika29** [OpenNMT/OpenNMT-tf#385]
Hello, I a am beginner in using OpenNMT-tf, and I am trying to build a model which translates text from English to Spanish.
I am trying to use pre-trained embeddings (like GloVe, fastText) in the Transformer model.
Here is my config file 

```model_dir: run/

data:
  train_features_file: /home/ubuntu/ktapedia/nfpa_models/Word_Embeddings/tokenized_train.en
  train_labels_file: /home/ubuntu/ktapedia/nfpa_models/Word_Embeddings/tokenized_train.es
  eval_features_file: /home/ubuntu/ktapedia/nfpa_models/Word_Embeddings/tokenized_eval.en
  eval_labels_file: /home/ubuntu/ktapedia/nfpa_models/Word_Embeddings/tokenized_eval.es
  source_words_vocabulary: /home/ubuntu/ktapedia/nfpa_models/Word_Embeddings/src-vocab.txt
  target_words_vocabulary: /home/ubuntu/ktapedia/nfpa_models/Word_Embeddings/tgt-vocab.txt
  source_embedding:
    path: /home/ubuntu/ktapedia/glove.6B/glove.6B.300d.txt
    with_header: True
    case_insensitive: True
    trainable: False

train:
  save_checkpoints_steps: 1000
  train_steps: 5000
  
eval:
  eval_delay: 300
  external_evaluators: [BLEU]
  exporters: last

infer:
  batch_size: 16
```

On the OpenNMT-tf documentation, I can find an option only for providing the source embeddings in the config file, and nothing related to the target word embeddings.
Also, I referred to a similar issue on embeddings and referred the code for Transformer model, which uses both source and target word embeddings.
Here, is the reference for it.

**Transformer Model Source Code :-**
[http://opennmt.net/OpenNMT-tf/_modules/opennmt/models/catalog.html#Transformer](url)

If there is no parameter for target embeddings in the configuration, then by default what value does the model take for target embeddings.

The following are my questions related to usage of pre-trained embeddings:

1. Do we need both source and target word embeddings?
2. If the answer to the above question is yes, then why do we need the target word embeddings?
3. And also, how to provide the target word embeddings?

Thanks in advance !!

**Comment by guillaumekln** [comment]
Hi,

1. Do we need both source and target word embeddings?

You can set pretrained embeddings for the source, the target, both or neither, so the answer is no. When you don't configure pretrained embeddings, they are randomly initialized.

3. And also, how to provide the target word embeddings?

You can define `target_embedding` the same way you defined `source_embedding`.

**If you are using version 1.21, make sure to update to the latest patch (1.21.6) as a bug was fixed regarding this feature.**

**Comment by krushika29** [comment]
Thanks for your quick reply, that means I have to provide the '''target_embedding''' in the config file, and make no changes in the code ?

Is that correct, please correct me if I am wrong.

**Comment by guillaumekln** [comment]
Yes, that is correct.

**Comment by krushika29** [comment]
Thanks a lot !!
