### ISSUE TITLE
Is there anythin in ONMT for text classification

### ISSUE THREAD

**Issue by mohammedayub44** [OpenNMT/OpenNMT-tf#388]
Hi
I have millions of sentences from two data sets belonging to different domains (for eg. sports and health). Is there an out of box NN model that I can train for a text classifier for these sentences from two domains. 

If yes, how Can I expand that to multiple domains as well. ?

Any help appreciated. 

Thanks !
Mohammed Ayub

**Comment by guillaumekln** [comment]
Hi,

This capability is implemented but you need to define a model architecture by yourself. Here are the relevant sections in the documentation:

* Custom model: http://opennmt.net/OpenNMT-tf/model.html#custom-models
* Sequence classifier model: http://opennmt.net/OpenNMT-tf/package/opennmt.models.sequence_classifier.html

Maybe there are ready-to-use text classifiers out there but if you want to use OpenNMT, these 2 links should get you started.

**Comment by mohammedayub44** [comment]
Thanks @guillaumekln 
I see. Let me check these links out and get back. Closing this for now. Once I try and run into issues will reopened again
