### ISSUE TITLE
Questions about the order of learning BPE and Tokenization

### ISSUE THREAD

**Issue by ruyyi0323** [OpenNMT/OpenNMT-tf#389]
Hi, I am trying to implement learning and apply BPE in the dataset, but I am confused about which process to go first between learning BPE and tokenization since I've found ``bpe_model``parameter inside the tokenzation configuration. If the process should be one of these or something else:

1. original data -> learn_bpe -> apply_bpe -> tokenzation -> build-vocab ...
2. original data -> tokenzation -> learn_bpe -> apply_bpe -> build-vocab ...

**Comment by guillaumekln** [comment]
Hi,

There are 2 steps:

1. Original data -> tokenization -> learn_bpe
2. Original data -> tokenization -> apply_bpe -> build-vocab

If you are unsure about this process, you should try [SentencePiece](https://github.com/google/sentencepiece) that makes this easier and less error-prone:

1. Original data -> spm_train
2. Original data -> spm_encode -> build-vocab

**Comment by ruyyi0323** [comment]
Thanks for the helping, I totally got the process now. And if you mind giving an intuitive example for why BPE will help in machine translation?

**Comment by guillaumekln** [comment]
Subword encoding is a way reduce the vocabulary size while covering a large domain of words, including unseen words.
