### ISSUE TITLE
How to measure the performance of GPT-2?

### ISSUE THREAD

**Issue by BigFishMaster** [OpenNMT/OpenNMT-tf#390]
I trained a GPT-2 model and the following is the loss curve(orange-train and blue-valid). Cloud you tell me how to measure whether  it is well trained or not ？My problem is that GPT-2 is a pure decoder and  the tokens in the front of the input sentence have more uncertainty than the tokens at the tail while training. Because tokens from the tail have more context than the tokens from the head. Thus the loss below makes me confuse
![image](https://user-images.githubusercontent.com/4915869/54523312-2ffeb380-49aa-11e9-9c40-e38bdb070589.png)

**Comment by guillaumekln** [comment]
What task are you trying to achieve? Is it sentence scoring, text generation?

**Comment by BigFishMaster** [comment]
@guillaumekln text generation

**Comment by guillaumekln** [comment]
Did you try some generation already? How do they look?
