### ISSUE TITLE
How to run inference by using exported model ?

### ISSUE THREAD

**Issue by ljch2018** [OpenNMT/OpenNMT-tf#392]
Thank you!

**Comment by guillaumekln** [comment]
Are you looking to start an inference server or just run the model directly?

**Comment by ljch2018** [comment]
@guillaumekln  just run the model directly, such as 
```
onmt-main infer \
    --config config/my_config.yml \
    --features_file newstest2014.en.tok \
    --predictions_file newstest2014.en.tok.out \
    --checkpoint_path run/baseline-enfr/avg/model.ckpt-200000
```
But when I setup the checkpoint path like ``` --checkpoint_path model/export/latest/1552964695/```, it wont work.

**Comment by guillaumekln** [comment]
As the option name suggests, it loads a checkpoint, not an exported model. The primary use of exported models is to run them outside of OpenNMT-tf.

Currently, you can either run it via [TensorFlow Serving](https://github.com/OpenNMT/OpenNMT-tf/tree/master/examples/serving) or learn how to load and run a [SavedModel](https://www.tensorflow.org/guide/saved_model#build_and_load_a_savedmodel) from the code.

**Comment by ljch2018** [comment]
@guillaumekln Thanks.
