### ISSUE TITLE
Questions about implementing BPE (Cont'd from issue #389)

### ISSUE THREAD

**Issue by ruyyi0323** [OpenNMT/OpenNMT-tf#395]
Hi,

In the previous issue, I have acknowledged that there are two steps if I need to learn and use BPE. There are 2 steps:

Original data -> tokenization -> learn_bpe
Original data -> tokenization -> apply_bpe -> build-vocab

Here are some few questions about it,

1. If I am not wrong, a BPE vocabulary and BPE model file should be passed into the second step tokenization?

2. What is the output should be when after tokenized with BPE and after applied BPE is done, respectively. I saw some output like this example
```
Original:
This is an apple

after tokenized with BPE:
T h i s  i s  a n  a p p l e

apply BPE:
T h i s i s a n a p p l e
```
  And some of the words still (not teared apart)

  is this output normal?
  in the tokenize config I passed `mode:None` and the `bpe_model` and `bpe_vocabulary` in it

3. If there is any suggestion to select the parameters of learning BPE? what it would impact? 

4. Should I use the applied bpe data file to continue the training and eval process or files in other processing step?

**Comment by ruyyi0323** [comment]
#389

**Comment by guillaumekln** [comment]
Hi,

Can you ask such questions on the [forum](http://forum.opennmt.net/) instead? These are general questions not related to OpenNMT-tf specifically. Thanks.
