### ISSUE TITLE
How to solve Catastrophic Forgetting after Domain Adaption (English-Spanish)

### ISSUE THREAD

**Issue by mohammedayub44** [OpenNMT/OpenNMT-tf#396]
Hi,

After creating a good Engligh - Spanish model using this repo I'm running into something called as "Catastrophic Forgetting" and need some help on how to solve this. Open to any simple or complex ideas possible.

I have posted this in the forum as well  [2567](http://forum.opennmt.net/t/catastrophic-forgetting-after-domain-adaption-ideas-to-solve/2567). We can carry forward this discussion here or on the forum. 

Thanks !

Mohammed Ayub

**Comment by guillaumekln** [comment]
Let's continue on the forum:

http://forum.opennmt.net/t/catastrophic-forgetting-after-domain-adaption-ideas-to-solve/2567
