### ISSUE TITLE
Two-Directional Model and Multi-Language Support

### ISSUE THREAD

**Issue by mohammedayub44** [OpenNMT/OpenNMT-tf#397]
Hi,

I have come up an English to Spanish (Domain Adapted) model that does well. This involved coming up with parallel data, setting up lot of pre-processing steps, developing the base model and then fine-tuning on domain data.

I’m wondering how can I do the following with OpenNMT-tf repo -

- probably a novice question. Create a two directional model - one that performs both English --> Spanish and Spanish --> English. Is this even possible or I have to follow the same process steps twice ending up with two models one for Engligh–>Spanish and another for Spanish to English ?

- Scale model to multiple languages - Something like Google’s Zero Shot translation model. I came across this repo while researching [Cross Lingual Modeling](https://github.com/facebookresearch/XLM). Is this something already available within OpenNMT-tf ?

I have also posted this on forum [2568](http://forum.opennmt.net/t/expanding-the-model-to-two-directional-and-or-multi-language-support/2568). Happy to carry forward the discussion here or on forum

Thanks !

**Comment by guillaumekln** [comment]
Let's keep the discussion in one place:

http://forum.opennmt.net/t/expanding-the-model-to-two-directional-and-or-multi-language-support/2568
