### ISSUE TITLE
Corpus' fields 

### ISSUE THREAD

**Issue by M7md-HaDyS** [OpenNMT/OpenNMT-tf#399]
Which is better using specific corpus field or using a collected corpus fields?? I mean if I have a finance corpus (about 17 millions words) or IT corpus (about 14 millions words) will be better to use individually or I can collect both corpses and use them as a one corpus. 

Also I have another question related to the NMT quality :

how many word count per corpus should I have to reach quality not less than 80%

**Comment by guillaumekln** [comment]
> Which is better using specific corpus field or using a collected corpus fields?? I mean if I have a finance corpus (about 17 millions words) or IT corpus (about 14 millions words) will be better to use individually or I can collect both corpses and use them as a one corpus.

If you want to train an IT model, only use the IT corpus. However, if you want to train a more general model, use all data.

> how many word count per corpus should I have to reach quality not less than 80%

There is no good answer to that. You should probably experiment.

**Comment by M7md-HaDyS** [comment]
Does this mean if I have an IT file it prefers to translate it on the IT model rather than translate it on the collected general model ?

**Comment by xiaotaw** [comment]
One practical way: using all the corpora for several epochs, and then the specific corpus for the next several epochs.
