### ISSUE TITLE
[KeyError: 'vocabulary' ] when gpt-2 training 

### ISSUE THREAD

**Issue by byuns9334** [OpenNMT/OpenNMT-tf#403]
when I type
"CUDA_VISIBLE_DEVICES=1 onmt-main train --model gpt-2.py --auto_config --config config/config_gpt2.yml" for gpt-2 training, I get this error:
/home/users/woody/opennmt/lib/python3.5/site-packages/opennmt/config.py:139: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
 subconfig = yaml.load(config_file.read())
Traceback (most recent call last):
 File "/home/users/woody/opennmt/bin/onmt-main", line 10, in <module>
   sys.exit(main())
 File "/home/users/woody/opennmt/lib/python3.5/site-packages/opennmt/bin/main.py", line 169, in main
   hvd=hvd)
 File "/home/users/woody/opennmt/lib/python3.5/site-packages/opennmt/runner.py", line 96, in __init__
   self._model.initialize(self._config["data"])
 File "/home/users/woody/opennmt/lib/python3.5/site-packages/opennmt/models/model.py", line 70, in initialize
   self.examples_inputter.initialize(metadata)
 File "/home/users/woody/opennmt/lib/python3.5/site-packages/opennmt/inputters/text_inputter.py", line 356, in initialize
   metadata, asset_dir=asset_dir, asset_prefix=asset_prefix)
 File "/home/users/woody/opennmt/lib/python3.5/site-packages/opennmt/inputters/text_inputter.py", line 251, in initialize
   self.vocabulary_file = metadata[self.vocabulary_file_key]
KeyError: 'vocabulary'

I tried so hard to fix this problem but it still doesn't work.
also when I trained other models like 'CUDA_VISIBLE_DEVICES=0 onmt-main train_and_eval --model_type Transformer --auto_config --config config.yml', it worked well. 

Why do I get this 'KeyError: 'vocabulary'' error?

**Comment by guillaumekln** [comment]
For language models, the vocabulary file should be defined in the configuration like this:

```yml
data:
  vocabulary: /path/to/your/vocabulary.txt
```

**Comment by byuns9334** [comment]
@guillaumekln  I already did it. so my config for gpt-2 now is :

model_dir: run_GPT2/

data:
    train_features_file: src_trn.txt
    train_labels:file: tgt_trn_jamo.txt
    eval_features_file: src_val.txt
    eval_labels_file: tgt_val_jamo.txt
    source_words_vocabulary: src_vocab.txt
    target_words_vocabulary: tgt_vocab_jamo.txt

params:
    optimizer: AdamOptimizer 


Is there any more information I need to add in config?

**Comment by guillaumekln** [comment]
You used `source_words_vocabulary`, not `vocabulary`.

Also, training a language model does not require configurations related to labels/target.

**Comment by byuns9334** [comment]
@guillaumekln thanks brother, it works now!! have a good day!
