### ISSUE TITLE
question about decoding some words

### ISSUE THREAD

**Issue by wingsyuan** [OpenNMT/OpenNMT-tf#406]
Hi，
you know there are many words or symbols in some corpuses no need to translate..
for example (1)...(9)（a)...(z)   （aa)...(af), "Donald J. Trump" "USA"、 numbers、date and time an so on, 

Can the decoder of NMT directly copy the  above words to the target sentence base on some rule table? thanks very much!

**Comment by guillaumekln** [comment]
Hi,

Subword tokenization like BPE or SentencePiece can handle this fairly well given that you have enough training examples.

Another practice is to detect such entities with an external system and replace them by a placehoder tokens, which reduces the number of combinations that the model has to learn.
