### ISSUE TITLE
Using full aspects

### ISSUE THREAD

**Issue by opennmt91** [OpenNMT/OpenNMT-tf#407]
Hello, I am a new user for your machine translation, I already installed it and now I need to know how to use the full capacity of my PC while preparation, training and translation so what is the appropriate commands can I use ?? 

Best Regards.

**Comment by guillaumekln** [comment]
Hi,

Maybe take a look at the [Quickstart](http://opennmt.net/OpenNMT-tf/quickstart.html) page to get started.

**Comment by opennmt91** [comment]
Thanks for your support, I already read the Quickstart and know I am capable of start my job.
So now I am working with conda package and TensorFlow environment but When I installed the 'sentencepiece-master'package from the command 'pip install sentencepiece' they show me I installed the library well but when I started to train my corpus through the command **'spm_train --input=src-train --model_prefix=src-vocab --vocab_size=32000 --character_coverage=0.9995 --model_type=word'** I got that error **'spm_train' is not recognized** could you help and tell me what is the problem ??

**Comment by guillaumekln** [comment]
I see that you asked on the SentencePiece repo which was the correct thing to do.
