### ISSUE TITLE
Sentences getting truncated during model inference/translation.

### ISSUE THREAD

**Issue by nelsonmarcelino** [OpenNMT/OpenNMT-tf#408]
Trained a TransformerBigFP16 model. Used SentencePiece to generate shared vocabulary
and subword sequences. After training wanted to translate some test data containing 
long sentences. Noticed that inferred data had truncated sentences (e.g. truncates
sentences after 100 tokens) How to translate larger sentences?  Added 
maximum_features_length, maximum_labels_length, batch_size etc. to yml 
file but still truncating after 100 tokens? What to do?

```
e.g. TransformerBigFP16.yml: 
model_dir: TransformerBigFP16-dir

data:
  train_features_file: train.es
  train_labels_file: train.en
  eval_features_file: valid.es
  eval_labels_file: valid.en
  source_words_vocabulary: data/mesen.vocab
  target_words_vocabulary: data/mesen.vocab

train:
  save_checkpoints_steps: 1000
  maximum_features_length: 1000
  maximum_labels_length: 1000

eval:
  eval_delay: 3600  # Every 1 hour
  external_evaluators: BLEU
  maximum_features_length: 1000
  maximum_labels_length: 1000

infer:
  batch_size: 4096
  batch_type: tokens
  maximum_features_length: 4096
  maximum_labels_length: 4096
  #batch_size: 32
  #maximum_features_length: 1000
  #maximum_labels_length: 1000


e.g. eval.sh:
...
onmt-main infer \
  --config TransformerBigFP16.yml --auto_config \
  --checkpoint_path=$runconfig/avg \
  --features_file testdata/$testset \
  > testdata/$testset.trans
```

**Comment by guillaumekln** [comment]
```yaml
train:
  maximum_features_length: 1000
  maximum_labels_length: 1000
```

Did you use that during training also? If not, the automatic value is set to 100 which could explain that the model does not know how to generate sentences longer than 100 tokens.

Also, please note that the parameter controlling the maximum number of iterations is the following (presented here with its default value):

```yaml
params:
  maximum_iterations: 250
```

**Comment by nelsonmarcelino** [comment]
@guillaumekln That helped. Thanks.
