### ISSUE TITLE
dual-source transformer has OOM problem

### ISSUE THREAD

**Issue by BigFishMaster** [OpenNMT/OpenNMT-tf#410]
I use dual-source transformer from opennmt-tf by setting the encoders to share parameters. I have to reduce the batch size to avoid OOM.  Compared to standard transformer, batch size is changed from 4096 to 1024 and ffn_inner_dim from 2048 to 1024...
In my mind, it will not cause so much MEMORY if encoders share parameters. Can you help me to find the problem?

**Comment by guillaumekln** [comment]
Dual source Transformer has an additional sub-layer in each decoder layer, see this paper for example: https://arxiv.org/pdf/1809.00188.pdf. So the model itself does use more memory.

Also make sure to constrain both inputs length. This is already done when using `--auto_config`: https://github.com/OpenNMT/OpenNMT-tf/blob/master/config/models/multi_source_transformer.py#L40

**Comment by atebbifakhr** [comment]
I'm also experiencing the same problem.
I use maximum_length 70 for both encoders, and I share everything resulting in ~80M parameters (vocab size is ~35K).
But I cannot increase the effective_batch_size more than 512!

**Comment by BigFishMaster** [comment]
> I'm also experiencing the same problem.
> I use maximum_length 70 for both encoders, and I share everything resulting in ~80M parameters (vocab size is ~35K).
> But I cannot increase the effective_batch_size more than 512, while using 4 gpus with 16GB RAM each.

I think "effective_batch_size " will not affect the memory usage BUT I also have the same problem,.

**Comment by BigFishMaster** [comment]
> Also make sure to constrain both inputs length. This is already done when using `--auto_config`:

Hi. @guillaumekln There is a bug when using '--auto_config', because this priority is lower than runner config.  A better way is to set the "maximum_features_length" in runner config as:
![image](https://user-images.githubusercontent.com/4915869/56497596-cc2f5380-6530-11e9-9e53-1cb7e91a951b.png)

**Comment by BigFishMaster** [comment]
@guillaumekln I found the output_reducer and state_reducer are set to None in order to support dual-source transformer. If I use the default value of output_reducer and state_reducer in ParallelEncoder (````               outputs_reducer=ConcatReducer(axis=1),
               states_reducer=JoinReducer(),```)
![image](https://user-images.githubusercontent.com/4915869/56500082-07834f80-653c-11e9-96dc-28d6ab3bb3e8.png)

**Comment by guillaumekln** [comment]
Thanks for the feedback. I will check the code again but it is expected that dual source transformer has higher memory requirements, especially during training.

> Hi. @guillaumekln There is a bug when using '--auto_config', because this priority is lower than runner config. A better way is to set the "maximum_features_length" in runner config as:

That's expected. User configuration has a higher priority than automatic configuration.

> If I use the default value of output_reducer and state_reducer in ParallelEncoder below, will it be the original transformer ? I think the outputs of two encoders are just concated together to output a single one.

The default argument concatenates the 2 encoder outputs in the time dimension. So yes, the decoder will be the same as the original Transformer.

**Comment by guillaumekln** [comment]
The related code changed quite a bit in the V2 version. I'm closing this issue for now. Feel free to reopen if there are still issues to fit a multi-source Transformer on the GPU memory.
