### ISSUE TITLE
How to set the number of epochs?

### ISSUE THREAD

**Issue by wingsyuan** [OpenNMT/OpenNMT-tf#411]
Hi,
  in opennmt-tf , the config file is set as follow:
train:
  train_steps: 30000
   but if I want to set the number of epoches instead of train_steps like the settings in the Marian,
how to set this? Thanks very much!!!

--mini-batch 1000 --maxi-batch 1000 \
EPOCHS=60
B=12(beam with)

**Comment by guillaumekln** [comment]
Hi,

We only expose the "steps" terminology for simplicity. However, it is possible to run the training epoch by epoch:

```yaml
train:
  train_steps: null
  single_pass: true
```

then:

```
onmt-main train [...]  # 1st epoch
onmt-main train [...]  # 2nd epoch
...
```

You can call `train` in a shell loop for example.

**Comment by wingsyuan** [comment]
@guillaumekln 
Thanks a lot!
