### ISSUE TITLE
got only <unk> token after GPT-2 inference

### ISSUE THREAD

**Issue by byuns9334** [OpenNMT/OpenNMT-tf#412]
Hi, I am trying to inference (generate word sequences) with pretrained GPT-2 model (model.ckpt > 2000000) for korean language, but it only outputs <unk> token (predictions.txt): 

CUDA_VISIBLE_DEVICES="1" onmt-main infer --model model_gpt2.py --config config_gpt2_100k.yml --auto_config --checkpoint_path raw_gpt_2_100k/model.ckpt-2370677 --features_file test.txt > predictions.txt

![image](https://user-images.githubusercontent.com/26813646/56478130-b77a9d80-64e7-11e9-8cb9-2742e1dfbf7b.png)

where test.txt (initial seed words for GPT-2 inference) looks like this : 

![스크린샷 2019-04-22 10 20 55](https://user-images.githubusercontent.com/26813646/56478202-5acbb280-64e8-11e9-8129-d9126babd45c.png)

currently config looks like this : 
![image](https://user-images.githubusercontent.com/26813646/56478161-150eea00-64e8-11e9-9a77-39ce289ec72a.png)

is there any way to solve this problem ? (I got the same problem with ckpt.20000 too)

I am sure all the words in test.txt are in our vocab dictionary. Thanks!

**Comment by guillaumekln** [comment]
Hi,

We had similar issues with the first revision of the GPT-2 configuration. The `weight_decay` parameter was the culprit. I removed in the last version of the model file:

https://github.com/OpenNMT/OpenNMT-tf/commit/ac267850809003748123d083f0214d1d364401a1

Can you retry with this change?

**Comment by BigFishMaster** [comment]
@guillaumekln I tried the newest version of GPT-2 and the below is loss curve:
![image](https://user-images.githubusercontent.com/4915869/56874322-c1624a80-6a6b-11e9-8176-cc5fbd68e87f.png)
The test result is bad when my input is a Chinese sentence in red. the following words are generated. It's repetitive and unsmooth. Seems it learn nothing.
![image](https://user-images.githubusercontent.com/4915869/56874348-fbcbe780-6a6b-11e9-9402-bea527c591f3.png)

**Comment by guillaumekln** [comment]
You should probably let it run for more iterations. Also, I'm not sure label smoothing is helpful here, consider removing it.

**Comment by BigFishMaster** [comment]
@guillaumekln Thanks. After more iterations, the result gets better.
