### ISSUE TITLE
Inference returns random results when using sampling_topk

### ISSUE THREAD

**Issue by BigFishMaster** [OpenNMT/OpenNMT-tf#415]
Hi. When I use sampling_topk = 10 and beam = 1 during inference, the output of model is not under control: random results will be returned. Do I use the sampling_topk in a wrong way?
I want to deploy the model Thus it's important to get centain result for each input.

**Comment by guillaumekln** [comment]
Sorry if this was not clear but that is the point of this parameter: it randomly samples predictions from the top K candidates.

It should not be used for actual inference.

**Comment by BigFishMaster** [comment]
@guillaumekln I have read the original paper and learnt that the sampling method is used to generate synthetic data for further training. Thanks for your help.
