### ISSUE TITLE
Problem in sharing embeddings

### ISSUE THREAD

**Issue by atebbifakhr** [OpenNMT/OpenNMT-tf#416]
I noticed that when I use DualTransformer with sharing parameters between Encoders and also setting sharing level to 'ALL', two sets of embeddings are created with these prefixes:

> **transformer//w_embs**
> **transformer/shared_embeddings/w_embs**

However, it should be one for everything.

**Comment by atebbifakhr** [comment]
I tried to change
`def _get_shared_name(self):
    return ""`
to:
`def _get_shared_name(self):
    return "shared_embeddings"`

in `ParallelInputter` but I'm getting **Duplicate Node** error.

**Comment by atebbifakhr** [comment]
The best way I found is reimplementing `build()` function in `ExampleInputter`.

**Comment by guillaumekln** [comment]
Thanks for reporting. Do you have a working fix that you can share?

**Comment by atebbifakhr** [comment]
I sent a pull request.

It works for DualTransformer, but I'm not sure for other use cases.

**Comment by guillaumekln** [comment]
Thanks. This indeed needs a more general fix: the issue is that the `built` flag is not properly set for `MultiInputter` classes and weights are recreated when the layer is first called. I will push an appropriate fix to that.
