### ISSUE TITLE
About multi-source function

### ISSUE THREAD

**Issue by penny9287** [OpenNMT/OpenNMT-tf#418]
I know that according to the opennmt.encoders.parallelEncoder can realize the multi-source function, I wonder if there have some reference papers that intorduce this thought or some theory I can read.

**Comment by atebbifakhr** [comment]
Hi,
This the first paper leveraging multi-source input: https://arxiv.org/abs/1601.00710

**Comment by penny9287** [comment]
> Hi,
> This the first paper leveraging multi-source input: https://arxiv.org/abs/1601.00710

Thanks for your reply ^_^
