### ISSUE TITLE
Tensorboard validation loss

### ISSUE THREAD

**Issue by bkj** [OpenNMT/OpenNMT-tf#423]
Simple question -- apologies if it's answered in the docs somewhere, but I couldn't find it.

When I train w/ `onmt-main train --config my_config.yml`, I don't see validation metrics showing up in tensorboard.  Is there a flag that I need to set to get them to appear?

Thanks!

**Comment by guillaumekln** [comment]
You should use `train_and_eval` instead of `train`.

**Comment by bkj** [comment]
Great -- thanks!
