### ISSUE TITLE
question about using the shuffled vocabulary

### ISSUE THREAD

**Issue by wingsyuan** [OpenNMT/OpenNMT-tf#424]
Hi,
 NMT always use the vocabulary that  word arrangement with frequency from high to low, but Can I use the shuffled vocabulary , or the vocabulary that  word arrangement with no frequency?
Thanks very much!!!

**Comment by guillaumekln** [comment]
Hi,

The vocabulary order has no importance.

**Comment by wingsyuan** [comment]
Thanks very much!!!@guillaumekln
