### ISSUE TITLE
how to debug values

### ISSUE THREAD

**Issue by WangYongzhao** [OpenNMT/OpenNMT-tf#426]
I was trying to debug values, shapes of my model. i used a standard transformer model, and i add a line in the self_attention_decoder.py. did i miss anything here? or i used that in a wrong way?
@guillaumekln

  def _self_attention_stack(self,
    ....
    **tf.print(first_head_attention)**
    outputs = transformer.norm(inputs)
    return outputs, first_head_attention

**Comment by WangYongzhao** [comment]
thanks @guillaumekln .

tf.Print is actually deprecated, that's why I use tf.print in my first email.

**Warning: THIS FUNCTION IS DEPRECATED. It will be removed after 2018-08-20.** 

I still use the old approach to debug. ( seession.run()   )
tf.print looks more straightforward than my old approach. I tried a lot but didn't find the right way.

**Comment by guillaumekln** [comment]
To use `tf.print` in graph mode, you still need to make sure to run the print op with a control dependency. This is documented in the TensorFlow documentation:

https://www.tensorflow.org/api_docs/python/tf/print

This is a general TensorFlow question and this is probably better asked on StackOverflow.
