### ISSUE TITLE
How to tokenize the text when some words are merged to one word?

### ISSUE THREAD

**Issue by wingsyuan** [OpenNMT/OpenNMT-tf#427]
Hi,
when I process some corpus ,  I found some words are merged as one word, for example:
seniorcolonel(senior colonel,  bpe processed as sen@@ i@@ or@@ colon@@ el ), PoliticalScience(Political Science, bpe processed as P@@ oli@@ tical@@ Science),becausehe(because he, bpe processed as bec@@ a@@ use@@ he), these kind of words are a lot and I can not split them one by one,  and in the BPEprocessed corpora they are processed as above..

Is there any solution to tokenize them properly? thanks very much!!!

**Comment by guillaumekln** [comment]
Hi,

This seems unrelated to OpenNMT-tf. Can you post that on the forum instead? http://forum.opennmt.net/
