### ISSUE TITLE
Something maybe a bug in BeamSearch

### ISSUE THREAD

**Issue by BigFishMaster** [OpenNMT/OpenNMT-tf#432]
The following code updates ```cum_log_probs``` variable by ``` tf.where```. However the elements of ```cum_log_probs``` and ```next_cum_log_probs```  are not consistent because in ```tf.where``` function, the input parameter ```finished``` has been updated in ```_body``` function. Only ```next_cum_log_probs``` are consistent with the returned ```finished```.  That means the finished sequence may have a wrong log_probs score. Could you help me to check this ?
```python
    if attention_history:
      if attn is None:
        raise ValueError("attention_history is set but the model did not return attention")
      attention = attention.write(step, tf.cast(attn, tf.float32))
    outputs = outputs.write(step, output)
    cum_log_probs = tf.where(finished, x=cum_log_probs, y=next_cum_log_probs)
    finished = tf.logical_or(finished, tf.equal(output, end_id))
    return step + 1, finished, state, output, outputs, attention, cum_log_probs, extra_vars
```

https://github.com/OpenNMT/OpenNMT-tf/blob/master/opennmt/utils/decoding.py#L310

**Comment by BigFishMaster** [comment]
I understand this code and close issue

**Comment by guillaumekln** [comment]
Do you confirm it's correct then? Easy to make a mistake in this part of the code.

**Comment by BigFishMaster** [comment]
I re-think this code. The ```finished``` variable can not be used between ```cum_log_probs``` and ```next_cum_log_probs```. I think the code ``` cum_log_probs = tf.where(finished, x=cum_log_probs, y=next_cum_log_probs)```  is to keep the right ```log_probs``` values of the sequences with eos_id (e.g. 1), because ```finished``` can only be updated by ```tf.logical_or(finished, tf.equal(output, end_id))```. For example, a sequence ```[3,4,5,1]``` maybe extended to ```[3,4,5,1,1]``` in the ```while_loop```. The right ```log_probs``` value of this sequence is calculated by the first four tokens rather than the all.

1. Thus, my revision is as follows (not debuged):
old:
https://github.com/OpenNMT/OpenNMT-tf/blob/679e5025d05da91741aafa5a002483f43e4b68cc/opennmt/utils/decoding.py#L205-L209
new:
```python
 next_cum_log_probs = _gather_from_word_indices(total_probs, sample_ids) 
 prev_cum_log_probs = tf.gather(cum_log_probs, beam_indices)
 finished = tf.gather(finished, beam_indices)
 next_cum_log_probs = tf.where(finished, x=prev_cum_log_probs, y=next_cum_log_probs)
 parent_ids = parent_ids.write(step, beam_ids) 
 state = compat.nest.map_structure(lambda s: _gather_state(s, beam_indices), state) 
 return word_ids, next_cum_log_probs, finished, state, (parent_ids, maximum_lengths) 
```

2. Then revise this line:
old:
https://github.com/OpenNMT/OpenNMT-tf/blob/679e5025d05da91741aafa5a002483f43e4b68cc/opennmt/utils/decoding.py#L310
new:
```python
cum_log_probs = next_cum_log_probs
```

**Comment by BigFishMaster** [comment]
@guillaumekln This trick 
https://github.com/OpenNMT/OpenNMT-tf/blob/679e5025d05da91741aafa5a002483f43e4b68cc/opennmt/utils/decoding.py#L291

**Comment by guillaumekln** [comment]
Yes, I looked at the code again and I think it's correct because EOS is forced for finished beams.
