### ISSUE TITLE
Question about SeqTagger Model Serving

### ISSUE THREAD

**Issue by Goofy-G** [OpenNMT/OpenNMT-tf#433]
Hi,
   I have already read the #347, but I also have a question. 
   if  my inputs is "I am a Chinese", the chars tensor is ["I", "a", "m", "a", "C", "h", "i", "n", "e", "s", "e"], the token tensor is ["I", "am", "a", "Chinese"]. how about the length and how about the length of chars tensor and token tensor

**Comment by guillaumekln** [comment]
What do want to know about the length vectors?

**Comment by Goofy-G** [comment]
Hi
I want to serving the model via grpc, but I am not sure about the shape of "chars" and token. My inputs is "I am a Chinese", then send request
```
req.inputs["chars"].CopyFrom(tf.make_tensor_proto([[["I"], ["a"], ["m"], ["a"], ["C"], ["h"], ["i"], ["n"], ["e"], ["s"], ["e"]]], shape=[1, 11, 1]))
req.inputs["tokens"].CopyFrom(tf.make_tensor_proto([["I", "am", "a", "Chinese"]], shape=[1, 4]))
req.inputs["length"].CopyFrom(tf.make_tensor_proto([4], shape=[1]))
........
```
and has failed. I wondered what's wrong about it

**Comment by guillaumekln** [comment]
The `chars` input is of shape [batch size, max sequence length, max word length], so probably something like that:

```
[[["I", "", "", "", "", "", ""], ["a", "m", "", "", "", "", ""], ["a", "", "", "", "", "", ""], ["C", "h", "i", "n", "e", "s", "e"]]]
```

**Comment by Goofy-G** [comment]
I see. Thanks
