### ISSUE TITLE
Typo in Serving / Manual export (auto-config -> auto_config)

### ISSUE THREAD

**Issue by alexisdoualle** [OpenNMT/OpenNMT-tf#434]
On the following page: http://opennmt.net/OpenNMT-tf/serving.html#manual-export

Typo on this line:
onmt-main export --export_dir_base ~/my-models/ende --auto-config --config my_config.yml

giving this error: onmt-main: error: unrecognized arguments: --auto-config

Fixed with --auto_config

**Comment by guillaumekln** [comment]
Can you send a fix to https://github.com/OpenNMT/OpenNMT-tf/blob/master/docs/serving.md? Thanks.

**Comment by alexisdoualle** [comment]
Done.
