### ISSUE TITLE
Why its forced an external evaluator  with save_eval_predictions

### ISSUE THREAD

**Issue by lockder** [OpenNMT/OpenNMT-tf#435]
right know if I want to save the predictions file. I have to setup an external_evaluator, but if for 
example I'm doing a classification or tagger model, none of those external evals helps me 
but I need to save the predictions into a file.

Could be possible to save the predictions file and not setup an external eval?

because right know its crashing here:

File "/Users/sergio.hurtado/gitlab/NaturalLanguageRecognition/venv/lib/python3.6/site-packages/opennmt/utils/evaluator.py", line 187, in make_scorers
    name = name.lower()
AttributeError: 'NoneType' object has no attribute 'lower'

since I want to save the file but I dont want an evaluator external so its None

**Comment by guillaumekln** [comment]
Thanks for reporting. The code should allow it.

**Comment by lockder** [comment]
you are welcome :)
