### ISSUE TITLE
Understanding the Serving Model Output from Transformer Model

### ISSUE THREAD

**Issue by mohammedayub44** [OpenNMT/OpenNMT-tf#439]
Hi @guillaumekln ,
I have a English- Spanish Transformer model deployed for serving, I get the below four variables as prediction outputs  - Length, Log Probabilities, Alignment, Tokens. 

A sample input such "France passed the budget." gives me 4 results as follows:

`{'length': dtype: DT_INT32`
`tensor_shape {`
`  dim {`
`    size: 1`
`  }`
`  dim {`
`    size: 4`
`  }`
`}`
`int_val: 7`
`int_val: 7`
`int_val: 3`
`int_val: 8`

`,'log_probs': dtype: DT_FLOAT`
`tensor_shape {`
`  dim {`
`    size: 1`
`  }`
`  dim {`
`    size: 4`
`  }`
`}`
`float_val: -7.795619487762451`
`float_val: -7.853789329528809`
`float_val: -7.894498825073242`
`float_val: -8.24423599243164`

`,'alignment': dtype: DT_FLOAT`
`tensor_shape {`
`  dim {`
`    size: 1`
`  }`
`  dim {`
`    size: 4`
`  }`
`  dim {`
`    size: 54`
`  }`
`  dim {`
`    size: 5`
`  }`
`}`
`float_val: 0.028136229142546654`
`float_val: 0.07441766560077667`
`....`
`float_val: 0.13134515285491943`
`float_val: 0.004944383632391691`

` , 'tokens': dtype: DT_STRING`
`tensor_shape {`
`  dim {`
`    size: 1`
`  }`
`  dim {`
`    size: 4`
`  }`
`  dim {`
`    size: 55`
`  }`
`}`
`string_val: "la"`
`string_val: "\342\226\201clase"`
`string_val: "\342\226\201aprueba"`
`string_val: "\342\226\201el"`
`string_val: "\342\226\201presupuesto"`
`string_val: "."`
`string_val: "</s>"`
`string_val: "<blank>"`
`string_val: "<blank>"`
`....`
`string_val: "\342\226\2011996"`
`string_val: "<blank>"`

1) Best output in this case - My guess is the first result with length 7 and log probability '-7.795619487762451' is considered as best out of 4 ? (not sure why tensor shape for tokens is 1x4x55)

2) How do I interpret the alignments returned. Planning to plot of heatmap of input and best output.  (Again why is it 1x4x54x5, is it giving 5 probable values for each string_val token returned) , so for best output what alignments values would map back?

Appreciate any help !

**Comment by guillaumekln** [comment]
Hi,

1. You get 4 hypotheses ordered from best to worst. The shape of `tokens` is [batch size, num. hypotheses, max sequence length].
2. The `alignment` is of shape [batch size, num. hypotheses, max target length, max source length].

If you only care about the best prediction, you should only select the first index of the second dimension, e.g. `tokens[:, 0]`.

Is that helpful?

**Comment by mohammedayub44** [comment]
@guillaumekln 

Yeah, extracting first dim from token works. And for mapping the corresponding alignments to best output I'm doing the following - 
###### Converting into np arrays
`    batch_lengths = tf.make_ndarray(result.outputs["length"])`
`    batch_predictions = tf.make_ndarray(result.outputs["alignment"])`
###### Getting the first dim from alignments
`    best_hypothesis = batch_predictions[0][0]`
`    best_length = batch_lengths[0][0] - 1 # Ignoring </s>`
###### Return float values only for best output
`     return best_hypothesis[:best_length]`
###### Plotting the heatmap
`fig = plt.figure()`
`            sns.heatmap(bestalignment_data, cmap = "Reds", annot=annot, fmt=".1f", cbar = True, linewidths=.5, xticklabels = en_tokens, yticklabels = es_tokens)`
`            plt.xticks(rotation=45)`

I get the following output, which makes it a little confusing to understand:

![image](https://user-images.githubusercontent.com/7122670/58394174-e9fc4680-800f-11e9-8e9c-496a32c57cba.png)

My assumption was it should give more weights to "apreuba" and "passed", "el" and "the", instead it feels like alignments are always off on some very words (/or my code is wrong /or model is very bad) and for some reason its always giving more weight to "." character even though the output is almost good. Here's another one just for characters. 

![image](https://user-images.githubusercontent.com/7122670/58394367-d9989b80-8010-11e9-960f-404fa4e3b019.png)

Appreciate your thoughts.

**Comment by guillaumekln** [comment]
If the Transformer model was not trained with guided alignment, then the alignments are not usable.

**Comment by guillaumekln** [comment]
Closing. Feel free to reopen if you feel there is something missing.
