### ISSUE TITLE
Relative position representations

### ISSUE THREAD

**Issue by WangYongzhao** [OpenNMT/OpenNMT-tf#440]
I see py version has this feature, OpenNMT/OpenNMT-py#1198
does tf version has similar feature?

**Comment by WangYongzhao** [comment]
I see py version has this feature, https://github.com/OpenNMT/OpenNMT-py/issues/1198
does tf version has similar feature?

**Comment by guillaumekln** [comment]
This was not implemented. Contributions are welcome.

**Comment by WangYongzhao** [comment]
sure
