### ISSUE TITLE
ParallelInputter, MixedInputter and build method

### ISSUE THREAD

**Issue by lockder** [OpenNMT/OpenNMT-tf#444]
Is there any reason why MixedInputter does nothing when the build method is called and its waiting to the method make_inputs to check the WordEmbedder is not built to call the WordEmbedder build method?
I'm asking because on ParallelInputs build method is already doing stuff, so I find weird that MixedInputter its not doing anything at all on that method

**Comment by guillaumekln** [comment]
There is no good reason for the method override to be missing. But do you encounter an issue with that?

**Comment by lockder** [comment]
I'm trying to create a multihead model just by subclassing the classes and not touching the opennmt lib and since I'm doing that I first build the inputs outside the scope of each model, so I found I had to check if the inputter was MixedInputter to force the build phase.

I was waiting to see if I was able to create it and share it with you so if may be useful for the lib
something like https://www.tensorflow.org/api_docs/python/tf/contrib/estimator/multi_head
but since I'm trying not to touch anything rather than subclassing I can't use that method

**Comment by lockder** [comment]
also I seen ClassInputter make_features is not sending back the lenght I guess beacuse its already thinking the lenght will be one but its forcing me to subclass that class to return the lenght

**Comment by guillaumekln** [comment]
What modules are using with `MixedInputter`? I think I did not override `build()` because it is commonly used with `CharConvEmbedder` and `CharRNNEmbedder` which do no implement `build()`. The build() approach will be generalized in TensorFlow 2.0 as all layers will be stateful. I will probably wait for that to make the change.

In the meantime, it should be easy enough for you to subclass to adapt the behavior (like you did for `ClassInputter`).

**Comment by lockder** [comment]
yes thanks, When I'm done and if it works I would like to show you so it may useful.
if we have multihead model we can have models like GAN or models using outputs from other models as features or sharing inputs for multi target training like in https://arxiv.org/abs/1901.11504
