### ISSUE TITLE
get_receiver_tensors and make_features error in ParallelInputter

### ISSUE THREAD

**Issue by lockder** [OpenNMT/OpenNMT-tf#448]
Hi there I found that when I'm exporting the get_receiver_tensors will always add the counter of the inputter so avoid clashing with the other inputter tensor and thats fine

the issue comes while exporting after the get_receiver_tensors, then the make features is called in my model the combine features is deactivated on that moment so the extract_prefixed_keys is not called and the features are not found.

I will overwrite the class to fix it but not sure if this kind of behavior is the right think because those methods are interconnected and the make features is expecting to be set the flag self.combine_features  and that may not be the case.

the expected thing for me is to keep the same behavior so I don't see why make_features
shouldn't always add the inputter counter to they prefixed_keys that way never would have any clashing issues

``` 
  def get_receiver_tensors(self):
    receiver_tensors = {}
    for i, inputter in enumerate(self.inputters):
      tensors = inputter.get_receiver_tensors()
      for key, value in six.iteritems(tensors):
        receiver_tensors["{}_{}".format(key, i)] = value <----- here is not checking if self.combine_features is active
    return receiver_tensors
```

```
  def make_features(self, element=None, features=None, training=None):
    if self.combine_features:
      if features is None:
        features = {}
      for i, inputter in enumerate(self.inputters):
        prefix = "inputter_%d_" % i
        sub_features = extract_prefixed_keys(features, prefix)
        if not sub_features:
          # Also try to read the format produced by get_receiver_tensors.
          sub_features = extract_suffixed_keys(features, "_%d" % i)
        sub_features = inputter.make_features(
            element=element[i] if element is not None else None,
            features=sub_features,
            training=training)
        for key, value in six.iteritems(sub_features):
          features["%s%s" % (prefix, key)] = value
      return features
    else:
      if features is None:
        features = [{} for _ in self.inputters]
      for i, inputter in enumerate(self.inputters):
        features[i] = inputter.make_features(
            element=element[i] if element is not None else None,
            features=features[i], <---- here is the conflict
            training=training)
      return tuple(features)
```

**Comment by guillaumekln** [comment]
The `combine_features=False` case was mostly a convenient way to define `ExampleInputter` which represents training examples (parallel source and target). It is actually not expected to call `get_receiver_tensors` on it. In fact, `tf.estimator.export.ServingInputReceiver` will not accept a tuple of dict. We should probably raise an error in this case.

Can you do with combined features? The current `make_features` should handle the prefix for you.
