### ISSUE TITLE
Windows: OSError: [WinError 193] %1 is not a valid Win32 

### ISSUE THREAD

**Issue by halidziya** [OpenNMT/OpenNMT-tf#451]
If windows does not detect perl extensions as direct executable file it generates error and stops execution. 

https://github.com/OpenNMT/OpenNMT-tf/blob/a8d70bb7dbc55ccb563251e7d6ce067e54f53645/opennmt/utils/evaluator.py#L148

**Comment by guillaumekln** [comment]
Is the following a good fix for Windows? I don't have a Windows machine to test right now.

```python
bleu_out = subprocess.check_output(
    ["perl", os.path.join(third_party_dir, self._bleu_script), labels_file],
    stdin=predictions_file,
    stderr=subprocess.STDOUT)
```
