### ISSUE TITLE
is the score different in mode score/infer?

### ISSUE THREAD

**Issue by WangYongzhao** [OpenNMT/OpenNMT-tf#455]
anyone know the score differentces in these 2 modes?

**Comment by WangYongzhao** [comment]
just double confirm,  score_score = 0 - score_infer ?

**Comment by guillaumekln** [comment]
The scores from `score` are the negative log likelihood (or cross entropy) of the reference target.
The scores from `infer` are the cumulated log probabilities of generated tokens.

**Comment by WangYongzhao** [comment]
thanks, that explains why I got 
**score_score = - score_infer**
