### ISSUE TITLE
model serving questions

### ISSUE THREAD

**Issue by WangYongzhao** [OpenNMT/OpenNMT-tf#459]
I am trying to deploy the model in a existing DL system. I can refer main.py and runner.py to initilize my model directly. 
By referring this one https://github.com/OpenNMT/OpenNMT-tf/tree/master/examples/serving, it has dependency on docker and grpc, so this not work for me.
```
class ModelImp:
    def  __init__(self):
        print('loading model...')
        # Load your model here
        print('model loaded.')

    # data is a string
    def Infer(self, data):
        # Implement your string inference here
        return "hello {0}".format(data)
```

my idea is the old way approcach like  sess.run(result,feed_dict={intput:x})
```
    # data is a string,like "hello world"
    def Infer(self, data):
        # Implement your string inference here
        x=[['hello','world']]
        l=[2]
        result= session.run(res, feed_dict={x, l, ..})
        data=parse(result)
        return "hello {0}".format(data)
```
so my question is 
1. As current opennmt-tf relies on tf.data.Dataset (reading from files), is there any suggestion for my scenario?
currently I only found tf.make_tensor_proto, should work.
2. my plan is doing as the function translate(...)  https://github.com/OpenNMT/OpenNMT-tf/blob/master/examples/library/minimal_transformer_training.py, any better suggestion?

**Comment by guillaumekln** [comment]
This thread could help to load a `SavedModel` from Python: http://forum.opennmt.net/t/opennmt-inference-system/2760

See also: http://opennmt.net/OpenNMT-tf/serving.html

**Comment by WangYongzhao** [comment]
really thanks, this is really helpful, will also help others if put this in expamles folder.

**Comment by WangYongzhao** [comment]
1 more question, the solution above seems only works for inference. 

by checking opennmt-tf code, seems that it reuse training graph for scoring.

So if I want to use scoring for my service, I may need update the export function and saving training graph tf.saved_model.tag_constants.TRAINING. Is there similar script before?

**Comment by guillaumekln** [comment]
There is no such example. You would have to write something custom. Look at how the model is currently exported and how the scoring is implemented.

If exporting is too cumbersome, you can still use placeholders and the `sess.run` approach.

**Comment by WangYongzhao** [comment]
I was trying to use exporting, by reading the code, any insight of the approach below?

1. line 28/29 seems useless, can you confirm?  https://github.com/OpenNMT/OpenNMT-tf/blob/master/opennmt/estimator.py#L28
2. as now i need input/label, so i also need refer the variable labels_inputter in sequence_to_sequence.py, and combine labels_inputter/features_inputter.

**Comment by guillaumekln** [comment]
1. It's only required to export a specific input type, read the comment above.
2. Yes you probably need to customize some functions.

**Comment by WangYongzhao** [comment]
seems this feature is not that straightforward, tried some solutions, still not work it out to export the model. will keep updated.
https://stackoverflow.com/questions/56750697/serve-a-sequence-to-sequence-model-for-scoring

**Comment by guillaumekln** [comment]
Ok, thanks. I will close this thread as this is not really an issue with the current code.

**Comment by WangYongzhao** [comment]
if anyone need similar function. here are some code pieces.
But this method depends on an official tensorflow feature, tf.estimator.export.SupervisedInputReceiver
you need activate this by yourself.

```
 def get_serving_input_receiver_tensors(self):
    receiver_tensors = self.get_receiver_tensors()
    features = self.make_features(features=receiver_tensors.copy())
    return receiver_tensors, features

def make_serving_input_fn_new(model, metadata=None):
  def _fn():
    local_model = copy.deepcopy(model)
    tensor_src,f_src = local_model.features_inputter.get_serving_input_receiver_tensors()
    tensor_tgt,f_tgt = local_model.labels_inputter.get_serving_input_receiver_tensors()
    com_f = {}
    for key, value in f_src.items():
        com_f[key] = value
    for key, value in f_tgt.items():
        com_f[key] = value
    
    com_tensor ={}
    for key, value in tensor_src.items():
        com_tensor[key] = value
    for key, value in tensor_tgt.items():
        com_tensor[key] = value
        
    return tf.estimator.export.SupervisedInputReceiver(f_src,f_tgt, com_tensor)

  return _fn

```
