### ISSUE TITLE
Three-way weight tying on Transformer

### ISSUE THREAD

**Issue by alphadl** [OpenNMT/OpenNMT-tf#462]
As mentioned in the paper [Weight Tying](https://arxiv.org/pdf/1608.05859.pdf), weight tying seems a useful trick that could reduce the parameter size and improve the model inference quality. Is there anyone who tried this trick in Opennmt-tf?

**Comment by alphadl** [comment]
i.e., Using the option during training ```--share_decoder_embeddings ----share_embeddings```

**Comment by guillaumekln** [comment]
There is an example model for you to try: https://github.com/OpenNMT/OpenNMT-tf/blob/master/config/models/transformer_shared_embedding.py

**Comment by alphadl** [comment]
Thx, I am wondering that if this trick could reduce the parameter scale and improve translation quality, why this setting does not default?  I find that sockeye maked this as a default setting

**Comment by guillaumekln** [comment]
It's not the default because it requires that source and target vocabularies have the same size which is not always true.
