### ISSUE TITLE
Question about eager execution.

### ISSUE THREAD

**Issue by atebbifakhr** [OpenNMT/OpenNMT-tf#465]
Hi,

I noticed that for dropping checkpoints in eager execution mode, the model should inherit tf.keras.Model, however in OpenNMT-tf models are tf.keras.layers subclasses.

Do you know a way for this problem? and is there any reason that you didn't choose tf.keras.Model to inherit from for the models in OpenNMT-tf?

**Comment by guillaumekln** [comment]
Hi,

What checkpoint utility are you referring to? It should not make a difference whether the object inherits from `Model` or `Layer`.

**Comment by atebbifakhr** [comment]
I used this one: `tfe.save_network_checkpoint`

**Comment by guillaumekln** [comment]
OpenNMT-tf models are currently not compatible with this API that requires all variables to be accessible from the model object via nested Keras layers.

As this will be the recommended design in TensorFlow 2.0, I'm working towards that in a [separate branch](https://github.com/guillaumekln/OpenNMT-tf/tree/v2).
