### ISSUE TITLE
window10: unable to pip install OpenNMT-tf

### ISSUE THREAD

**Issue by qwtao** [OpenNMT/OpenNMT-tf#466]
Here is the problem:

> Collecting OpenNMT-tf
  Using cached https://files.pythonhosted.org/packages/de/e9/eef6ceccc0fe17cb283453b626161b1a40967cee0eb09e864b6280d8e7db/OpenNMT_tf-1.24.0-py2.py3-none-any.whl
Requirement already satisfied: rouge==0.3.1 in e:\python\anaconda\lib\site-packages (from OpenNMT-tf) (0.3.1)
Requirement already satisfied: sacrebleu==1.*; python_version >= "3.0" in e:\python\anaconda\lib\site-packages (from OpenNMT-tf) (1.3.6)
Collecting pyyaml>=5.1 (from OpenNMT-tf)
  Using cached https://files.pythonhosted.org/packages/71/f7/5513e0982417c0a497b5194cc975831755447ab5e64c5fe4c877c1706a7a/PyYAML-5.1.1-cp36-cp36m-win_amd64.whl
Requirement already satisfied: typing in e:\python\anaconda\lib\site-packages (from sacrebleu==1.*; python_version >= "3.0"->OpenNMT-tf) (3.6.2)
chatterbot-corpus 1.1.2 has requirement PyYAML<4.0,>=3.12, but you'll have pyyaml 5.1.1 which is incompatible.
Installing collected packages: pyyaml, OpenNMT-tf
  Found existing installation: PyYAML 3.12
Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

I have noticed that the code here has been updated to be compatible to PyYAML 5.1, but the code downloaded by pip is obviously the old version.  What can I do now? I guess I need to download the code here manually, and then put it in the site-packages directory.

**Comment by guillaumekln** [comment]
This is not a issue with OpenNMT-tf but with the package `chatterbot-corpus` that requires an old version of PyYAML.
