### ISSUE TITLE
are there any examples about language model?

### ISSUE THREAD

**Issue by Pekary** [OpenNMT/OpenNMT-tf#467]
i found https://github.com/OpenNMT/OpenNMT-tf/pull/356 finished language model training and generation. but the `model_type` argument dosen't support Language Model. 

for training a language model, i use custom model definition as blow:
```python
from opennmt.utils.misc import merge_dict

import opennmt as onmt


class MyLanguageModel(onmt.models.LanguageModel):
  def __init__(self):
    super(MyLanguageModel, self).__init__(
      decoder=onmt.decoders.SelfAttentionDecoderV2(num_layers=6, num_sources=0),
      embedding_size=512,
    )
  def auto_config(self, num_devices=1):
    config = super(MyLanguageModel, self).auto_config(num_devices=num_devices)
    return merge_dict(config, {
        "params": {
            "average_loss_in_time": True,
            "label_smoothing": 0.1,
            "optimizer": "LazyAdamOptimizer",
            "optimizer_params": {
                "beta1": 0.9,
                "beta2": 0.998
            },
            "learning_rate": 2.0,
            "decay_type": "noam_decay_v2",
            "decay_params": {
                # "model_dim": self._num_units,
                "model_dim": 512,
                "warmup_steps": 8000
            }
        },
        "train": {
            "effective_batch_size": 25000,
            "batch_size": 3072,
            "batch_type": "tokens",
            "maximum_features_length": 100,
            "maximum_labels_length": 100,
            "keep_checkpoint_max": 8,
            "average_last_checkpoints": 8
        }
    })


model=MyLanguageModel
```

during training time, there are a lot of message like this:
`WARNING:tensorflow:It seems that global step (tf.train.get_global_step) has not been increased. Current value (could be stable): 144 vs previous value: 144. You could increase the global step by passing tf.train.get_global_step() to Optimizer.apply_gradients or Optimizer.minimize.
`
dose this matter?

it seems few docs about language model in Opennmt-tf . 

so are there some examples about language model training and generation?

**Comment by guillaumekln** [comment]
> during training time, there are a lot of message like this: [...] dose this matter?

No.

> so are there some examples about language model training and generation?

There is an example model here: https://github.com/OpenNMT/OpenNMT-tf/blob/master/config/models/gpt_2.py. Then, most of the documentation about translation also applies to language modeling.

What issue are you facing specifically?

**Comment by Pekary** [comment]
I'm not sure whether the usage is correct, the example model helps, thank you!
