### ISSUE TITLE
onmt-main infer - using multiple GPUs

### ISSUE THREAD

**Issue by nelsonmarcelino** [OpenNMT/OpenNMT-tf#474]
How to use onmt-main infer to do inference with multiple GPUs (e.g. num_gpus 8)
Having run a few tests and increasing batch_size generates OOM errors and 
does not appear to leverage multiple GPUs, only a single one.

**Comment by guillaumekln** [comment]
Multiple GPUs are only supported for training, the option is ignored during inference. You could instead split your file and run separate inference processes to leverage multiple GPUs.
