### ISSUE TITLE
installing on gcp

### ISSUE THREAD

**Issue by peithous** [OpenNMT/OpenNMT-tf#479]
I install successfully on a tensorflow optimized vm and when I run python I can import the module opennmt. However, when I run the basic command "opennmt-main -h" from the gcp-vm console the shell returns command not found.

**Comment by leod** [comment]
Have you also tried `onmt-main -h`?

**Comment by peithous** [comment]
Yes, onmt-main -h is what I was actually trying.

**Comment by peithous** [comment]
<img width="1418" alt="Screen Shot 2019-08-14 at 5 29 53 AM" src="https://user-images.githubusercontent.com/27439526/63010729-e761fe00-be54-11e9-8a48-ea002f4f2592.png">

**Comment by leod** [comment]
You will probably need to do something like the following for pip's install directory:
```
export PATH=~/.local/bin:$PATH
```

**Comment by peithous** [comment]
something seems to be going on with tensorflow
<img width="1127" alt="Screen Shot 2019-08-14 at 6 49 29 AM" src="https://user-images.githubusercontent.com/27439526/63015760-d5d22380-be5f-11e9-8484-d2b254e3aaa6.png">

**Comment by peithous** [comment]
all set, thanks!

**Comment by peithous** [comment]
I installed tensorflow, I only had tensorflow-gpu. How come the library does not work with tensorflow-gpu?

**Comment by leod** [comment]
The library does work with tensorflow-gpu, but there may be a mismatch between your installed version of CUDA (is it CUDA 9.0?) and the version that tensorflow-gpu is compiled against here (which is CUDA 10.0).

If it is the case that you have CUDA 9.0, you can either install an older version of TensorFlow (e.g. TensorFlow 12.0, see here for requirements: https://www.tensorflow.org/install/source#tested_build_configurations) or compile TensorFlow yourself.

**Comment by peithous** [comment]
Would I be able to use the gpu with regular tensorflow?

**Comment by leod** [comment]
No, you will need some version of tensorflow-gpu for that.

**Comment by peithous** [comment]
I have CUDA 9.1. Is tensorflow_gpu-1.12.0 the correct version?

**Comment by peithous** [comment]
Should I uninstall and re-install OpenNMT?
<img width="933" alt="Screen Shot 2019-08-14 at 7 51 00 AM" src="https://user-images.githubusercontent.com/27439526/63019048-56951d80-be68-11e9-9ef0-28cf96bbab06.png">

**Comment by leod** [comment]
Not sure where this comes from, could be an issue with your TensorFlow installation.

**Comment by peithous** [comment]
I'm trying to run the quickstart example now, exactly as I did on my computer, but on gcp I get this error 
<img width="1233" alt="Screen Shot 2019-08-14 at 9 14 15 AM" src="https://user-images.githubusercontent.com/27439526/63023884-0e7bf800-be74-11e9-8990-8341b515fa78.png">

**Comment by guillaumekln** [comment]
> I have CUDA 9.1. Is tensorflow_gpu-1.12.0 the correct version?

The binaries of TensorFlow 1.5 to 1.12 are compiled with CUDA 9.0, not 9.1

> I'm trying to run the quickstart example now, exactly as I did on my computer, but on gcp I get this error

From the error message, looks like you YAML file is invalid?

**Comment by peithous** [comment]
thank you!
