### ISSUE TITLE
About Combination Method implementation in multi-source machine Translation

### ISSUE THREAD

**Issue by hero007feng** [OpenNMT/OpenNMT-tf#480]
Looking at the issue https://github.com/OpenNMT/OpenNMT-tf/issues/418, I found that multi-source NMT is based on the paper 'Multi-Source Neural Translation' is with proposed two combine method, but I can't found where the combination method is implemented. 
Thanks!

**Comment by guillaumekln** [comment]
There are multiple ways to implement multi source and we did not specifically follow this paper. In the current code, I would say there are 2 combination methods implemented:

* at the encoder level, multiple source can be encoded separately then merged together, see https://github.com/OpenNMT/OpenNMT-tf/blob/v1.24.0/opennmt/encoders/encoder.py#L111
* at the decoder level (Transformer only), attention can be computed sequentially on each source, see https://github.com/OpenNMT/OpenNMT-tf/blob/v1.24.0/opennmt/decoders/self_attention_decoder.py#L174

**Comment by hero007feng** [comment]
Thanks for your quick reply.
