### ISSUE TITLE
traceback

### ISSUE THREAD

**Issue by peithous** [OpenNMT/OpenNMT-tf#481]

**Comment by peithous** [comment]
<img width="525" alt="Screen Shot 2019-08-15 at 12 25 58 PM" src="https://user-images.githubusercontent.com/27439526/63109846-144b0980-bf58-11e9-8558-b6dc7c50def6.png">
I am not sure what is going wrong. I am trying to run with my texts, arranged in the same way as the toy-ende example. Everything seems to start up correctly (tensorboard works) and then training shuts down.

**Comment by Dagamies** [comment]
You are missing "src-val.txt". This is most likely defined in .yml file where you have defined also your training data. During evaluation it can not find this file.

**Comment by peithous** [comment]
I have the file, that's why I can't tell why it's not being found. 
<img width="405" alt="Screen Shot 2019-08-15 at 1 33 16 PM" src="https://user-images.githubusercontent.com/27439526/63113776-41e88080-bf61-11e9-8788-a43a3e3311be.png">

**Comment by Dagamies** [comment]
Can you share your data.yml?

**Comment by peithous** [comment]
<img width="546" alt="Screen Shot 2019-08-15 at 1 38 19 PM" src="https://user-images.githubusercontent.com/27439526/63114102-fc788300-bf61-11e9-91db-be5997e938b1.png">
