### ISSUE TITLE
score function

### ISSUE THREAD

**Issue by peithous** [OpenNMT/OpenNMT-tf#483]
It's unclear in the documentation what the config file for scoring should look like. 

I run "onmt-main score --config data.yml --features_file tgt-test.txt --predictions_file decoded-test.txt" with the same config file that I use to train. 

I also can't find any documentation on interpreting the output of score, which returns a small part of the test file with three numbers before each sentence. I am attaching a picture of the end of the output
<img width="1131" alt="Screen Shot 2019-08-17 at 5 38 02 AM" src="https://user-images.githubusercontent.com/27439526/63209647-93a02080-c0b1-11e9-86dd-e07e686fff8a.png">

**Comment by guillaumekln** [comment]
> It's unclear in the documentation what the config file for scoring should look like.

There are some score related parameters that can be configured, see http://opennmt.net/OpenNMT-tf/configuration.html. Other than that, it's usually the same as the training.

> I also can't find any documentation on interpreting the output of score, which returns a small part of the test file with three numbers before each sentence.

Does http://opennmt.net/OpenNMT-tf/inference.html#scoring help?

**Comment by peithous** [comment]
I guess the interpretation makes sense. I had overlooked the last couple of sentences. 

I have read the first page you linked to many times and I really can't infer based on what is there how to use OpenNMT-tf to calculate BLEU scores. It's easy to use SacreBLEU of course, but it would be nice to be able to do it directly with OpenNMT.

**Comment by guillaumekln** [comment]
Currently, BLEU scoring is only applied to the evaluation files during the `train_and_eval` or `eval` run types.

If you want to score a particular file, you could replace the evaluation files in `data.yml`, e.g.:

```yml
data:
  eval_features_file: data/toy-ende/src-val.txt
  eval_labels_file: data/toy-ende/tgt-val.txt

eval:
  external_evaluators: sacreBLEU
```

and run an `eval` command.

**Comment by peithous** [comment]
thank you!
