### ISSUE TITLE
Serving large files for NMT translation optimizing on GPU instance

### ISSUE THREAD

**Issue by mohammedayub44** [OpenNMT/OpenNMT-tf#484]
#### Description:  
I have a client app that accepts text files for translation(English-Spanish). I use GPU hardware (p2.xlarge ec2 instance, 12GB memory) to accelerate inference. I'm also using batching_parameters_file.txt

`max_batch_size { value: 16384 }`   --> Files are big (sentences greater than 10,000) hence large value to avoid client request error
`batch_timeout_micros { value: 10000000 }` --> for bulk requests
`pad_variable_length_inputs: true`
`allowed_batch_sizes: 2`
`allowed_batch_sizes:8`
`allowed_batch_sizes: 16`
`allowed_batch_sizes: 32`
`allowed_batch_sizes: 64`
`allowed_batch_sizes: 128`
`allowed_batch_sizes: 256`
`allowed_batch_sizes: 512`
`allowed_batch_sizes: 1024`
`allowed_batch_sizes: 2048`
`allowed_batch_sizes: 4096`
`allowed_batch_sizes: 8192`
`allowed_batch_sizes: 16384`
`num_batch_threads { value: 2 }` --> max_cpu cores on p2 instance
`max_enqueued_batches { value: 10000 } ` --> initially set to large value

Also, to avoid `RESOURCE EXHAUSTED ...message exceeded 4MB error`, I change the `max_message_length` as below:
`no_max_message_sizes = [("grpc.max_receive_message_length", -1), ("grpc.max_send_message_length", -1)]`
`channel = grpc.insecure_channel("%s:%d" % (args.host, args.port),options = no_max_message_sizes)`

#### Errors:
When inputting a file greater than 128 sentences (actually has ~500 sentences), it gives OOM errors on GPU, however when I run this on CPU only version it does not give me any error (provided the time taken is very long)
Why does batching with GPU not queue up the remaining sentences into successive batches and thereby avoiding OOM issues ?

![GPU_OOM_Error_inference](https://user-images.githubusercontent.com/7122670/63370742-d92e4900-c350-11e9-8fc8-98a8454b7057.PNG)

This is my current client request code looks:

`def send_request(stub, model_name, batch_tokens, timeout=5.0):`
`    batch_tokens, lengths, max_length = pad_batch(batch_tokens)`
`    batch_size = len(lengths)`
`    request = predict_pb2.PredictRequest()`
`    print("Model Name: ", model_name)`
`    request.model_spec.name = model_name`
`    request.inputs["tokens"].CopyFrom(
        tf.make_tensor_proto(batch_tokens, shape=(batch_size, max_length)))`
`    request.inputs["length"].CopyFrom(
        tf.make_tensor_proto(lengths, shape=(batch_size,)))`
`    return stub.Predict.future(request, timeout)`

#### Suggestions - 
Do i need to custom batch my input (divide all incoming file data into 128 length batches and pass to send_request fn ) from the files or is there a better solution for this ?

Any help appreciated.

**Comment by guillaumekln** [comment]
> max_batch_size { value: 16384 }

This seems like a very big batch size. I don't think this fits on the GPU memory. Also note that a greater batch size does not necessarily improve the performance. You can test for yourself with the command `onmt-main infer [...] --log_prediction_time`.

You should probably set a maximum batch size to 64 or 128.

**Comment by mohammedayub44** [comment]
Yes, 16384 was just a placeholder to avoid errors. I found that p2.xlarge can hold only 128 sentences at once. My guess was the batching functionality -  `max_enqueued_batches` and `max_bacth_size` automatically figure this out irrespective of the file size. This means that I manually need to divide my input file into 64 or 128 size batches before sending it to send_request function ? 
then what's the need of this parameter - `max_enqueued_batches`

Thanks !

**Comment by guillaumekln** [comment]
This is better asked on the TensorFlow Serving repo but I don't think it can split up incoming batches. Instead, it can batch requests that are coming within the `batch_timeout_micros` timeframe. This configuration is suited to serve multiple clients concurrently. In case of file translation, it's just easier to control the batching directly in the client.

**Comment by mohammedayub44** [comment]
Sounds good. Let's keep this open for a little while as I try the split batches on GPU. Keep you posted.

**Comment by guillaumekln** [comment]
How do you measure the translation time?

**Comment by mohammedayub44** [comment]
Presently I'm just using simple time.time() function on send_request() fn which I have above, which is actually doing the translation (calling `stub.Predict.future(request, timeout)` ) 
`start= time.time()`
`    future = send_request(model_name, batch_input, timeout=timeout)`
`    end = time.time()`
`print("Time Taken to Translate: "+str((end- start))+" secs")`


and also using time.time() on the main translate function that is called from tornado (web framework) RequestHandler. like below:

`def make_app():`
`    root = os.getcwd()`
`    print(root)`
`    return tornado.web.Application([`
`        (r"/upload", UploadHandler),`
`        (r'/(.*)',`
`         tornado.web.StaticFileHandler,
`         {'path': root + '/template/', 'default_filename': 'index.html'})`
`    ], debug=True)`

`class UploadHandler(tornado.web.RequestHandler):`
`....`
`def post(self):`
`start = time.time()`
`        for batch in batches:`
`            result.extend(client.translate_file(client.args.model_name, batch, client.tokenizer,`
`                                       timeout=client.args.timeout))`
`        end = time.time()`
` print("Total Time to Bulk Translate: ", (end-start))`
`...`
`self.write({'ok': True, 'content': content})`

I see that same on Chrome Web tools as well that the upload call takes 30 secs. Is this usual or definitely there is some unwanted delay happening.

Let me know if you need the complete scripts as well.

**Comment by guillaumekln** [comment]
`send_request` is asynchronous as it returns a [future](https://en.wikipedia.org/wiki/Futures_and_promises). You should include the time it takes to get the result out of the future variable in "Time Taken to Translate".

**Comment by mohammedayub44** [comment]
Sounds good. Since its asynchronous, have to wait to receive all the output from future. Controlling the batches from client helps. I will close this for now. Thanks for help.
