### ISSUE TITLE
Infer using the best model

### ISSUE THREAD

**Issue by hero007feng** [OpenNMT/OpenNMT-tf#485]
I have finished training a model, but I don't know which module OpenNMT-tf use in the inference, last module or best module if setting exporters: best. I want to use the best model in evaluation to test the performance in test data. Have any method to deal with this problem
Thanks!

**Comment by guillaumekln** [comment]
Are you running inference with the `infer` run type? If yes, it is using the latest checkpoint by default.

**Comment by hero007feng** [comment]
Can I choose to save the best checkpoint for the infer part? Thanks

**Comment by hero007feng** [comment]
> Are you running inference with the `infer` run type? If yes, it is using the latest checkpoint by default.

Yes, use command line `infer`

**Comment by guillaumekln** [comment]
The `infer` command uses checkpoint which are always generated at fixed intervals. You could setup evaluation to run at this interval to know which one is better.
