### ISSUE TITLE
visualize hidden state

### ISSUE THREAD

**Issue by hero007feng** [OpenNMT/OpenNMT-tf#489]
Hello. I want to visualize final hidden state with PCA. Would you mind telling me how to dump the value of resulting hidden state or visualization in TensorBoard. Thanks

**Comment by LLluoling** [comment]
I have the same problem -_-  can someone help me

**Comment by guillaumekln** [comment]
Sorry, I forgot to reply here.

In the latest version, you can use for example [`tf.print`](https://www.tensorflow.org/api_docs/python/tf/print) to dump the values of the tensors you are interested in.
