### ISSUE TITLE
NMT, What if we do not pass input for decoder?

### ISSUE THREAD

**Issue by guotong1988** [OpenNMT/OpenNMT-tf#494]
For transformer-based neural machine translation (NMT), take English-Chinese for example, we pass English for encoder and use decoder input(Chinese) attend to encoder output, then final output.

What if we do not pass input for decoder and consider it as a 'memory' model for translation. Is it possible and what will happen?

It seems decoder could be removed and there only exist encoder.

Thank you！

**Comment by guillaumekln** [comment]
Could you clarify what objective function you want to optimize?

**Comment by guotong1988** [comment]
Thank you!
If the decoder is removed, I think the objective function is like `cross_entropy(target, encoder_output)`

**Comment by guillaumekln** [comment]
That would work for sequence tagging but not for sequence to sequence tasks (such as NMT). It assumes that the source and target have the same length and are monotonically aligned.

**Comment by guotong1988** [comment]
Thank you very much.

**Comment by guotong1988** [comment]
Could I do translation task like text generation?
See:
https://github.com/salesforce/ctrl/blob/master/generation.py#L103
https://einstein.ai/presentations/ctrl.pdf

**Comment by guotong1988** [comment]
See https://datascience.stackexchange.com/questions/60258/nmt-what-if-we-do-not-pass-input-for-decoder

**Comment by guillaumekln** [comment]
> Could I do translation task like text generation?

You can train a [GPT-2 model](https://github.com/OpenNMT/OpenNMT-tf/blob/master/config/models/gpt_2.py) for example. Read the documentation if interested.

**Comment by guotong1988** [comment]
Thank you
