### ISSUE TITLE
About batch size and infer sequence length

### ISSUE THREAD

**Issue by Syrup274** [OpenNMT/OpenNMT-tf#496]
Hi, I am using the transformer model to train a translation-like task. And I have encountered the following questions:
1. According to the document, batch_size should be like this: 
>  (optional when batch_type=tokens) If not set, the training will search the largest
> possible batch size.

However, I found that for the transformer model , the type of batch size is always "token" and  batch size is always 3072, it seems to be fixed at transformer.py. In practise, what is the exact batch_size: 3072, or "the largest possible batch size" as is said?  How can I know the trained epoch by now?
2. I found the model sometimes tends to "brief" the sentence when infering(In my task, input and output are most likely to have the same length), i.e., when i input a sentence contains about 100 tokens, the pridiction always predict sentences less than 100. I've adjusted the maximum_features_length and maximum_labels_length, but it made no sense. Is there any "maximun_sequence_length" setting of the model?

Thanks!

**Comment by guillaumekln** [comment]
1. When using `auto_config`, the default batch size is 3072. The documentation should probably replace "not set" by "set to 0", in which case the training will start by searching an appropriate batch size.
2. Did you try with the `length_penalty` parameter? It is described in [this paper](https://arxiv.org/abs/1609.08144) if you haven't read it already.

**Comment by Syrup274** [comment]
Thanks!
And I have another question. It might be dumb since I may not familiar with the model.
I tried to train a model whose input and output are both Chinese sentences. I simply split the sentence with space so that each Chinese character corresponds to an English word. I wanna know is this kind of input adapt to the model? Will the model just use "Space tokenizer" to split the inputs?

**Comment by guillaumekln** [comment]
Yes. By default the text is split on spaces.

**Comment by Syrup274** [comment]
I use the same source input and target input, but found that "source_words/second" is always less than "target_words/second" (about 153000 vs 143200, batch_size 16144). What might be the reason of this?

**Comment by guillaumekln** [comment]
The target is prefixed with a special token `<s>`. It is included in the throughput reporting.

**Comment by Syrup274** [comment]
I found the folloing log during training:
> source_words/sec: 142800
> target_words/sec:164938
> global_step/sec: 5.36069
 
My batch_size is 3072, batch_type is 'token'(by default), i've trained the model on 10 GPUS. How can the model process about 10x more words per second? What's the gap between this? Does the batch_size refer to bs on 1 GPU and the '*_words/sec' is the overall processed words?

**Comment by guillaumekln** [comment]
In http://opennmt.net/OpenNMT-tf/training.html:

> The resulting graph is equivalent to train with batches N times larger, where N is the number of used GPUs.

The reported speed is the overall processed words.
