### ISSUE TITLE
Add BLEU evaluation metric

### ISSUE THREAD

**Issue by guillaumekln** [OpenNMT/OpenNMT-tf#5]
Ideally, this metric should be compatible with [`tf.metrics`](https://www.tensorflow.org/api_docs/python/tf/metrics) for a seamless integration in the training flow. Otherwise, we could rely on the `opennmt.utils.hook.SaveEvaluationPredictionHook` hook for external evaluation.

**Comment by gsoul** [comment]
I'm sure you're aware of it, so what's wrong with this implementation:
https://github.com/tensorflow/tensor2tensor/blob/a55c4cf57e509a0caaf2079b11ca3a46c9e17636/tensor2tensor/utils/bleu_hook.py

?

**Comment by guillaumekln** [comment]
Yes I saw that. Have to look at it more closely but ideally we would like a scorer that gives the same result as `multi-bleu.perl`.

That's why I think it may be better to have an external evaluation by saving the validation translation (which is already implemented) and run `multi-bleu.perl` on it.
