### ISSUE TITLE
Running Sentencepiece on English-Arabic data gives bad results

### ISSUE THREAD

**Issue by mohammedayub44** [OpenNMT/OpenNMT-tf#502]
Hi,

I'm using this repo to run English to Arabic model and running into issues when trying the sentence piece tokenization. I'm running all sentence piece steps outside of OpenNMT. In short, my predictions are turning out to be in English, however I want them to be in Arabic. 

I have detailed the issue with steps and files on the Forum ( [Issue 3085](http://forum.opennmt.net/t/running-sentence-piece-model-on-english-arabic-gives-bad-results/3085) ) as I don't feel its a bug in the pipeline. I'm okay to carry out the conversation either here on on the Forum.

Thanks !

Mohammed Ayub

**Comment by guillaumekln** [comment]
Hi,

Yes, let's continue on the forum.
