### ISSUE TITLE
Error while parsing onmt-main arguments

### ISSUE THREAD

**Issue by rikman122** [OpenNMT/OpenNMT-tf#504]
I noticed that with the new way of parsing the command arguments of the main program I get an error if I run it like the documentation said:

`onmt-main --model-type Transformer --config data.yml --auto_config train --with_eval`

I get this error:

`usage: onmt-main [-h] [-v] --config CONFIG [CONFIG ...] [--auto_config]
      [--model_type{GPT2Small,ListenAttendSpell,LstmCnnCrfTagger,LuongAttention,Transformer,TransformerBig}]
[--model MODEL] [--run_dir RUN_DIR] [--data_dir DATA_DIR]
[--checkpoint_path CHECKPOINT_PATH]
                 [--log_level {CRITICAL,ERROR,WARNING,INFO,DEBUG,NOTSET}]
                 [--seed SEED] [--gpu_allow_growth]
                 [--intra_op_parallelism_threads INTRA_OP_PARALLELISM_THREADS]
                 [--inter_op_parallelism_threads INTER_OP_PARALLELISM_THREADS]
                 [--mixed_precision]
                 {train,eval,infer,export,score,average_checkpoints,update_vocab}
                 ...
onmt-main: error: argument run: invalid choice: 'Transformer' (choose from 'train', 'eval', 'infer', 'export', 'score', 'average_checkpoints', 'update_vocab')
`
I tried different ways to run the script and found this way working:

`onmt-main --config data.yml --auto_config --model_type Transformer train --with_eval`

so looks like the --config flag must be placed at the start, other way it will not work.

I hope this helps to fix the issue. Thank you!

**Comment by guillaumekln** [comment]
There is actually a typo in your first command: it should be `--model_type` instead of `--model-type`.

**Comment by rikman122** [comment]
Oh! you are right. It's my bad! Sorry!

**Comment by guillaumekln** [comment]
But you are right that there is a issue with `--config` when it is the last option before the subcommand (e.g. `train`). As it accepts multiple arguments, it will consider the subcommand as one of its argument.
