### ISSUE TITLE
v2 Automatic SavedModel export on evaluation

### ISSUE THREAD

**Issue by lockder** [OpenNMT/OpenNMT-tf#505]
not sure if this is the place you want we open the issue.
I was using the "best" feature to get the best model on eval. This feature will be implemented in the future?

**Comment by guillaumekln** [comment]
Yes, it should be added.

Now we could even define "best" on any evaluation metrics (such as BLEU).

**Comment by lockder** [comment]
cool thanks @guillaumekln
