### ISSUE TITLE
Subword tokenisation spacer can mark the beginning of word

### ISSUE THREAD

**Issue by steremma** [OpenNMT/OpenNMT-tf#514]
Certain sequence noising operations need to retrieve a list of words from the raw list of subword tokens. For example:

* Decoding with word removal/reordering to produce noisy back-translations as in [Scaling BT paper](https://arxiv.org/abs/1808.09381)

* Word omission to support the new contrastive learning feature as in the [contrastive learning paper](https://www.aclweb.org/anthology/P19-1623.pdf)

* Presumably more features relying on word level noise might come up in the future

In these cases the user should specify some details for the sub-tokenisation process: 
1. What subword tokens was used? (`decoding_subword_token`)
2. Was that token a joiner or a spacer? (`decoding_subword_token_is_spacer`)

When the user specifies (explicitly or implicitly) a spacer, the framework assumes that the spacer symbol appears at the beginning of each word, similar to what SentencePiece does. However this does not have to be the case, the spacer could also appear at the end of each word - for example [this one does](https://github.com/kovalevfm/SubTokenizer). If that extra sub-tokenisation flexibility is desired, we can add this configuration parameter. A sample implementation could look like [this](https://github.com/steremma/OpenNMT-tf/commit/d109af49911431e424b28def575fb94f07bfec47).

I realise that most user's rely on standard tools that are covered by the current implementation. If there is a user base for which the extra flexibility is desired, I can submit a PR that reads this option from the YAML.

**Comment by guillaumekln** [comment]
That makes sense. But we could probably improve the current implementation to support both modes instead of adding a new option.

Can you check the pull request above and see if the newly added tests cover your use case?

**Comment by steremma** [comment]
Update: The tests seem to word at a unit level. I am having some trouble running the full fine-tuning pipeline but this is probably related to the 2.0 transition. I did rollback to 1.25.1 and cherry-picked your commit,, everything works fine there!

Let me know if I should I make this 2.0 thing a separate issue - the use-case is fine-tuning (say with contrastive learning) models developed in V1 using V2. Here is the stacktrace:

```
Traceback (most recent call last):
  File "/usr/local/bin/onmt-main", line 10, in <module>
    sys.exit(main())
  File "/mnt/work/home/estergiadis/OpenNMT-tf/opennmt/bin/main.py", line 189, in main
    checkpoint_path=args.checkpoint_path)
  File "/mnt/work/home/estergiadis/OpenNMT-tf/opennmt/runner.py", line 167, in train
    evaluator = evaluation.Evaluator.from_config(model, config)
  File "/mnt/work/home/estergiadis/OpenNMT-tf/opennmt/evaluation.py", line 150, in from_config
    eval_dir=os.path.join(config["model_dir"], "eval"))
  File "/mnt/work/home/estergiadis/OpenNMT-tf/opennmt/evaluation.py", line 73, in __init__
    summaries = misc.read_summaries(eval_dir)
  File "/mnt/work/home/estergiadis/OpenNMT-tf/opennmt/utils/misc.py", line 254, in read_summaries
    tensor_proto.SerializeToString(), tf.as_dtype(tensor_proto.dtype))
  File "/home/estergiadis/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/dtypes.py", line 721, in as_dtype
    (type_value,))
TypeError: Cannot convert value 0 to a TensorFlow DType.
```

I isolated the problem in `utils.misc.read_summaries` [on this line](https://github.com/OpenNMT/OpenNMT-tf/blob/e38d68615ecf7f508ac1731621e10a18e30e8f7d/opennmt/utils/misc.py#L252)

It seems that the `value` object does not have a `tensor` field, so `value.tensor` is None and the cast fails - here is a print of some `value` objects:

```
value: tag: "words_per_sec/source"
simple_value: 63206.94140625

value: tag: "loss"
simple_value: 2.4506947994232178
```

The events files were generated a while ago with a much older version (around 1.20 I think).

**Comment by guillaumekln** [comment]
Thanks for testing!

The error is indeed a separate issue. The old event files should be deleted before running a v2 training.
