### ISSUE TITLE
can we output alignment of ParallelInputter?

### ISSUE THREAD

**Issue by WangYongzhao** [OpenNMT/OpenNMT-tf#529]
I was using the ParallelInputter and transformer, and I found that we can't output the alignment,
  

> (optional) For compatible models, also output the alignments (can be: null, hard, soft,default: null).
>   with_alignments: null

according the turtorial, want to know which part is not supported, and how to get the alignment?

my model is simliar as https://github.com/OpenNMT/OpenNMT-tf/blob/master/config/models/multi_source_transformer.py

**Comment by guillaumekln** [comment]
The alignment information is not returned in this case because it's unclear what to do: return alignment for first source? for second? for both?

What do you suggest?

**Comment by WangYongzhao** [comment]
for my specific case, i want to use alignment for first source.

for generic cases, maybe can add parameter to control output what alignments.
