### ISSUE TITLE
OpenNMT-tf inference output option

### ISSUE THREAD

**Issue by getao** [OpenNMT/OpenNMT-tf#53]
Hello. I wonder if I can output the attention matrix during inference because I want to replace unk tokens with the highest attention token in the source. Or, is there any other way to deal with unk tokens?

Thank you.

**Comment by guillaumekln** [comment]
There is currently a limitation in TensorFlow that prevents exposing the alignment history after decoding. See #2.

You could either:

* rely on an external alignment tool
* or use a subword tokenization like BPE or sentencepiece.
