### ISSUE TITLE
Support for non-text seq2seq

### ISSUE THREAD

**Issue by mattc-eostar** [OpenNMT/OpenNMT-tf#530]
Is there a plan to allow for either Custom sequence sources or other types of sources like samples of audio or frames of video?

I saw the vector source in the documentation, would I just pass the array of audio samples to that to create the proper input?

I know that CTC models exist that handle audio to transcribed text. But, I would guess that a seq2seq model would work as well.

I am trying to go from sequence of audio commands -> sequence of text commands.

**Comment by guillaumekln** [comment]
If you can represent your audio inputs as 2D vectors (time x dimension), you could indeed use the vector inputs as described in the documentation: http://opennmt.net/OpenNMT-tf/data.html#vectors

It is designed to pass arbitrary sequences of vectors to the encoder.

**Comment by mattc-eostar** [comment]
Great! Thank you. I would probably end up extracting 13 or so MFCC features from the audio which would fit nicely into a matrix. Can't wait for TFLite to support the ops needed to get a seq2seq model onto a device.
