### ISSUE TITLE
Long sentences training 

### ISSUE THREAD

**Issue by Syrup274** [OpenNMT/OpenNMT-tf#539]
I want to train and infer on a dataset of which the sentences are extra long so I need to split
the sentence into short pieces. I think the piece should be as long as possible for enough context information. What's the max_seq_len of features and labels for the model theoretically？
When setting params, are [maximum_features_length,  maximum_labels_length ,maximum_decoding_length] all params to set? 
Thanks.

**Comment by guillaumekln** [comment]
> What's the max_seq_len of features and labels for the model theoretically？

I don't think there is hard theoretical limit. The biggest issue will be memory usage.

> When setting params, are [maximum_features_length, maximum_labels_length ,maximum_decoding_length] all params to set?

Yes.

* `maximum_features_length` and `maximum_labels_length` filter out long sentences during training
* `maximum_decoding_length` is the maximum sequence length generated during inference
