### ISSUE TITLE
The model LanguageModelInputter requires a tokenizer to be initialized.

### ISSUE THREAD

**Issue by kanishkkalra11** [OpenNMT/OpenNMT-tf#546]
Any LanguageModelInputter object calls textinputter which requires the tokenizer.

**Comment by guillaumekln** [comment]
Can you clarify what is the issue you are facing?

`LanguageModelInputter` requires a vocabulary to be initialized but does not require configuring a tokenizer. It defaults to a basic tokenization on spaces.

**Comment by kanishkkalra11** [comment]
![Capture](https://user-images.githubusercontent.com/44034028/68527641-2813cb00-030f-11ea-8c2d-2d01165c1e14.JPG)

**Comment by guillaumekln** [comment]
You should at least initialize the inputter with a vocabulary:

```python
inputter = onmt.models.LanguageModelInputter(embedding_size=512)
inputter.initialize(dict(vocabulary="/path/to/the/tokens/vocabulary.txt"))
dataset = inputter.make_training_dataset(...)
```

See also the documentation about the vocabulary format: http://opennmt.net/OpenNMT-tf/data.html#vocabulary

**Comment by kanishkkalra11** [comment]
Resolved.
Thanks!
