### ISSUE TITLE
Does tf-1.x version support model ensemble decoding?

### ISSUE THREAD

**Issue by SefaZeng** [OpenNMT/OpenNMT-tf#550]
I do not find any code for ensemble in the tf-1.x version.But I find ensemble.py in the pytorch version.
So, does tf version still not implement this feature?

**Comment by guillaumekln** [comment]
No, it does not implement ensemble decoding. You could use checkpoint averaging which have a similar effect.

**Comment by SefaZeng** [comment]
> No, it does not implement ensemble decoding. You could use checkpoint averaging which have a similar effect.

But average means the models must have the same architecture, right?

**Comment by guillaumekln** [comment]
Yes, that's correct.
