### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by halidziya** [OpenNMT/OpenNMT-tf#558]
Hi, 

How important is the function of tensorflow-addons ? It is not supporting Windows currently. 

https://github.com/OpenNMT/OpenNMT-tf/blob/ae20bc17a7e997acc7f097daf15be5c9cc75f96e/opennmt/models/catalog.py#L4

https://pypi.org/project/OpenNMT-tf/#files
https://pypi.org/project/tensorflow-addons/#files

**Comment by guillaumekln** [comment]
We use it in several places ranging from beam search decoding to RNN decoder with attention. You probably want to track this issue: https://github.com/tensorflow/addons/issues/173

**Comment by halidziya** [comment]
Tensorflow-addons is now supporting Windows

**Comment by guillaumekln** [comment]
Yes, the next OpenNMT-tf release will depend on the latest TensorFlow Addons version.
