### ISSUE TITLE
Relative Positional Encoding

### ISSUE THREAD

**Issue by atebbifakhr** [OpenNMT/OpenNMT-tf#559]
Hi,

Instead of Sinusoidal Positional Encoding, Relative Positional Encoding is becoming dominant in Transformer models. I would like to ask for adding this feature to the project.

**Comment by guillaumekln** [comment]
Hi,

It's a good candidate. I will look to get this in.

**Comment by atebbifakhr** [comment]
Thanks a lot!

**Comment by atebbifakhr** [comment]
Sorry for reopening this issue again,

I was referring to Relative Positional Embedding, which is proposed in Transformer-XL paper: https://arxiv.org/pdf/1901.02860.pdf

**Comment by guillaumekln** [comment]
Ah ok, I was pretty sure you meant this one https://arxiv.org/pdf/1901.02860.pdf.

I would be happy to accept a PR for what is proposed in Transformer-XL. I have no plan to work on this in the short term.
