### ISSUE TITLE
segment embedding support

### ISSUE THREAD

**Issue by WangYongzhao** [OpenNMT/OpenNMT-tf#567]
did opennmt-tf support segment embedding of bert? or work around it by using existing API?

**Comment by guillaumekln** [comment]
Do you want to concatenate a BERT embedding to the encoder representation? If not, can you describe a bit more what you want to do with this embedding?

**Comment by WangYongzhao** [comment]
I want to train a classifier from scratch (not use pretrained bert model), used for relation of sentence A and B, so also want to have segment embedding in my model.


![image](https://user-images.githubusercontent.com/19544350/70309062-9b91f500-1847-11ea-8b84-9baee3f1a94a.png)

**Comment by guillaumekln** [comment]
It looks like the sentence embedding is added to each word embedding. In that case, it should be possible to load the embeddings with a [`SequenceRecordInputter`](http://opennmt.net/OpenNMT-tf/package/opennmt.inputters.SequenceRecordInputter.html) and add them to the main word embeddings with a [`ParallelInputter`](http://opennmt.net/OpenNMT-tf/package/opennmt.inputters.ParallelInputter.html), e.g.:

```python
ParallelInputter([<word_embedder>, <sequence_record_inputter>], reducer=opennmt.layers.SumReducer())
```

**Comment by WangYongzhao** [comment]
Yes, it's added. And any benefit use sequence_record_inputter? 

my ituition is like below, and the 2nd vocbulary only contains A and B.

```
opennmt.inputters.ParallelInputter(
    [<word_embedder>, <word_embedder>],
    reducer=opennmt.layers.SumReducer())
```

**Comment by guillaumekln** [comment]
SequenceRecordInputter can be used to load external vectors, e.g. "segment embedding" produced by BERT. Isn't it what you want to achieve?

**Comment by WangYongzhao** [comment]
thanks, what i want is the architecture, not the pretrained embedding.
