### ISSUE TITLE
Error while running the exported model 

### ISSUE THREAD

**Issue by sriram-c** [OpenNMT/OpenNMT-tf#568]
Hi,

I was trying to run the example given [https://github.com/OpenNMT/OpenNMT-tf/tree/master/examples/serving/python](url).

I am getting the following error.

> Source: I am going.
Traceback (most recent call last):
  File "ende_client.py", line 66, in <module>
    main()
  File "ende_client.py", line 60, in main
    output = translator.translate([text])
  File "ende_client.py", line 22, in translate
    return self._postprocess(outputs)
  File "ende_client.py", line 47, in _postprocess
    texts.append(self._tokenizer.detokenize(tokens))
TypeError: detokenize(): incompatible function arguments. The following argument types are supported:
    1. (self: pyonmttok.Tokenizer, tokens: list, features: object = None) -> str

> Invoked with: <pyonmttok.Tokenizer object at 0x147d10d0d538>, array([b'\xe2\x96\x81Ich', b'\xe2\x96\x81gehe', b'.'], dtype=object)
> WARNING:tensorflow:Unresolved object in checkpoint: (root).examples_inputter.features_inputter.ids_to_tokens._initializer
> WARNING:tensorflow:Unresolved object in checkpoint: (root).examples_inputter.labels_inputter.ids_to_tokens._initializer
> WARNING:tensorflow:A checkpoint was restored (e.g. tf.train.Checkpoint.restore or tf.keras.Model.load_weights) but not all checkpointed values were used. See above for specific issues. Use expect_partial() on the load status object, e.g. tf.train.Checkpoint.restore(...).expect_partial(), to silence these warnings, or use assert_consumed() to make the check explicit. See https://www.tensorflow.org/alpha/guide/checkpoints#loading_mechanics for details.
> 

I have the updated version of pyonmttok.

Thanks,
Sriram

**Comment by guillaumekln** [comment]
Thanks for reporting. It will get fixed by the PR linked above.
