### ISSUE TITLE
Do you know Radam?

### ISSUE THREAD

**Issue by lockder** [OpenNMT/OpenNMT-tf#572]
https://medium.com/@lessw/new-state-of-the-art-ai-optimizer-rectified-adam-radam-5d854730807b

https://www.tensorflow.org/addons/api_docs/python/tfa/optimizers/RectifiedAdam

not sure if could be posible to add this optimizer to opennmt ?

**Comment by guillaumekln** [comment]
You can use any optimizers defined in `tfa.optimizers`. Just use their name in the config:

```yaml
params:
  optimizer: RectifiedAdam
```

**Comment by lockder** [comment]
wow amazing thanks

**Comment by lockder** [comment]
sorry I reopen again but I have a doubt, looking in the tensorflow page they recommend to do something like

radam = tfa.optimizers.RectifiedAdam()
ranger = tfa.optimizers.Lookahead(radam, sync_period=6, slow_step_size=0.5)

so it means I have to use both optimizers first RectifiedAdam then use that as param for Lookahead.
its this posible?

**Comment by guillaumekln** [comment]
This is not possible at the moment.

But *do* they recommend it? It seems they are just mentioning that is possible to combine both optimizers to build the "Ranger" optimizer (which is not RAdam).

**Comment by guillaumekln** [comment]
Actually, you could do it by defining a custom model and overriding the [`get_optimizer`](http://opennmt.net/OpenNMT-tf/package/opennmt.models.Model.html#opennmt.models.Model.get_optimizer) method. But the YAML configuration file can not express this combination.

**Comment by lockder** [comment]
on the first article I added they say it gives better results than adam alone. So I started to look info about and since I wondered if could be a quick win for opennmt

**Comment by lockder** [comment]
the last lines of the article says:

Update — I find that by combining RAdam + LookAhead (Hinton, July 19), an even better optimizer (Ranger) is created as each address different aspects of training optimization. RAdam stabilizes early training, LookAhead stabilizes further training, exploration and convergence.
Details here: https://medium.com/@lessw/new-deep-learning-optimizer-ranger-synergistic-combination-of-radam-lookahead-for-the-best-of-2dc83f79a48d

**Comment by lockder** [comment]
I can do it for my self but I believe that if its improve the training in a generic way then wouldn't be awesome also all people using opennmt could aso use it? it's up to you if you believe worth the time to take a look on this :)

**Comment by guillaumekln** [comment]
Sure, but we may need to test first the impact on a task we care about, e.g. NMT with Transformer.

The configuration should also be relatively easy for people interested in this optimizer. With the next version of TensorFlow Addons (this [commit](https://github.com/tensorflow/addons/commit/2e9ea8be42e1369cea314b03b78124f981e3d0c8) is needed), one could do something like:

```python
import tensorflow_addons as tfa
import opennmt

class TransformerWithRanger(opennmt.models.TransformerBase):

  def get_optimizer(self):
    radam = tfa.optimizers.RectifiedAdam()
    ranger = tfa.optimizers.Lookahead(radam, sync_period=6, slow_step_size=0.5)
    return ranger

model = TransformerWithRanger
```

then pass the file to the `--model` command line option.

**Comment by lockder** [comment]
great :)

**Comment by guillaumekln** [comment]
Let's close this issue. The initial question was about RectifiedAdam which can already be used in OpenNMT-tf.
