### ISSUE TITLE
Bug in "onmt-ark-to-records" code

### ISSUE THREAD

**Issue by hseelawi** [OpenNMT/OpenNMT-tf#576]
I have found a small bug in the code line referenced below. It causes the script to terminate with a `TypeError: data type not understood`. Just for the sake of completeness, this is caused by the fact that numpy doesn't understand the object `tf.float32`. I changed that to `float` and it worked as it was supposed to. I can create a PR for this, but I suppose it is too trivial to do so and claim a contribution, unless you want me to.

https://github.com/OpenNMT/OpenNMT-tf/blob/5809c293d7bc65d923274cfd56b3339fc4107af6/opennmt/bin/ark_to_records.py#L46

**Comment by guillaumekln** [comment]
Thanks for reporting. The change referenced above should fix this.
