### ISSUE TITLE
Disable beam search during inference

### ISSUE THREAD

**Issue by sandeep-krishnamurthy** [OpenNMT/OpenNMT-tf#580]
Hello, Thanks for the great work.
I am trying to serving the pre-trained model using TF-Serving on Google Cloud. Unfortunately, I cannot use a custom docker container in Google Cloud Inference service. So I can use only stock TF and TFServing.
Hence, I cannot use custom ops (for beam search). How do I dis-able using beam search for inference when using a pre-trained model? Can I pass some config?
@guillaumekln - Can you please help?
I cam here from your SO answer here - https://stackoverflow.com/questions/58479897/tensorflow-serving-not-found-op-type-not-registered-gathertree

**Comment by sandeep-krishnamurthy** [comment]
I am currently facing below error as expected because stock TF and TFServing donot have the custom op "Addons>GatherTree"
```
[evhttp_server.cc : 238] NET_LOG: Entering the event loop ...
2020-01-02 01:55:21.510903: E external/org_tensorflow/tensorflow/core/grappler/optimizers/meta_optimizer.cc:533] fu
nction_optimizer failed: Not found: Op type not registered 'Addons>GatherTree' in binary running on 324f0434210c. M
ake sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a sav
ed graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing th
e graph, as contrib ops are lazily registered when the module is first accessed.
```

**Comment by guillaumekln** [comment]
Hi,

The solution is in the StackOverflow answer. You should pass this configuration when [exporting the model](http://opennmt.net/OpenNMT-tf/serving.html#manual-export):

```yaml
params:
  beam_width: 1
```

**Comment by sandeep-krishnamurthy** [comment]
Thanks @guillaumekln  for the response. I want to use a pre-trained model and not train my own model. How do I re-export a pre-trained Transformer model for en-de ?

**Comment by guillaumekln** [comment]
You could download the [training checkpoint](https://s3.amazonaws.com/opennmt-models/averaged-ende-ckpt500k.tar.gz) and re-export it. Let me know if you encounter issues doing that.

**Comment by sandeep-krishnamurthy** [comment]
Thanks @guillaumekln for the suggestion. I got the checkpoint, but I was unable to match the right config file and parameters like model type, data_dir etc. Can you please share any references on how to re-export with the checkpoint,  config and other params etc?

**Comment by guillaumekln** [comment]
Can you try this alternative pre-trained model with TFServing: https://opennmt-models.s3.amazonaws.com/averaged-ende-export500k-v2-beam1.tar.gz? It was exported with TensorFlow 2.0.

**Comment by guillaumekln** [comment]
I think this issue can be closed. The pretrained model shared above should not contain beam search inference.
