### ISSUE TITLE
2.x hovorod status

### ISSUE THREAD

**Issue by JoshuaPostel** [OpenNMT/OpenNMT-tf#581]
Opening this issue to express interest in and request priority/status updates for hovorod support in OpenNMT-tf 2.x.

From the [2.0.0 release notes](https://github.com/OpenNMT/OpenNMT-tf/releases/tag/v2.0.0): 
> Some features available in OpenNMT-tf v1 were removed or are temporarily missing in this v2 release. If you relied on some of them, please open an issue to track future support or find workarounds.
> * Asynchronous distributed training
> * Horovod integration
> ...

**Comment by JoshuaPostel** [comment]
My use case (`OpenNMT-tf==1.25.0`, machine translation) has heavily utilized horovod for distributed training.  Many thanks for maintaining and improving this library.  I do not have experience integrating hovorod with tensorflow, but depending on the expected complexity (using #322 as a reference) I am willing to lend a hand where I can.

**Comment by guillaumekln** [comment]
Yes, multi worker training should be added back at some point. Unfortunately I don't have a specific timeline for it as we don't have such need internally (for now at least). It would be great if someone could look into it.

Maybe a first step would be to support [TensorFlow own distrubuted training](https://www.tensorflow.org/api_docs/python/tf/distribute/experimental/MultiWorkerMirroredStrategy?version=stable). It's possible that the training code should be adapted for efficiency.

**Comment by JoshuaPostel** [comment]
Looks like I will not be able to dedicate a significant amount of time to this.  Unfortunately, my workspace is switching to a custom implementation of the transformer.

**Comment by Morizeyao** [comment]
I'm also trying to implement distributed support for opennmt-tf 2, preferably horovod.

Is there any suggestions how I can do this?

Thank you!

**Comment by guillaumekln** [comment]
The current training code assumes to work with TensorFlow's distribution strategies. I read that Horovod does not support them at the moment (cf. https://github.com/horovod/horovod/issues/935).

I will first refactor the training code to easily add other ways to train models (e.g. by extending a base class). I will let you know.

**Comment by guillaumekln** [comment]
@Morizeyao If you are looking to implement this, see the revisited [`Trainer`](https://github.com/OpenNMT/OpenNMT-tf/blob/master/opennmt/training.py) class. It can now be extended to implement other training logic.

Custom trainers should minimally implement a `_steps` method that returns a generator over training step. See for example the [`BasicTrainer`](https://github.com/OpenNMT/OpenNMT-tf/blob/d7db4b1b9a6c9577ca3a09c4241cdd9db58b31bc/opennmt/training.py#L177-L195) class. The base class handles the common logic related to checkpoints, logging, and evaluation.

**Comment by hdubey** [comment]
I am interested to see horovod intergated with TF 2.0 distributed framework, when will it be available?

**Comment by guillaumekln** [comment]
Are you interested in contributing?

**Comment by guillaumekln** [comment]
Note sure if any of you are still around, but if someone could try #639 and provide feedback, that would be helpful.
