### ISSUE TITLE
About install opennmt-tf

### ISSUE THREAD

**Issue by BUCTwangkun** [OpenNMT/OpenNMT-tf#610]
Hi,
My project need tensorflow<2.0, so I install tensorflow==1.9.0

But when I run "pip install OpenNMT-tf", it uninstalled tensorflow==1.9.0 and installed tensorflow==2.1.0. 

So How can I control the TensorFlow‘s version when I run "pip install OpenNMT-tf"？

Thanks~

**Comment by guillaumekln** [comment]
Hi,

OpenNMT-tf 2.x is not compatible with TensorFlow 1.x. You should install OpenNMT-tf 1.x instead. Try for example:

```bash
pip install OpenNMT-tf==1.*
```

**Comment by BUCTwangkun** [comment]
Thank you for your reply~

Where can I find relationships between tensorflow and OpenNMT-tf ? Just like tensorflow1.9 -> OpenNMT-tf 1.9.

**Comment by guillaumekln** [comment]
OpenNMT-tf 1.25 is compatible with TensorFlow 1.4 to 1.15. You can grab this version.
