### ISSUE TITLE
Is the last release compatible with Tensorflow  2.0.0?

### ISSUE THREAD

**Issue by atebbifakhr** [OpenNMT/OpenNMT-tf#616]

**Comment by guillaumekln** [comment]
We require TensorFlow 2.1 since the OpenNMT-tf version 2.5.0. You can find the exact requirement in the `setup.py` file:

https://github.com/OpenNMT/OpenNMT-tf/blob/v2.7.0/setup.py#L50

**Comment by atebbifakhr** [comment]
Thanks,
