### ISSUE TITLE
GPT2 training reports on source and target words

### ISSUE THREAD

**Issue by jsenellart** [OpenNMT/OpenNMT-tf#640]
When training a language mode (GPT2) model - we can see the following logs:
```
INFO:tensorflow:Evaluation result for step 20000: perplexity = 99.456184 ; loss = 4.599717
INFO:tensorflow:Step = 20100 ; steps/s = 2.09, source words/s = 6382, target words/s = 6382 ; Learning rate = 0.000250 ; Loss = 3.851096
```

There is no reason to see source & target word reports. If I correctly understand the code, `source` and `target` are defined as words counters in `_accumulate_gradients_on_replica` function in training.py regardless of training type. Can you give an hint on how/where we could correct this?

Thanks

**Comment by guillaumekln** [comment]
Right, good find. A quick fix would be to add a condition when declaring the target counter, for example:

```python
if not self._model.unsupervised:
  self._update_words_counter("target", target)
```
