### ISSUE TITLE
Whether support bpe data?

### ISSUE THREAD

**Issue by lidongxing** [OpenNMT/OpenNMT-tf#646]
I used bpe data of wmt17 with cpu successfully. But with Gpu, some errors occurs.

E tensorflow/stream_executor/cuda/cuda_blas.cc:366] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
E tensorflow/stream_executor/cuda/cuda_dnn.cc:385] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR

batch_size:2,16,32,64, all have been test, but the errors are the same.
Thank you very much.

**Comment by guillaumekln** [comment]
Can you post the full training log?

**Comment by lidongxing** [comment]
@guillaumekln 
yaml file:
![image](https://user-images.githubusercontent.com/16410042/78788256-1cbbed00-79de-11ea-9e21-c8e4a7721473.png)
error log:
[error.log](https://github.com/OpenNMT/OpenNMT-tf/files/4450727/error.log)

**Comment by guillaumekln** [comment]
This is possibly hiding a out of memory error. What is the size of your vocabulary?

Also make sure that you have correctly installed CUDA 10.1. Maybe it is loading `cublas` from another CUDA version.

**Comment by lidongxing** [comment]
@guillaumekln 
two independent 40000 bpe words. 
![image](https://user-images.githubusercontent.com/16410042/78791522-905ff900-79e2-11ea-99c9-64dd1f068486.png)
I installed many cuda versions. But the environment has been modified.

**Comment by lidongxing** [comment]
Also, I used the data you given, and its can run successfully.

**Comment by guillaumekln** [comment]
Did you also install CUDA 10.2? You could have overridden the cuBLAS library from CUDA 10.1.
