### ISSUE TITLE
Error occurs for multi source transformer training

### ISSUE THREAD

**Issue by yukiyakiZ** [OpenNMT/OpenNMT-tf#649]
I tried to use multi_source_transformer and encountered with a bug said 
`Error occurred when finalizing GeneratorDataset iterator` right after the training start. It seems that it is a bug caused by out of memory. But I even set the batch size to 1... Could you help me with what I could do for this? Thanks!
The .yml file I used is as below.

`model_dir: run/

data:
    train_features_file:
     - data/train.txt_w
     - data/train.gls_p
    train_labels_file: data/train.gls_w
    eval_features_file:
     - data/valid.txt_w
     - data/valid.gls_p
    eval_labels_file: data/valid.gls_w
    source_1_vocabulary: data/src-vocab.txt_w
    source_2_vocabulary: data/src-vocab.gls_p
    target_vocabulary: data/tgt-vocab.gls_w

train:
    batch_size: 1
    effective_batch_size: null
    maximum_features_length: [400, 400]
    maximum_labels_length: 400
    save_checkpoints_steps: 100
eval:
    external_evaluators: bleu
    export_on_best: bleu
    early_stopping:
        metric: bleu
        min_improvement: 0.05
        steps: 4
infer:
    batch_size: 32`

**Comment by guillaumekln** [comment]
Couple questions:

1. How much GPU memory do you have?
2. What is your vocabulary size?
3. Did you try reducing the maximum lengths to smaller values?

**Comment by yukiyakiZ** [comment]
Thanks for your reply.
Below is the GPU information. I use 4 GPU and each of them has 10G memory.
![image](https://user-images.githubusercontent.com/43117502/79577442-bba5b080-8092-11ea-8eeb-a3489e35a232.png)

The vocabulary sizes for all the source and target are less than 2000. My maximum sentence length is larger than 300...so I guess I have to use that maximum lengths. 

The command line I use is:
`$ onmt-main --config data.yml --auto_config --model ../../config/models/multi_source_transformer.py train --with_eval --num_gpus 4`

I also attached an error log when I trained for one time, where I use batch size of 512, but the error is exactly the same as batch_size = 1.
[train_log.txt](https://github.com/OpenNMT/OpenNMT-tf/files/4493434/train_log.txt)

Thanks so much!

**Comment by guillaumekln** [comment]
Sorry for not getting back to you earlier.

I checked again a dual source Transformer training on a single 6GB GPU but did not find specific issues. I believe your maximum sequence lengths are too long for a dual source Transformer. You probably need to reduce them or the model size.

Let me close this issue as it does not appear there is a bug, but feel free to reopen if you still face the problem after trying other things.
