### ISSUE TITLE
ERROR: Command errored out with exit status 1:

### ISSUE THREAD

**Issue by git31** [OpenNMT/OpenNMT-tf#653]
### When installing OpenNMT-tf, I encountered some errors:

> 
> Building wheels for collected packages: mecab-python3
>   Building wheel for mecab-python3 (setup.py) ... error
>   ERROR: Command errored out with exit status 1:
>    command: 'D:\ProgramFiles\Anaconda3\envs\opennmt\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\nlp\\AppData\\Local\\Temp\\pip-install-nw0zl599\\mecab-python3\\setup.py'"'"'; __file__='"'"'C:\\Users\\nlp\\AppData\\Local\\Temp\\pip-install-nw0zl599\\mecab-python3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\nlp\AppData\Local\Temp\pip-wheel-fue90fc1'
>        cwd: C:\Users\nlp\AppData\Local\Temp\pip-install-nw0zl599\mecab-python3\
>   Complete output (9 lines):
>   running bdist_wheel
>   running build
>   running build_py
>   creating build
>   creating build\lib.win-amd64-3.7
>   creating build\lib.win-amd64-3.7\MeCab
>   copying src\MeCab\__init__.py -> build\lib.win-amd64-3.7\MeCab
>   running build_ext
>   error: [WinError 2] 系统找不到指定的文件。【It means the system cannot find the specific file.】
>   
> ---------------------------------------
>   ERROR: Failed building wheel for mecab-python3
>   Running setup.py clean for mecab-python3
> Failed to build mecab-python3
> Installing collected packages: mecab-python3, pywin32, portalocker, sacrebleu, OpenNMT-tf
>     Running setup.py install for mecab-python3 ... error
>     ERROR: Command errored out with exit status 1:
>      command: 'D:\ProgramFiles\Anaconda3\envs\opennmt\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\nlp\\AppData\\Local\\Temp\\pip-install-nw0zl599\\mecab-python3\\setup.py'"'"'; __file__='"'"'C:\\Users\\nlp\\AppData\\Local\\Temp\\pip-install-nw0zl599\\mecab-python3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\nlp\AppData\Local\Temp\pip-record-i5eou2d2\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\ProgramFiles\Anaconda3\envs\opennmt\Include\mecab-python3'
>          cwd: C:\Users\nlp\AppData\Local\Temp\pip-install-nw0zl599\mecab-python3\
>     Complete output (9 lines):
>     running install
>     running build
>     running build_py
>     creating build
>     creating build\lib.win-amd64-3.7
>     creating build\lib.win-amd64-3.7\MeCab
>     copying src\MeCab\__init__.py -> build\lib.win-amd64-3.7\MeCab
>     running build_ext
>     error: [WinError 2] 系统找不到指定的文件。【It means the system cannot find the specific file.】
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: 'D:\ProgramFiles\Anaconda3\envs\opennmt\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\nlp\\AppData\\Local\\Temp\\pip-install-nw0zl599\\mecab-python3\\setup.py'"'"'; __file__='"'"'C:\\Users\\nlp\\AppData\\Local\\Temp\\pip-install-nw0zl599\\mecab-python3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\nlp\AppData\Local\Temp\pip-record-i5eou2d2\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\ProgramFiles\Anaconda3\envs\opennmt\Include\mecab-python3' Check the logs for full command output.
> 

---------------------------------------
**Environments:**
- Windows 10
- anaconda
- python3.6
- tensorflow2.1(automatically installed when installing OpenNMT-tf)

**Comment by guillaumekln** [comment]
This is a known error on Windows. Recent versions of `sacrebleu` require `mecab-python3` which does not provide packages for Windows. See https://github.com/mjpost/sacrebleu/issues/74 for more information.

Workaround is to install an older version of `sacrebleu` before OpenNMT-tf:

```text
pip install sacrebleu==1.4.4
pip install OpenNMT-tf
```

**Comment by guillaumekln** [comment]
I also pushed a new OpenNMT-tf version (2.9.2) which pins `sacrebleu` to this version. There should no longer be an error on install.
