### ISSUE TITLE
missing "decoder/output_layer/kernel" in onmt-main checkpoint

### ISSUE THREAD

**Issue by charleybian** [OpenNMT/OpenNMT-tf#656]
Hi, I trained a Transformer model with:
`onmt-main --model config/model.py --config config/config.yaml train --with_eval --num_gpus 2`

model.py is simple:
```
import opennmt


class CustomTransformer(opennmt.models.Transformer):
    def __init__(self):
        super().__init__(
            source_inputter=opennmt.inputters.WordEmbedder(embedding_size=256),
            target_inputter=opennmt.inputters.WordEmbedder(embedding_size=256),
            num_layers=3,
            num_units=256,
            num_heads=4,
            ffn_inner_dim=1024,
            dropout=0.1,
            attention_dropout=0.1,
            ffn_dropout=0.1,
            share_embeddings=opennmt.models.EmbeddingsSharingLevel.ALL)

model = CustomTransformer
```

I want to get the weights in the checkpoint for future use, and most weights are found, including "decoder/output_layer/bias", but "decoder/output_layer/kernel" is missing.

I use the tensorflow [tool](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/inspect_checkpoint.py) to parse the weights, or simply:
```
from tensorflow.python.training import py_checkpoint_reader


reader = py_checkpoint_reader.NewCheckpointReader('output/ckpt-10000')
for k, v in reader.get_variable_to_shape_map().items():
    print(k, v)
```

Also, official onmt library [example](https://github.com/OpenNMT/OpenNMT-tf/blob/master/examples/library/custom_transformer_training.py) failed to "translate(predict)" after loading the checkpoint, but `onmt-main infer` works, so I am confused. I tested with OpenNMT-tf 2.9.2 and 2.8.1 on Debian.

**Q: How can I make "decoder/output_layer/kernel" visible in the checkpoint?**

**Comment by guillaumekln** [comment]
Hi,

This is because you configured embeddings sharing to `opennmt.models.EmbeddingsSharingLevel.ALL`. So the output layer kernel is actually the embedding weight.

**Comment by charleybian** [comment]
> Hi,
> 
> This is because you configured embeddings sharing to `opennmt.models.EmbeddingsSharingLevel.ALL`. So the output layer kernel is actually the embedding weight.

I see. Thanks for your quick reply.
