### ISSUE TITLE
No Training steps are executed (Runtime Error)

### ISSUE THREAD

**Issue by Sanaj2060** [OpenNMT/OpenNMT-tf#657]
`RuntimeError: No training steps were executed. This usually means the training file is empty or all examples were filtered out. For the latter, verify that the maximum_*_length values are consistent with your data.`

I have generated src-vocab.txt and tgt-vocab.txt using `onmt-build-vocab`. And I have all the required files and the data.yml is configured correctly. Help me with the error.

**Comment by guillaumekln** [comment]
The message is clear. The training did not get enough data to run a single step.

Can you check for that? If you want more help you need to post more information about your data, configuration, command line, etc.

**Comment by Sanaj2060** [comment]
**Ok it's solved.** 
The training data has more than 10000 words but the problem was with data preprocessing.
