### ISSUE TITLE
Running TF -1 exported models in TF-2 

### ISSUE THREAD

**Issue by sriram-c** [OpenNMT/OpenNMT-tf#666]
Hi,

When running the exported models in open nmt TF-1.14 in the latest OpenNMT based on TF-2, I am getting the following warning message.

`WARNING:tensorflow:Unable to create a python object for variable <tf.Variable 'transformer/decoder/layer_5/ffn/conv1d_1/bias:0' shape=(512,) dtype=float32_ref> because it is a reference variable. It may not be visible to training APIs. If this is a problem, consider rebuilding the SavedModel after running tf.compat.v1.enable_resource_variables().

`

1. How to get rid of this warning message which is coming many times?
2.  Will it have effect on the quality of the translations. 
3. Is there any way I can convert the TF-1 exported models to be compatible with TF-2 

Thanks for the help.
Sriram

**Comment by guillaumekln** [comment]
Hi,

What do you mean by "running an exported models in OpenNMT-tf"? Once a model is exported, it is no longer related to OpenNMT-tf and only requires TensorFlow to be executed.

In general, models exported in TensorFlow 1 are not compatible with TensorFlow 2. To upgrade, you can re-export a checkpoint with OpenNMT-tf v2.
