### ISSUE TITLE
Segmentation fault (core dumped) during eval and infer

### ISSUE THREAD

**Issue by ptamas88** [OpenNMT/OpenNMT-tf#668]
Hi,

I got segmentation fault during the training process when the model evaluates and also if i try to infer from command line with the saved checkpoint.
My setup:
2x 1080Ti (12GB)
12 core cpu
32 GB ram
Tensorflow 2.2.0, CUDA 10.1, cudNN 7.6.5, python 3.7.7, OpenNMT-tf 2.9.3
Training code:
`onmt-main --model_type Transformer --config data.yml --auto_config train --with_eval --num_gpus=2`

also happens for this infer code:
`onmt-main --config data.yml --auto_config infer --features_file test.en`

The training goes well here are the last few lines before the error:
```
INFO:tensorflow:Step = 4900 ; steps/s = 0.59, source words/s = 16844, target words/s = 14544 ; Learning rate = 0.000605 ; Loss = 2.536082
INFO:tensorflow:Step = 5000 ; steps/s = 0.57, source words/s = 17240, target words/s = 14895 ; Learning rate = 0.000618 ; Loss = 2.599866
INFO:tensorflow:Saved checkpoint run/ckpt-5000
INFO:tensorflow:Running evaluation for step 5000
Segmentation fault (core dumped)
```

Full training log (with model config, etc.):
https://pastebin.com/N3JJ1beV

How to handle this problem? (It doesnt look like system ram is running out, only using 1-2 GB of it, and i can't tell about GPU ram because tensorflow allocates all)
**UPDATE:** i put --gpu_allow_growth into config parameters and i monitor vram usage with nvidia-smi and it allocates ~1300mb tops before crashing
Thanks in advance

**Comment by guillaumekln** [comment]
Hi,

OpenNMT-tf 2.9.3 requires TensorFlow 2.1, not 2.2.

If you can't use TensorFlow 2.1, you can install OpenNMT-tf from the master branch for TensorFlow 2.2 compatibility, e.g.:

```
pip install https://github.com/OpenNMT/OpenNMT-tf/archive/master.zip
```

**Comment by ptamas88** [comment]
Thank you for the quick answer @guillaumekln 
I uninstalled tf2.2 and installed tf2.1 and it works now!
