### ISSUE TITLE
Serving with specific GPU

### ISSUE THREAD

**Issue by owenljn** [OpenNMT/OpenNMT-tf#673]
Hi,

I'm using python way to serve the models, however, the code automatically allocates all available GPUs, is there anyway to specify which GPU to use?

Thanks.

**Comment by guillaumekln** [comment]
Hi,

There are 2 methods:

* Set the environment variable `CUDA_VISIBLE_DEVICES=0`
* Restrict devices visible to the TensorFlow runtime with [`tf.config.set_visible_devices`](https://www.tensorflow.org/api_docs/python/tf/config/set_visible_devices)

**Comment by guillaumekln** [comment]
The comment above should answer the question.
