### ISSUE TITLE
'share_embeddings' param seems to be working incorrectly

### ISSUE THREAD

**Issue by iamweiweishi** [OpenNMT/OpenNMT-tf#687]
Hi there,

I was tring to test the codes following the instructions. I tried to add the param share_embeddings following the official documents [link.](https://github.com/OpenNMT/OpenNMT-tf/blob/v1.25.0/config/models/transformer_shared_embedding.py)

But I got the following error,

ValueError: Dimensions must be equal, but are 24999 and 35820 for 'transformer/decoder/dense/BiasAdd' (op: 'BiasAdd') with input shapes: [?,24999], [35820].

If I remove the param, everything works fine.

**Comment by guillaumekln** [comment]
Hi,

Did you use the same vocabulary for the source and the target?

**Comment by iamweiweishi** [comment]
Yes. 
I did not modify the yaml file.

**Comment by guillaumekln** [comment]
I mean, do the parameters `source_vocabulary` and `target_vocabulary` point to the same vocabulary file? If not, you can't enable embeddings sharing as the vocabulary size will not match.

**Comment by guillaumekln** [comment]
Let me close this issue. Feel free to reopen if you can provide a way to reproduce the error.
