### ISSUE TITLE
where is the default config file for setting up max_step or train_step for machine translation? 

### ISSUE THREAD

**Issue by lidongxing** [OpenNMT/OpenNMT-tf#688]
In the doc file (doc/configuation.md), it is said that the setting is max_step: 1000000.
where is the configuation file?
No matter that I edit it in the config file, it is still 500000 unless I reset it in .yml file formatted as max_step: 20000

My task is machine translation.
Thank you very much.

**Comment by lidongxing** [comment]
@guillaumekln 
I know reconfig the parameter in yml file. I only want to know where is the original config file.
opennmt/models/squence-to-sequence.py------  def auto_config(self, num_replicas=1) ? Is it this ? 
 I edit the 'max_step' parameter in this function. But no effect occurs.

Thank you very much

**Comment by guillaumekln** [comment]
Yes, that's the correct location. But we don't recommend to change the code when it can be overridden with the configuration.

**Comment by lidongxing** [comment]
OK,thanks.
