### ISSUE TITLE
Layer Norm in Transformer

### ISSUE THREAD

**Issue by NProkoptsev** [OpenNMT/OpenNMT-tf#70]
https://github.com/OpenNMT/OpenNMT-tf/blob/master/opennmt/encoders/self_attention_encoder.py#L70 
Layer norm is also applied to the inputs(after position encoding, before first self-attention) which contradicts scheme presented in paper.
In official implementation it is applied after self-attention layer https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/models/transformer.py#L695

**Comment by guillaumekln** [comment]
Actually in the latest configuration, layer normalization is applied during [preprocessing and not postprocessing ](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/models/transformer.py#L929)of the self attention layer. The authors claim that this configuration is "better for harder-to-learn models".
