### ISSUE TITLE
Update mecab-python3 version to  1.0.1

### ISSUE THREAD

**Issue by EPixowl** [OpenNMT/OpenNMT-tf#703]
mecab-python3 0.996.5 has several issues with Windows (and some versions of OSX) and the OpenNMT-TF package cannot be installed in the latest version using pip.

Updating mecab-python3 to the latest version should solve this issue.

Thanks.

**Comment by guillaumekln** [comment]
`mecab-python3` is not a direct dependency of OpenNMT-tf, but a dependency of `sacrebleu`. It looks like this was already resolved in `sacrebleu`, see https://github.com/mjpost/sacrebleu/issues/104.

We should just wait for a new release of this package. In the meantime, the workaround is similar to https://github.com/OpenNMT/OpenNMT-tf/issues/653:

```bash
pip install sacrebleu==1.4.10
pip install OpenNMT-tf
```

**Comment by EPixowl** [comment]
You are right.
Thanks!
