### ISSUE TITLE
Replace unknown target does not work

### ISSUE THREAD

**Issue by jordimas** [OpenNMT/OpenNMT-tf#750]
replace_unknown_target: True does not work in OpenNMT v2.13.0 with TensorFlow 2.3.1

Source: `Both  the <emphasis>Color Picker</emphasis> and the  <emphasis>Sample Points</emphasis> dialog now display pixel  values in CIE LAB and CIE LCH at your preference."`

Source (tokenized): ` ▁Both ▁the ▁ < em pha sis > Color ▁Pick er < / em pha sis > ▁and ▁the ▁ < em pha
 sis > S a mple ▁Points < / em pha sis > ▁dialog ▁now ▁display ▁pixel ▁values ▁i
n ▁C IE ▁LAB ▁and ▁C IE ▁L CH ▁at ▁your ▁preference .`

Translated: ` Tant el diàleg <<unk>> Selector de color</<unk>> com el diàleg <>Punts de mostreig</<unk>> ara mostra els valors dels píxels en la CIE LAB i la CIE LCH a les vostres preferències."`

Tokenizer: SentencePiece (done externally)
Configuration: https://github.com/Softcatala/nmt-softcatala/blob/master/training/eng-cat/data.yml
Model: TransformerRelative

**Comment by guillaumekln** [comment]
Can you reformat and put backticks (\` and \`) around the translation so that we can see the \<unk> tokens?

Also, what is the translation output in 2.4.0 with the same checkpoint and source?

**Comment by jordimas** [comment]
For 2.4.0 I use the same source corpus but I rebuilt from scratch

**Comment by guillaumekln** [comment]
For this example, what is the source after tokenization?

Please also post the training configuration and logs if relevant.

**Comment by jordimas** [comment]
I added some additional info. Thanks

**Comment by guillaumekln** [comment]
Is it possible for you to share privately the checkpoint and vocabulary files? This would help debugging the output.

**Comment by jordimas** [comment]
Sorry I did not keep the data and I do not have access to a GPU at the moment. Next time that I do a training I will keep it and share it. Thanks

**Comment by jordimas** [comment]
@guillaumekln I think that the problem may be that I'm using CTranslate2 for inference and CTranslate2 does not support replacing <unk> during inference. Correct?
