### ISSUE TITLE
Regarding RNN-based checkpoints and sample inference script

### ISSUE THREAD

**Issue by sayakpaul** [OpenNMT/OpenNMT-tf#764]
Hi. 

I am looking for an RNN-based pre-trained model if it is available. Also, if there is a sample Python script that shows how to perform inference with the [available pre-trained model](https://opennmt.net/Models-tf/), that would be great.

**Comment by guillaumekln** [comment]
Hi,

There are no RNN-based pretrained models.

You can fin some sample Python scripts in the `examples/` directory:

* [Run inference with a checkpoint using the high-level Runner API](https://github.com/OpenNMT/OpenNMT-tf/blob/master/examples/library/minimal_transformer_training.py)
* [Run inference with a SavedModel](https://github.com/OpenNMT/OpenNMT-tf/tree/master/examples/serving/python)

**Comment by sayakpaul** [comment]
Thank you!

I was specifically asking for it because TFLite better supports RNN-based conversions. By I RNN, I really mean non-transfomer based models, more of classic seq2seq ones. Sorry, my lingo is being inconsistent here. But I guess we could train it ourselves to completion using the specifications provided by OpenNMT-tf.
