### ISSUE TITLE
Q: about ParallelInputter

### ISSUE THREAD

**Issue by mayaKaplansky** [OpenNMT/OpenNMT-tf#781]
Hello,
I do not understand is it enough to define multiple input files for the library to use the ParallelInputter, or do I also have to modify something within the function?
Thanks

**Comment by guillaumekln** [comment]
Hi,

You should first define a model that uses a `ParallelInputter` as input and then configure the corresponding data files in the configuration. There are some examples in the `config/models` directory, for example:

https://github.com/OpenNMT/OpenNMT-tf/blob/master/config/models/multi_source_transformer.py

**Comment by mayaKaplansky** [comment]
Thanks I will try it. Is there a way to use the "onmt-build-vocab" from the notebook and not from command line?
I want to do cross validation so I want to run it all from notebook with a loop.

**Comment by guillaumekln** [comment]
Maybe it's easier to work with the [Vocab](https://opennmt.net/OpenNMT-tf/package/opennmt.data.Vocab.html) class directly. You can see how it is used in the [build vocab script](https://github.com/OpenNMT/OpenNMT-tf/blob/master/opennmt/bin/build_vocab.py). It is just a few lines.

**Comment by mayaKaplansky** [comment]
Thank you!! Is there a way to set verbose or log level so something will be printed in the console while training, so I will know its running?

**Comment by guillaumekln** [comment]
Looks like you asked the same question in #783. For these types of questions, please try to use the forum in the future: https://forum.opennmt.net/

**Comment by mayaKaplansky** [comment]
Thanks, I moved to forum
