### ISSUE TITLE
Is it possible to convert a v1 tf 1.15 SavedModel to v2 tf2

### ISSUE THREAD

**Issue by byoungb** [OpenNMT/OpenNMT-tf#785]
I do not have a checkpoints to build from but I do have the exported models. 

I tried to use the following command to reexport the model. 

```
onmt-main --model_type Transformer --config /home/byoungb/workspace/nmt/t2_export/config.yml --checkpoint_path /data/nmt_tmp/ende_csp/1577649964 export --export_dir /data/nmt_out/
```

And it did produce a model that looks to be the correct size and have the right files and loads up in tensorflow_service v2... but the output returns just a bunch of `кккккккккккк`s

I know when I ran the export it said if could not find any checkpoint at the path.

Anyway I have like 20 languages models that I trained for hundreds of hours... so I was really hoping that I would not have to retrain them.... and I am really not wanting to build my own versions of tensorflow serving with the contrib libraries included.

I just thought it was worth asking. I know I saw other similar questions but they didn't appear to answer this specific question. And honestly I have dug through tensorflow docs and I know there are differences between checkpoints and exported models... I just thought the exported models were very close to what a checkpoint is... just with some additional data/variables to make it stand on its own (servable without the nmt code) vs checkpoints which require the nmt code.

**Comment by guillaumekln** [comment]
Re-exporting a model requires the original checkpoint. This is why we usually need to keep the checkpoint around in case we have to re-export the model with a newer TensorFlow version, or change a decoding parameter.

In your case it looks like you would need to re-create the corresponding V1 checkpoint from the exported model, and then re-export with the latest OpenNMT-tf version (assuming you trained a model that can be [automatically upgraded from V1 to V2 layout](https://opennmt.net/OpenNMT-tf/v2_transition.html#changed-checkpoint-layout)). This is technically possible but it requires some exploration.

If you trained Transformer models, another option is to convert the SavedModel to [CTranslate2](https://github.com/OpenNMT/CTranslate2). It means rebuilding your inference service around CTranslate2, but performance and flexibility would be much improved.

**Comment by byoungb** [comment]
Okay thanks, I will give CTranslate2 a try!
