### ISSUE TITLE
gpu_allow_growth is not working

### ISSUE THREAD

**Issue by ET-Chan** [OpenNMT/OpenNMT-tf#80]
Calling the tutorial code with additional argument gpu_allow_growth
```
python -m bin.main train_and_eval --gpu_allow_growth --model config/models/nmt_small.py --config config/opennmt-defaults.yml config/data/toy-ende.yml
```

does not prevent GPU memory being fully allocated. After some digging, it can be found that a call in https://github.com/OpenNMT/OpenNMT-tf/blob/master/opennmt/utils/parallel.py#L27 is causing this.

It seems that this issue is already brought up on a [stackoverflow question](https://stackoverflow.com/questions/38559755/how-to-get-current-available-gpus-in-tensorflow)

**Comment by guillaumekln** [comment]
Interesting. Thanks for highlighting the culprit!

An easy fix would be to not call `device_lib.list_local_devices()` when `num_devices` is 1, thus making `--gpu_allow_growth` only work for single GPU training. I would assume that when training on multiple GPUs, people do not execute other tasks on them.

What do you think?

**Comment by ET-Chan** [comment]
I am not entirely sure if this is a reasonable assumption. We, however, can enforce allow_growth by a trick mentioned in

https://github.com/tensorflow/tensorflow/issues/8021

Specifically, create a session before the first list_local_devices call, as some gpu options, e.g. allow_growth, only have effect when it is used in the 1st session created in the process.

I've tested in by just adding 
```
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.333, allow_growth=True)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))
```

in https://github.com/OpenNMT/OpenNMT-tf/blob/master/bin/main.py#L79 and it works.

(For details why this works, read https://github.com/tensorflow/tensorflow/issues/8136)

**Comment by guillaumekln** [comment]
Thanks for the details. I applied your recommendation in the commit above.
