### ISSUE TITLE
CUDA version required to run OpenNMT-tf

### ISSUE THREAD

**Issue by Anurag-Swarnim-Yadav** [OpenNMT/OpenNMT-tf#803]
So seems like OpenNMT-tf comes with tf version 2.4. So what cuda version do I need for this ?  I have cuda 10.3 available.

**Comment by guillaumekln** [comment]
OpenNMT-tf currently supports TensorFlow 2.3 and 2.4. They require the following CUDA versions:

* TensorFlow 2.3: CUDA 10.1
* TensorFlow 2.4: CUDA 11.0

Please refer to the [TensorFlow GPU documentation](https://www.tensorflow.org/install/gpu).

**Comment by Anurag-Swarnim-Yadav** [comment]
So Do I need to install TensorFlow-GPU 2.3 separately ?

**Comment by guillaumekln** [comment]
You said you have CUDA 10.3, but this version does not exist. If you have CUDA 10.1 installed you can install OpenNMT-tf like this:

```
pip install tensorflow==2.3.* OpenNMT-tf
```

**Comment by Anurag-Swarnim-Yadav** [comment]
Thanks a lot @guillaumekln . It worked with tensorflow==2.3 . It was CUDA 10.1.
