### ISSUE TITLE
Issues about score batch size 

### ISSUE THREAD

**Issue by Anurag-Swarnim-Yadav** [OpenNMT/OpenNMT-tf#812]
How does score batch size effects the result ?

**Comment by guillaumekln** [comment]
The batch size should not impact the result of the `score` runs. However, there could be small differences due to numerical precision (usually < 1e-4).

**Comment by Anurag-Swarnim-Yadav** [comment]
Hey @guillaumekln  Then why do we have batch size for score ?

**Comment by guillaumekln** [comment]
The batch size has an impact on performance. You can compare the time it takes with batch_size 1 vs batch_size 64 for example. The run with batch_size 64 should complete faster.

**Comment by Anurag-Swarnim-Yadav** [comment]
Thanks a lot .
