### ISSUE TITLE
Terminology Clarification - Effective Batch Size

### ISSUE THREAD

**Issue by kyledampier** [OpenNMT/OpenNMT-tf#813]
While training my model in OpenNMT, I had some questions on some of the terminologies for the parameters.

I was wondering what `effective_batch_size` means since we are already required to define a batch size in `training`. What effect does this have on the training of the model?

**Comment by kyledampier** [comment]
The answer to the mentioned issue just links to this issue, and neither of the issues are answered. Is there any chance you can help clarify what `effective_batch_size` means?

**Comment by guillaumekln** [comment]
Transformer models are known to require large batches during training. For example, the paper [Attention Is All You Need](https://arxiv.org/abs/1706.03762) trains Transformer models with a batch size of 25,000 tokens.

Usually users don't have enough GPU memory to reach this batch size, even with multiple GPUs. That's when `effective_batch_size` is helpful. It will accumulate multiple gradients to simulate to simulate a large batch size. So if you set `batch_size` to 3125 and `effective_batch_size` to 25000, it will accumulate the gradients of 8 batches and effectively train the model with a batch size of 25,000 tokens.

The `effective_batch_size` parameter is automatically set when training Transformer models with `--auto_config`.

> The answer to the mentioned issue just links to this issue, and neither of the issues are answered. Is there any chance you can help clarify what effective_batch_size means?

The other issue was closed as it was the wrong repository.
