### ISSUE TITLE
Length mismatch for alignment line

### ISSUE THREAD

**Issue by avillalbacantero** [OpenNMT/OpenNMT-tf#815]
Hi,

I am trying to train the Transformer model with guided-alignments. 

These are the steps I have done:

- I have trained and tokenized both source and target files with SentencePiece + BPE and convert the vocab to OpenNMT format.
- I have computed the alignments using the tool simalign (https://github.com/cisnlp/simalign) with these tokenized files, replacing the symbol ▁ from SentencePiece by a space, which means that I am aligning the subwords, does it?
- I have set the following configuration: https://www.dropbox.com/s/dk9e7r7foq0qe19/myconfig.yml?dl=0

Then, I have started to train using:

`onmt-main --model_type Transformer --config ./config/my_config.yml train --with_eval` 

After the model is loaded, I am getting the following error:

```
INFO:tensorflow:Training on 3502269 examples
INFO:tensorflow:Number of model parameters: 79105545
INFO:tensorflow:Number of model weights: 260 (trainable = 260, non trainable = 0)
2021-03-19 18:05:05.295475: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
2021-03-19 18:05:30.860191: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:172] Filling up shuffle buffer (this may take a while): 1 of 500000
2021-03-19 18:05:30.860524: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:172] Filling up shuffle buffer (this may take a while): 2 of 500000
2021-03-19 18:05:36.475180: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:172] Filling up shuffle buffer (this may take a while): 498548 of 500000
2021-03-19 18:05:36.488959: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:221] Shuffle buffer filled.
Traceback (most recent call last):
  File "e:\programfiles\miniconda\envs\opennmt-tf\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "e:\programfiles\miniconda\envs\opennmt-tf\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\ProgramFiles\Miniconda\envs\opennmt-tf\Scripts\onmt-main.exe\__main__.py", line 7, in <module>
  File "e:\programfiles\miniconda\envs\opennmt-tf\lib\site-packages\opennmt\bin\main.py", line 227, in main
    runner.train(
  File "e:\programfiles\miniconda\envs\opennmt-tf\lib\site-packages\opennmt\runner.py", line 237, in train
    summary = trainer(
  File "e:\programfiles\miniconda\envs\opennmt-tf\lib\site-packages\opennmt\training.py", line 96, in __call__
    for loss in self._steps(dataset, accum_steps=accum_steps, report_steps=report_steps):
  File "e:\programfiles\miniconda\envs\opennmt-tf\lib\site-packages\opennmt\training.py", line 205, in _steps
    loss = forward_fn()
  File "e:\programfiles\miniconda\envs\opennmt-tf\lib\site-packages\tensorflow\python\eager\def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "e:\programfiles\miniconda\envs\opennmt-tf\lib\site-packages\tensorflow\python\eager\def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "e:\programfiles\miniconda\envs\opennmt-tf\lib\site-packages\tensorflow\python\eager\function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "e:\programfiles\miniconda\envs\opennmt-tf\lib\site-packages\tensorflow\python\eager\function.py", line 1843, in _filtered_call
    return self._call_flat(
  File "e:\programfiles\miniconda\envs\opennmt-tf\lib\site-packages\tensorflow\python\eager\function.py", line 1923, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "e:\programfiles\miniconda\envs\opennmt-tf\lib\site-packages\tensorflow\python\eager\function.py", line 545, in call
    outputs = execute.execute(
  File "e:\programfiles\miniconda\envs\opennmt-tf\lib\site-packages\tensorflow\python\eager\execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  assertion failed: [Length mismatch for alignment line \"0-0 1-1 2-2 3-3 4-5 5-4 6-5 7-6 8-7 9-8 10-8 11-9 12-10 13-11 14-12 15-13 16-14 17-14 18-15 19-15 20-16 21-17 22-18 23-19 24-20 26-20 27-21 28-22 29-23 30-24 31-25 32-26 33-27 34-28 35-29 36-30 37-31 38-32 39-33 40-34 41-35 42-36 43-37 44-38 45-39 46-40 47-41 48-42 \": actual source length is 34, but got source id 48 which is out of range. Please check that the alignment file is correctly aligned to the training file.] [Condition x < y did not hold element-wise:] [x (strided_slice_5:0) = ] [48] [y (Cast:0) = ] [34]
         [[{{node assert_less/Assert/AssertGuard/else/_1/assert_less/Assert/AssertGuard/Assert}}]]
         [[IteratorGetNext]]
  (1) Invalid argument:  assertion failed: [Length mismatch for alignment line \"0-0 1-1 2-2 3-3 4-5 5-4 6-5 7-6 8-7 9-8 10-8 11-9 12-10 13-11 14-12 15-13 16-14 17-14 18-15 19-15 20-16 21-17 22-18 23-19 24-20 26-20 27-21 28-22 29-23 30-24 31-25 32-26 33-27 34-28 35-29 36-30 37-31 38-32 39-33 40-34 41-35 42-36 43-37 44-38 45-39 46-40 47-41 48-42 \": actual source length is 34, but got source id 48 which is out of range. Please check that the alignment file is correctly aligned to the training file.] [Condition x < y did not hold element-wise:] [x (strided_slice_5:0) = ] [48] [y (Cast:0) = ] [34]
         [[{{node assert_less/Assert/AssertGuard/else/_1/assert_less/Assert/AssertGuard/Assert}}]]
         [[IteratorGetNext]]
         [[IteratorGetNext/_8]]
0 successful operations.
0 derived errors ignored. [Op:__inference__forward_33495]

Function call stack:
_forward -> _forward
```

which seems to be that my alignment does not correspond to my training source line. This line is different on each execution, it's not that particular line, it seems like the whole alignments file is wrong. 

What is more surprising is that I have dived into my files and I have search for this line. This is what I get:

The training source line, after tokenization:

`▁La ▁resolució ▁de ▁concessió ▁es ▁pot ▁modificar ▁en ▁cas ▁d ' alteració ▁de ▁les ▁condicions ▁que ▁van ▁determinar ▁l ' atorgament , ▁amb ▁la ▁sol · licitud ▁prèvia ▁del ▁beneficiari , ▁que ▁la ▁presentarà ▁amb ▁anterioritat ▁a ▁la ▁realització ▁de ▁les ▁actuacions , ▁juntament ▁amb ▁la ▁documentació ▁necessària .`

The corresponding training target line, also after tokenization:

`▁La ▁resolución ▁de ▁concesión ▁puede ▁modificarse ▁en ▁caso ▁de ▁alteración ▁de ▁las ▁condiciones ▁que ▁determinaron ▁el ▁otorgamiento , ▁con ▁la ▁solicitud ▁previa ▁del ▁beneficiario , ▁que ▁la ▁presentará ▁con ▁anterioridad ▁a ▁la ▁realización ▁de ▁las ▁actuaciones , ▁junto ▁con ▁la ▁documentación ▁necesaria .`

The corresponding alignments (reported by the log):

`0-0 1-1 2-2 3-3 4-5 5-4 6-5 7-6 8-7 9-8 10-8 11-9 12-10 13-11 14-12 15-13 16-14 17-14 18-15 19-15 20-16 21-17 22-18 23-19 24-20 26-20 27-21 28-22 29-23 30-24 31-25 32-26 33-27 34-28 35-29 36-30 37-31 38-32 39-33 40-34 41-35 42-36 43-37 44-38 45-39 46-40 47-41 48-42`

I do not understand why this length mismatch happens, because if I split the source line by spaces (just by doing some `.split(' ')`) I get a length of 49 which matches the index 48 (starting in zero), and the same happens with the target line which has a length of 43.

What's more, I have write a small test script which ensures me that training and alignments files have the same number of lines and also that there is no index in the alignments file which is out of range. The only thing I have found is that some words stay unaligned (i.e their index does not appear in the alignments file) but nothing else.

I provided my files here: 
- Train source file: https://www.dropbox.com/s/3zh66ie07wxptjp/ca_src_entry_norm_clean_train_atok_clean.txt?dl=0
- Train target file: https://www.dropbox.com/s/8cm3m3uotxklara/es_tgt_entry_norm_clean_train_atok_clean.txt?dl=0
- Train alignments: https://www.dropbox.com/s/8wm33x5qah2nsi6/_ca2es_train_guided_alignments.txt?dl=0

Without guided alignments, I have successfully trained the model before.

What am I doing wrong? Should I try to use fast-align instead?

Any help would be appreciated, thanks in advance!

**Comment by guillaumekln** [comment]
Hi,

> replacing the symbol ▁ from SentencePiece by a space, which means that I am aligning the subwords, does it?

This sounds incorrect. You should prepare the alignments on exactly the same training data, otherwise there will be index mismatch when training with guided alignment.

**Comment by avillalbacantero** [comment]
Thank you for your answer @guillaumekln 

So, how does opennmt expect the input alignments? Each index position must represent a word or a subword?

**Comment by guillaumekln** [comment]
Each index must represent a valid token in your training data. It does not matter whether it is a word or a subword. So you typically need to run your alignment tool on the unmodified tokenized data you will be using for the NMT training.

**Comment by avillalbacantero** [comment]
Thank you. 

I think I am gonna try to use fast-align since the tool I am using (simalign) does not seem to perform well when trying to align two tokenized files with the ▁ from SentencePiece, that's why I replaced them. As I see here in this post https://forum.opennmt.net/t/translation-models-with-alignment/2550/3 fast-align does expect this kind of format. 

I apologize for posting this question here since it is not a bug, thank you for your help @guillaumekln .
