### ISSUE TITLE
Feature request: Log time for events during training

### ISSUE THREAD

**Issue by alpamo** [OpenNMT/OpenNMT-tf#822]
Hi Guillaume and others, thanks a lot for the great work you are doing!

I was thinking if it's possible to add time tracking to the logger during training. I tried to search the forum and google for relevant issues but didn't find anything. I think it would be helpful for everyone. So please tell me what you think about it.

Thank you,
Alex

**Comment by guillaumekln** [comment]
Hi Alexander,

Thanks for the request. It makes sense to add the time in the logs produced by the `onmt-main` script. In the PR above I propose to use the log format of the TensorFlow C++ logs:

**Before:**
```text
WARNING:tensorflow:No GPU is detected, falling back to CPU
INFO:tensorflow:Using parameters:
```

**After:**
```text
2021-04-06 18:39:38.214000: W runner.py:195] No GPU is detected, falling back to CPU
2021-04-06 18:39:38.216000: I main.py:341] Using parameters:
```

I decided not to change the behavior for the users of the Python API. If they want to change the log format, they can configure the root logger before importing the `opennmt` package (see the [Python logging API](https://docs.python.org/3/library/logging.html)).

**Comment by alpamo** [comment]
Hi Guillaume,

Great, thank you! That's exactly what I was talking about.

Alex
