### ISSUE TITLE
Performance issues in the definition of _get_initial_state, opennmt/decoders/self_attention_decoder.py

### ISSUE THREAD

**Issue by DLPerf** [OpenNMT/OpenNMT-tf#870]
Hello, I found a performance issue in the definition of `_get_initial_state`, opennmt/decoders/self_attention_decoder.py, [tf.zeros](https://github.com/OpenNMT/OpenNMT-tf/blob/5b7e42c653ffbec90b44d71bb9c6a0fc9a3816d2/opennmt/decoders/self_attention_decoder.py#L228) will be called repeatedly during program execution, resulting in reduced efficiency. I think it should be created before the loop in `_get_initial_state`.

The same issue exists [here](https://github.com/OpenNMT/OpenNMT-tf/blob/5b7e42c653ffbec90b44d71bb9c6a0fc9a3816d2/opennmt/decoders/self_attention_decoder.py#L230).

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by guillaumekln** [comment]
I'm not sure this is a performance issue, especially in graph mode.

Did you run a benchmark to validate that your change improves the performance?

**Comment by guillaumekln** [comment]
Let me close this issue. I don't think this change would make any difference. But if you have benchmark numbers showing an improvement (speed or memory), feel free to reopen this issue and contribute the change. Thanks.
