### ISSUE TITLE
How to convert a fairseq model to OpenNMT type

### ISSUE THREAD

**Issue by lishaojun412** [OpenNMT/OpenNMT-tf#871]
I have several FairSeq models trained before, how can I convert them to OpenNMT type , is there any script support？

**Comment by guillaumekln** [comment]
Why exactly do you want to convert these models? Is it to continue the training or just to run inference?

For inference only, the [OpenNMT/CTranslate2](https://github.com/OpenNMT/CTranslate2) library can now convert models trained with Fairseq.
