### ISSUE TITLE
bug in inputter.py

### ISSUE THREAD

**Issue by EinsQiang** [OpenNMT/OpenNMT-tf#88]
https://github.com/OpenNMT/OpenNMT-tf/blob/93609e075de0de17490e31098df7019e850d8f44/opennmt/inputters/inputter.py#L372

This place should chang to 

```
return self.inputters[0].get_dataset_size(data_file[0])
```

because `data_file` is  a list.

**Comment by guillaumekln** [comment]
Did you mean to use `ParallelInputter` instead? See the description of each inputter:

https://github.com/OpenNMT/OpenNMT-tf/blob/v1.0.1/opennmt/inputters/inputter.py#L262-L263

https://github.com/OpenNMT/OpenNMT-tf/blob/v1.0.1/opennmt/inputters/inputter.py#L347-L348

**Comment by EinsQiang** [comment]
Yes, when I use ParallelInputter. Because it is the subclass of MultiInputter, ParallelInputter use MultiInputter's get_dataset_size which call the first inputter's get_dataset_size, get_dataset_size accept a string data_file, not list data_file.  

I am sorry for my poor english.

**Comment by guillaumekln** [comment]
If you look at the `ParallelInputter` implementation, it correctly overrides `get_dataset_size`  and consider `data_file` as a list:

https://github.com/OpenNMT/OpenNMT-tf/blob/93609e075de0de17490e31098df7019e850d8f44/opennmt/inputters/inputter.py#L294-L304

**Comment by EinsQiang** [comment]
Yes, I read your newest code, find your code is correct. My local code not the newest code. Sorry for my mistake.
