### ISSUE TITLE
Output of inference with score formatted as a "byte string"

### ISSUE THREAD

**Issue by kschweiger** [OpenNMT/OpenNMT-tf#880]
Running `onmt-main  --auto_config infer` with scores enabled in the config, outputs the prediction formatted as a byte string. 
Example:
`-18.279692 ||| b'Mira mit Orien- und B\xc3\xa4hrschienen .'`

When parsing the output afterwards, this leads to problems because
```
>>> str("b'Mira mit Orien- und B\xc3\xa4hrschienen .'`")
"b'Mira mit Orien- und BÃ¤hrschienen .'`"
```
while it should be 
```
>>> b'Mira mit Orien- und B\xc3\xa4hrschienen .'.decode()
'Mira mit Orien- und Bährschienen .'
```

I am using OpenNMT-tf 2.21.0 and TF/TF-text 2.4.3. To generate the output, I followed the [quickstart ](https://opennmt.net/OpenNMT-tf/quickstart.html) and used SentancePiece (as described [here](https://opennmt.net/OpenNMT-tf/tokenization.html#example-sentencepiece-tokenization)).
For the inference I added 
```
infer:
  n_best: 4
  with_scores: ture
```
to the config. Setting `with_scores: false` and rerunning, results in correct formatting/encoding.
I happy to provide additional information if necessary.

**Comment by guillaumekln** [comment]
Thanks for reporting! The PR above should fix this bug.
