### ISSUE TITLE
RuntimeError: Model diverged with loss = NaN.

### ISSUE THREAD

**Issue by FPBHW** [OpenNMT/OpenNMT-tf#890]
Hi,

this might be more of a question than an issue, but I'm observing loss = NaN, and am not clear how this could be, at least not from a theoretical standpoint.

It is possible for loss to be "INFinite" when a prediction is a hard 0 or 1, and the target is the opposite. However, a NaN should - as far as I understand - not occur.

In summary:
- `-log(0) = inf` (not observed, inconvenient, but understandable)
- `-log(x) = NaN` -> Observed, but I do not know for which `x` this could happen (assuming `x >= 0`)

Does anyone have an explanation ?

Using classic SGD OpenNMT-tf-2.20.1, NaN loss encountered after 49900 steps.

Many thanks in advance,
Fokko

**Comment by FPBHW** [comment]
Hypothesis: inside the model, positive and negative INFs are generated and then summed, leading to a prediction of `NaN`. If this is the case, it would be better to report the prediction as `NaN`.

**Comment by guillaumekln** [comment]
> Hypothesis: inside the model, positive and negative INFs are generated and then summed, leading to a prediction of NaN.

Yes, for example:

```python
>>> import tensorflow as tf
>>> x = tf.constant([float("inf")], dtype=tf.float32)
>>> tf.nn.softmax(x)
<tf.Tensor: shape=(1,), dtype=float32, numpy=array([nan], dtype=float32)>
```

> If this is the case, it would be better to report the prediction as NaN.

What do you mean exactly? What should be improved in the current way of reporting a training that diverges?

**Comment by guillaumekln** [comment]
Maybe an empty line in the data file? The score task does not apply any filtering.

**Comment by FPBHW** [comment]
For at least 1 job with this error I am certain that there are no empty lines. If I have updates on this crash, shall I post them in #523 ?
