### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by gsoul** [OpenNMT/OpenNMT-tf#9]
Just for the sake of saving some time for the others.

Demo model worked fine for me, and so I decided to try Transformer model on a bigger dataset. Namely En<->Fr giga corpus with ~20mln sentences.

But my mistake was, that I created vocabulary like was shown in tutorial, without "--size" parameter. As a result script collected all the words in the 20mln sentences, and NMT was not able to deal with such vocabulary size. And was throwing segfault to me.

Luckily after I created vocabulary of size 50000 everything worked fine.

**Comment by guillaumekln** [comment]
Thanks for the feedback.

I added the `--size` option in the quickstart to remind users to limit the vocabulary size.

**Comment by guangzhixie** [comment]
Sorry just want to further understand this. If we want to train the model with a larger vocabulary, how can we prevent Segmentation fault error?

Currently I am training English-to-Chinese NMT, the vocabulary size I set for the source language is 200000. According to this [post](http://forum.opennmt.net/t/large-vocabulary-model/72), it should be no issue. But still, I encountered **Segmentation fault (core dumped)**.

Any suggestion is appreciated!

**Comment by guillaumekln** [comment]
When exactly are you facing the segmentation fault error?

**Comment by guangzhixie** [comment]
Hi @guillaumekln, the error is encountered during the training (onmt-main train), after the step 0. I am using the default config (opennmt-defaults.yml) with sample_buffer_size changed to -1.

**Comment by guangzhixie** [comment]
My dataset is about 1.6G, but my server has quite large memory. Seems it runs ok if I changed to use the transformer model instead of NMTMedium model.
