### ISSUE TITLE
Translator inference is repeating the word and including values when the .

### ISSUE THREAD

**Issue by eduamf** [OpenNMT/OpenNMT-tf#912]
It is my first time using Transformer on onmt (OpenNMT-tf). The data was preprocessed,  almost all parameters are using default value and n_best: 1.  The features_file is like the source vocabulary filtered.

**Comment by guillaumekln** [comment]
Can you clarify what is the problem exactly?

You should also give more information about the configuration, tokenization, data size, command lines, etc.
