### ISSUE TITLE
Fail to load dynamic quantized tflite model

### ISSUE THREAD

**Issue by SefaZeng** [OpenNMT/OpenNMT-tf#915]
I try to use the dynamic quant to decrease the model size. For the float32 model, it works well at Android, but it fail to load the dynamic quantized tflite model with error:
`java.lang.IllegalArgumentException: Internal error: Cannot create interpreter: Did not get operators or tensors in subgraph 1.`
The java code is:
`mtflite = new Interpreter(loadModelFile(MainActivity.this, "opennmt_1.tflite"));`
And the python test also failed with:
```
[  FAILED  ] TFLiteTest.testTFLiteOutput_4
[ RUN      ] TFLiteTest.test_session
[  SKIPPED ] TFLiteTest.test_session
======================================================================
ERROR: testTFLiteInterpreter_0 (__main__.TFLiteTest)
TFLiteTest.testTFLiteInterpreter_0
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/users/anaconda3/envs/pytorch/lib/python3.6/site-packages/parameterized/parameterized.py", line 533, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/workspace/temp_for_tflite/OpenNMT-tf-master/opennmt/tests/tflite_test.py", line 135, in testTFLiteInterpreter
    interpreter = tf.lite.Interpreter(model_path=export_file, num_threads=1)
  File "/home/users/anaconda3/envs/pytorch/lib/python3.6/site-packages/tensorflow/lite/python/interpreter.py", line 367, in __init__
    custom_op_registerers_by_func, experimental_preserve_all_tensors))
ValueError: Did not get operators or tensors in subgraph 1.
```

**Comment by guillaumekln** [comment]
Hi @gcervantes8, any idea about this error?

**Comment by gcervantes8** [comment]
I've gotten a very similar error when exporting with a lower TensorFlow version than the one that you are trying to run with.  What TensorFlow version did you use to export, and which one are you using to run?

**Comment by SefaZeng** [comment]
> I've gotten a very similar error when exporting with a lower TensorFlow version than the one that you are trying to run with. What TensorFlow version did you use to export, and which one are you using to run?

The Tensorflow version to export and test is 2.6.0

**Comment by SefaZeng** [comment]
> > I've gotten a very similar error when exporting with a lower TensorFlow version than the one that you are trying to run with. What TensorFlow version did you use to export, and which one are you using to run?
> 
> The Tensorflow version to export and test is 2.6.0

Update tensorflow to 2.7.0 works. Both 2.6.0 and 2.5.0 failed. But it's not clear what the reason is.

**Comment by SefaZeng** [comment]
> > > I've gotten a very similar error when exporting with a lower TensorFlow version than the one that you are trying to run with. What TensorFlow version did you use to export, and which one are you using to run?
> > 
> > 
> > The Tensorflow version to export and test is 2.6.0
> 
> Update tensorflow to 2.7.0 works. Both 2.6.0 and 2.5.0 failed. But it's not clear what the reason is.

BTW, 2.5.0 output a smaller model file.
