### ISSUE TITLE
Import error on mac M1

### ISSUE THREAD

**Issue by vietph34** [OpenNMT/OpenNMT-tf#917]
I installed opennmt-tf successfully on my mac M1, but I got this error when importing library.
I tried use this toolkit with tf 2.4, 2.5, 2.6, 2.7 
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/var/folders/jp/sf2y5mts7b5fbxmq88g0hs240000gn/T/ipykernel_6733/2874288245.py in <module>
----> 1 import opennmt as omt

/opt/homebrew/Caskroom/miniforge/base/envs/tfmac/lib/python3.8/site-packages/opennmt/__init__.py in <module>
      3 __version__ = "1.25.3"
      4 
----> 5 from opennmt import decoders
      6 from opennmt import encoders
      7 from opennmt import inputters

/opt/homebrew/Caskroom/miniforge/base/envs/tfmac/lib/python3.8/site-packages/opennmt/decoders/__init__.py in <module>
      1 """Module defining decoders."""
      2 
----> 3 from opennmt.decoders.rnn_decoder import RNNDecoder
      4 from opennmt.decoders.rnn_decoder import AttentionalRNNDecoder
      5 from opennmt.decoders.rnn_decoder import MultiAttentionalRNNDecoder

/opt/homebrew/Caskroom/miniforge/base/envs/tfmac/lib/python3.8/site-packages/opennmt/decoders/rnn_decoder.py in <module>
    433     return cell, cell.zero_state(batch_size, dtype)
    434 
--> 435 class _RNMTPlusDecoderCell(tf.nn.rnn_cell.RNNCell):
    436 
    437   def __init__(self,

AttributeError: module 'tensorflow._api.v2.nn' has no attribute 'rnn_cell'`

**Comment by guillaumekln** [comment]
You installed an old version of OpenNMT-tf not compatible with TensorFlow 2.

Try installing a more recent version, for example:

```bash
pip install OpenNMT-tf==2.*
```
