### ISSUE TITLE
Multi GPU training fails with more than 2 A100 GPUs (RuntimeError: Model diverged with loss = NaN.)

### ISSUE THREAD

**Issue by Dagamies** [OpenNMT/OpenNMT-tf#918]
With Nvidia NGC Tensorflow container images (tensorflow:21.12-tf2-py3 and at least down to 20.12-tf2-py3) all works fine with 1xA100 or 2XA100.
When starting training with 3 or 4 GPUs, following error occurs immediately when the actual model training starts:
Traceback (most recent call last):
  File "opennmt/bin/main.py", line 350, in <module>
    main()
  File "opennmt/bin/main.py", line 308, in main
    runner.train(
  File "/ai/onmt/onmt-2240/OpenNMT-tf/opennmt/runner.py", line 276, in train
    summary = trainer(
  File "/ai/onmt/onmt-2240/OpenNMT-tf/opennmt/training.py", line 109, in __call__
    for i, loss in enumerate(
  File "/ai/onmt/onmt-2240/OpenNMT-tf/opennmt/training.py", line 258, in _steps
    raise RuntimeError("Model diverged with loss = NaN.")
RuntimeError: Model diverged with loss = NaN.

**Comment by guillaumekln** [comment]
I suppose you are using mixed precision training, right?

For completeness, can you post the training command line, the configuration, and the full logs?

**Comment by Dagamies** [comment]
--mixed_precision makes no difference.

This works:
`CUDA_VISIBLE_DEVICES=0,1  nohup python opennmt/bin/main.py --model_type Transformer16LargeMem --config /ai/lm/config/data-16-mask-spm-Transformer16LargeNS-lr0005.yml --gpu_allow_growth  train --with_eval --num_gpus 2 >> /ai/lm/16/logs/onmt.log &`

This does not:
`CUDA_VISIBLE_DEVICES=0,1,2,3  nohup python opennmt/bin/main.py --model_type Transformer16LargeMem --config /ai/lm/config/data-16-mask-spm-Transformer16LargeNS-lr0005.yml --gpu_allow_growth  train --with_eval --num_gpus 4 >> /ai/lm/16/logs/onmt.log &`

Model definition:
 ```
   def __init__(self):
        super().__init__(
            num_layers=16,
            num_units=768,
            num_heads=16,
            ffn_inner_dim=8192,
            ffn_activation=layers.gelu,
            position_encoder_class=None,
            maximum_relative_position=96,
            share_embeddings=sequence_to_sequence.EmbeddingsSharingLevel.ALL,
        )
```
Please see attached log:
[onmt.log](https://github.com/OpenNMT/OpenNMT-tf/files/7941522/onmt.log)

**Comment by guillaumekln** [comment]
I'm not sure about this optimizer and learning rate values. Did you also try with the default Transformer parameters (as used in `--auto_config`)?

```yaml
params:
  optimizer: LazyAdam
  optimizer_params:
    beta_1: 0.9
    beta_2: 0.998
  learning_rate: 2.0
  decay_type: NoamDecay
  decay_params:
    model_dim: 768
    warmup_steps: 8000
```

**Comment by Dagamies** [comment]
If it helps, this is the Dockerfile I use to run OpenNMT-tf:
```
FROM nvcr.io/nvidia/tensorflow:21.12-tf2-py3

RUN apt-get update

RUN python3 -m pip --no-cache-dir install pyonmttok && \
    python3 -m pip --no-cache-dir install pyyaml && \
    python3 -m pip --no-cache-dir install rouge && \
    python3 -m pip --no-cache-dir install sacrebleu
```

**Comment by guillaumekln** [comment]
Since you are using gradient accumulation, a data or optimization issue would probably also affect 2 GPU training. So it must be something else related to the additional GPUs.

Did you already tried a 2 GPU training on other GPU pairs, such as `2,3` or `1,2`?

Also, I would try with an official TensorFlow image, for example `tensorflow/tensorflow:2.7.0-gpu`, to make sure there is no unexpected incompatibility.

**Comment by Dagamies** [comment]
Some progress:
No change with official Tensorflow images, same failure. But training works with 0,1 and 2,3 but not 1,2. This might be Tensorflow issue relating to NVLink (system has no NVLink switch but bridges between 0,1 and 2,3)?

**Comment by guillaumekln** [comment]
Interesting. So there seem to be communication issues between GPU 1 and 2 which are not directly connected.

Note sure it's related, but did you apply the recommendation below that is shown when starting the NGC image?

```text
NOTE: The SHMEM allocation limit is set to the default of 64MB.  This may be
   insufficient for TensorFlow.  NVIDIA recommends the use of the following flags:
   docker run --gpus all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 ...
```

**Comment by Dagamies** [comment]
Did that. No help. Downgraded Linux driver + cuda to 11.5 level. No help. Installed TF 2.7 on host and tried outside of container. Still failing.

Modified code a bit so that it will not stop on NaN. Got this:
2`022-01-27 17:03:10.859000: I runner.py:277] Step = 15100 ; steps/s = 0.26, source words/s = 36799522, target words/s = 36771391 ; Learning rate = 0.001000 ; Loss = nan`

It seems to pack a lot of words into steps. Could it be that it is trying to feed empty packets during training?

**Comment by Dagamies** [comment]
Some more experiments. Initial data set has over 100M lines. When I decreased them to 6 M lines, following happened:
`2022-01-27 19:54:42.838000: I runner.py:276] Number of model parameters: 310710272
2022-01-27 19:54:42.842000: I runner.py:276] Number of model weights: 258 (trainable = 258, non trainable = 0)
2022-01-27 19:54:42.860000: W deprecation.py:341] From /home/ari/.local/lib/python3.8/site-packages/tensorflow/python/distribute/values.py:617: Variable.initialized_value (from tensorflow.python.ops.variables) is deprecated and will be removed in a future vers
ion.
Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
2022-01-27 19:54:59.024000: I cross_device_ops.py:619] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
2022-01-27 19:54:59.031000: I cross_device_ops.py:619] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
2022-01-27 19:55:18.946365: W tensorflow/core/grappler/optimizers/loop_optimizer.cc:907] Skipping loop optimization for Merge node with control input: replica_1/gradients/global_norm/write_summary/summary_cond/branch_executed/_549
2022-01-27 19:56:26.015000: I cross_device_ops.py:619] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
2022-01-27 19:56:26.038000: I cross_device_ops.py:619] Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
2022-01-27 19:56:26.080000: I runner.py:276] Step = 100 ; steps/s = 3.04, source words/s = -289383321264874880, target words/s = -289383321264894592 ; Learning rate = 0.000500 ; Loss = 11.692111
2022-01-27 19:56:58.775000: I runner.py:276] Step = 200 ; steps/s = 3.06, source words/s = 282227671238486336, target words/s = 282227671238467264 ; Learning rate = 0.000500 ; Loss = 11.640470
Traceback (most recent call last):
  File "opennmt/bin/main.py", line 350, in <module>
    main()
  File "opennmt/bin/main.py", line 308, in main
    runner.train(
  File "/ai/onmt/onmt-2240/OpenNMT-tf/opennmt/runner.py", line 276, in train
    summary = trainer(
  File "/ai/onmt/onmt-2240/OpenNMT-tf/opennmt/training.py", line 109, in __call__
    for i, loss in enumerate(
  File "/ai/onmt/onmt-2240/OpenNMT-tf/opennmt/training.py", line 258, in _steps
    raise RuntimeError("Model diverged with loss = NaN.")
RuntimeError: Model diverged with loss = NaN.
`

Everything else seems to be OK until NaN, but source/target words/s are off.

**Comment by guillaumekln** [comment]
The reporting is probably wrong. The numbers of source and target words are also synchronized across GPUs. So it seems like data is somehow getting corrupted when transferred between GPU 1 and 2?

Can you run the [topology query script](https://github.com/NVIDIA/cuda-samples/tree/master/Samples/1_Utilities/topologyQuery) from NVIDIA and report the output here?

Also, can you try training a smaller model and see if it makes a difference?

**Comment by Dagamies** [comment]
I tried with "TransformerBigSharedEmbeddings" with same results.

here is topology report (within container):
`
topologyQuery
GPU0 <-> GPU1:
  * Atomic Supported: yes
  * Perf Rank: 0
GPU0 <-> GPU2:
  * Atomic Supported: no
  * Perf Rank: 1
GPU0 <-> GPU3:
  * Atomic Supported: no
  * Perf Rank: 1
GPU1 <-> GPU0:
  * Atomic Supported: yes
  * Perf Rank: 0
GPU1 <-> GPU2:
  * Atomic Supported: no
  * Perf Rank: 1
GPU1 <-> GPU3:
  * Atomic Supported: no
  * Perf Rank: 1
GPU2 <-> GPU0:
  * Atomic Supported: no
  * Perf Rank: 1
GPU2 <-> GPU1:
  * Atomic Supported: no
  * Perf Rank: 1
GPU2 <-> GPU3:
  * Atomic Supported: yes
  * Perf Rank: 0
GPU3 <-> GPU0:
  * Atomic Supported: no
  * Perf Rank: 1
GPU3 <-> GPU1:
  * Atomic Supported: no
  * Perf Rank: 1
GPU3 <-> GPU2:
  * Atomic Supported: yes
  * Perf Rank: 0
GPU0 <-> CPU:
  * Atomic Supported: no
GPU1 <-> CPU:
  * Atomic Supported: no
GPU2 <-> CPU:
  * Atomic Supported: no
GPU3 <-> CPU:
  * Atomic Supported: no

`

**Comment by Dagamies** [comment]
This is in our own data center. I will go and check on Monday.

**Comment by Dagamies** [comment]
Made a small change on training.py:
`    
def _forward(self, source, target, accum_steps=1, report_steps=None):

        """Forwards a training example and accumulates the gradients."""

        loss, gradients = self._compute_gradients(
            source,
            target,
            accum_steps,
            report_steps,
        )

        if accum_steps > 1:
            self._gradient_accumulator(gradients)
        else:
            self._apply_gradients(gradients)
        if tf.math.is_nan(loss):
            tf.print("_forward nan source:"%source)
            tf.print("_forward nan target:"%target)
            tf.print("_forward nan accum_steps:%d"%accum_steps)
            tf.print("_forward nan report_steps:%d"%report_steps)
        return loss
`
Now this is what I get:

`
_forward nan source:
_forward nan target:
_forward nan accum_steps:2
_forward nan report_steps:100
Traceback (most recent call last):
  File "opennmt/bin/main.py", line 350, in <module>
    main()
  File "opennmt/bin/main.py", line 308, in main
    runner.train(
  File "/ai/onmt/onmt-2240/OpenNMT-tf/opennmt/runner.py", line 276, in train
    summary = trainer(
  File "/ai/onmt/onmt-2240/OpenNMT-tf/opennmt/training.py", line 109, in __call__
    for i, loss in enumerate(
  File "/ai/onmt/onmt-2240/OpenNMT-tf/opennmt/training.py", line 259, in _steps
    raise RuntimeError("Model diverged with loss = NaN.")
RuntimeError: Model diverged with loss = NaN.
`

**Comment by guillaumekln** [comment]
What are you trying to print? It seems `source` and `target` are not logged. Try this instead:

```python
tf.print("_forward nan source:", source["tokens"])
tf.print("_forward nan target:", target["tokens"])
```

(Also, you should use triple backticks ``` to enclose your code examples. I had to update your previous posts to fix the formatting.)

**Comment by Dagamies** [comment]
Sorry for the formatting. 

I added some more logging 

``` 
        if tf.math.is_nan(loss):
          tf.print("_forward nan source:",source["tokens"])
          tf.print("_forward nan target:",target["tokens"])
          tf.print("_forward nan accum_steps:%d"%accum_steps)
          tf.print("_forward nan report_steps:%d"%report_steps)

        tf.print("_forward source:",source["tokens"])
        tf.print("_forward target:",target["tokens"])
        tf.print("_forward accum_steps:%d"%accum_steps)
        tf.print("_forward report_steps:%d"%report_steps)


``` 
Source and target tokens are OK and there is nothing interesting about them.

Also I did change _steps() to print out a bit on NaN:
```     
            tf.print("_steps(), i:%d, accum_steps:%d step_loss:%f"%(i,accum_steps,step_loss))
            if tf.math.is_nan(loss):
                tf.print("Before NaN, i:%d, accum_steps:%d step_loss:%f"%(i,accum_steps,step_loss))
                raise RuntimeError("Model diverged with loss = NaN.")
``` 
Now it seems that training fails always as follows:
at step 5, if training with 4 GPUs
at step 4, if training with 3 GPUs, for example

``` 
_steps(), i:2, accum_steps:2 step_loss:0.000000
_steps(), i:3, accum_steps:2 step_loss:2.870174
_steps(), i:4, accum_steps:2 step_loss:0.000000
Before NaN, i:4, accum_steps:2 step_loss:0.000000

```

**Comment by guillaumekln** [comment]
I'm not sure there is something interesting to find in the training code. If there was an issue in the code or the data, it would affect all 2 GPU trainings. But here the issue only occurs with specific GPU pairs.

**Comment by Dagamies** [comment]
Yes, today. It seems that I can reproduce this issue with any tf.distribute.MirroredStrategy() based training, so it is not OpenNMT-tf specific. I will proceed to troubleshoot this further with Dell. This is either a HW issue or issue with Nvidia libraries I believe.
