### ISSUE TITLE
RuntimeError: Model diverged with loss = NaN.

### ISSUE THREAD

**Issue by rudyyin** [OpenNMT/OpenNMT-tf#927]
Hello,
I have met a prolem with training model. Here is the error information:

# error information
2022-03-02 22:26:59.033000: I runner.py:276] Step = 297500 ; steps/s = 4.57, source words/s = 16758, target words/s = 19073 ; Learning rate = 0.000187 ; Loss = 1.602740
2022-03-02 22:27:20.229000: I runner.py:276] Step = 297600 ; steps/s = 4.72, source words/s = 17585, target words/s = 19955 ; Learning rate = 0.000187 ; Loss = 1.610771
Traceback (most recent call last):
  File "main.py", line 356, in <module>    main()  File "main.py", line 314, in main    runner.train(  File "/home/jovyan/project/atc-tf/opennmt/runner.py", line 276, in train    summary = trainer(  File "/home/jovyan/project/atc-tf/opennmt/training.py", line 110, in __call__    for i, loss in enumerate(  File "/home/jovyan/project/atc-tf/opennmt/training.py", line 269, in _steps    raise RuntimeError("Model diverged with loss = NaN.")RuntimeError: Model diverged with loss = NaN.

# yaml file:
model_dir: /tmp/run_02_09_transformer_new_input_long/

data:
  train_features_file: /tmp/ID/2022-01-10-src-train.txt
  train_labels_file: /tmp/ID/2022-01-10-tgt-train.txt
  eval_features_file: /tmp/ID/2022-02-08/2022-02-08-src-test.txt
  eval_labels_file: /tmp/ID/2022-02-08/2022-02-08-tgt-test.txt
  source_vocabulary: /tmp/ID/2022-02-08/src-vocab.txt
  target_vocabulary: /tmp/ID/2022-02-08/src-vocab.txt

train:
  batch_size: 1024
  batch_type: examples
  max_step: 300000
  maximum_features_length: 30
  maximum_labels_length: 30
  sample_buffer_size: 500000
  keep_checkpoint_max: 1
  average_last_checkpoints: 1
  prefetch_buffer_size: 500000
  effective_batch_size: null
  

eval:
  steps: 1000
  batch_size: 512

# command 
TF_GPU_THREAD_COUNT=24 TF_GPU_THREAD_MODE=gpu_private CUDA_VISIBLE_DEVICES=1 python main.py --model config/models/normal_transformer_all_metrics.py --gpu_allow_growth --mixed_precision --config yml/data_02_09_normal_metrics_new_input_long_step.yml --auto_config train --with_eval --num_gpus 1 > data_02_09_normal_metrics.log 2>&1

# normal_transformer_all_metrics.py
from unittest import result
import opennmt
from opennmt.utils import metrics
import tensorflow as tf

def decode_prediction(tokens,prediction=False):
    result = []
    for data in tokens:
        if prediction:
            text= " ".join([i.decode("utf-8") for i in data[0]]).split()
        else:
            text= " ".join([i.decode("utf-8") for i in data]).split()
        if text[-1] == '</s>':
            while len(text)>0 and text[-1] == '</s>':
                text = text[0:-1]
        text = " ".join(text).strip()
        result.append(text)
    return result

class tinyTransformer(opennmt.models.Transformer):
    def __init__(self):
        super().__init__(
            source_inputter=opennmt.inputters.WordEmbedder(embedding_size=256),
            target_inputter=opennmt.inputters.WordEmbedder(embedding_size=256),
            num_layers=6,
            num_units=384,
            num_heads=6,
            ffn_inner_dim=786,
            dropout=0.1,
            attention_dropout=0.1,
            ffn_dropout=0.1,
            share_embeddings=opennmt.models.EmbeddingsSharingLevel.SOURCE_TARGET_INPUT,
        )

    def get_metrics(self):
        all_metrics = metrics.correction_metrics()
        metric = {"all_metrics":all_metrics}
        return metric
    # Here you can override any method from the Model class for a customized behavior.

    def update_metrics (self, metrics, predictions, labels, source):
        predictedTokens = decode_prediction(predictions['tokens'].numpy().tolist(),True)
        labelsTokens = decode_prediction(labels['tokens'].numpy().tolist(),False)
        sourceTokens = decode_prediction(source['tokens'].numpy().tolist(),False)
        metrics['all_metrics'].update_state(sourceTokens,labelsTokens,predictedTokens)
        return metrics

model = tinyTransformer

**Comment by rudyyin** [comment]
# normal_transformer_all_metrics.py

```
from unittest import result
import opennmt
from opennmt.utils import metrics
import tensorflow as tf

def decode_prediction(tokens,prediction=False):
    result = []
    for data in tokens:
        if prediction:
            text= " ".join([i.decode("utf-8") for i in data[0]]).split()
        else:
            text= " ".join([i.decode("utf-8") for i in data]).split()
        if text[-1] == '</s>':
            while len(text)>0 and text[-1] == '</s>':
                text = text[0:-1]
        text = " ".join(text).strip()
        result.append(text)
    return result

class tinyTransformer(opennmt.models.Transformer):
    def __init__(self):
        super().__init__(
            source_inputter=opennmt.inputters.WordEmbedder(embedding_size=256),
            target_inputter=opennmt.inputters.WordEmbedder(embedding_size=256),
            num_layers=6,
            num_units=384,
            num_heads=6,
            ffn_inner_dim=786,
            dropout=0.1,
            attention_dropout=0.1,
            ffn_dropout=0.1,
            share_embeddings=opennmt.models.EmbeddingsSharingLevel.SOURCE_TARGET_INPUT,
        )

    def get_metrics(self):
        all_metrics = metrics.correction_metrics()
        metric = {"all_metrics":all_metrics}
        return metric
    # Here you can override any method from the Model class for a customized behavior.

    def update_metrics (self, metrics, predictions, labels, source):
        predictedTokens = decode_prediction(predictions['tokens'].numpy().tolist(),True)
        labelsTokens = decode_prediction(labels['tokens'].numpy().tolist(),False)
        sourceTokens = decode_prediction(source['tokens'].numpy().tolist(),False)
        metrics['all_metrics'].update_state(sourceTokens,labelsTokens,predictedTokens)
        return metrics


model = tinyTransformer


```

**Comment by guillaumekln** [comment]
Hi,

Can you first try training without `TF_GPU_THREAD_COUNT=24 TF_GPU_THREAD_MODE=gpu_private`?

Then you can also try removing `--mixed_precision` and see if it makes a difference.
