### ISSUE TITLE
After tflite invoke, the tflite model use a larger memory.

### ISSUE THREAD

**Issue by SefaZeng** [OpenNMT/OpenNMT-tf#928]
I try to use the tflite model via c++ and deploy it on mobile.
Here is the code example:
```
void Model::Inference(const std::vector<int> &inputs,
                      std::vector<int> &outputs){
  int size = inputs.size();
  const std::vector<int> input_size = {size};
  std::cout<<"model memo 1: "<<physical_memory_used_by_process_temp()<<std::endl;
  interpreter_->ResizeInputTensorStrict(0, input_size);
  interpreter_->AllocateTensors();
  std::cout<<"model memo 2: "<<physical_memory_used_by_process_temp()<<std::endl;
  int* input_tensor = interpreter_->typed_input_tensor<int>(0);
  for(int i = 0; i < input_size[0]; i++){
    input_tensor[i] = inputs[i];
  }
  std::cout<<"model memo 3: "<<physical_memory_used_by_process_temp()<<std::endl;
  interpreter_->Invoke();
  std::cout<<"model memo 4: "<<physical_memory_used_by_process_temp()<<std::endl;
  int* output_tensor = interpreter_->typed_output_tensor<int>(0);
  std::cout<<"model memo 5: "<<physical_memory_used_by_process_temp()<<std::endl;
 
  auto output_size = interpreter_->output_tensor(0)->dims->data[0];
  for(int i = 0; i < output_size; i++){
    if(output_tensor[i] == end_token_id_)
      break;
    outputs.push_back(output_tensor[i]);
  }
}
```
The model file size is 85MB. The memory usage is only 140MB when the model is loaded. After the `interpreter_->invoke()` , the memory usage increase to 200 or even 250 mb. Is this normal? Is there any way to release the increased memory usage?

**Comment by guillaumekln** [comment]
> Is this normal?

Yes. In general more memory are needed to run the model.

> Is there any way to release the increased memory usage?

I don't know about the TensorFlow Lite C++. You can try asking this question on the [TensorFlow forum](https://discuss.tensorflow.org/).

**Comment by gcervantes8** [comment]
In my experience, the memory will only increase after the first inference call.

The first prediction also has a higher run time (on mobile), while any later inference calls end up running faster.

**Comment by SefaZeng** [comment]
> In my experience, the memory will only increase after the first inference call.
> 
> The first prediction also has a higher run time (on mobile), while any later inference calls end up running faster.

But 100MB is a bit too large for mobile devices.

**Comment by SefaZeng** [comment]
> In my experience, the memory will only increase after the first inference call.
> 
> The first prediction also has a higher run time (on mobile), while any later inference calls end up running faster.

Is there any ways to move the beam search to cpp not in tensorflow? I guess that is the cause of the memory increase.

**Comment by guillaumekln** [comment]
You can also train a smaller model. Search for "knowledge distillation" which is a technique to train small models with little accuracy loss.

> Is there any ways to move the beam search to cpp not in tensorflow? I guess that is the cause of the memory increase.

Sure. You can develop a custom TensorFlow op and register it in the TensorFlow Lite runtime. But it's a relatively complex engineering task. We will not provide that as part of OpenNMT-tf.

I'm closing this since it does not seem there is an issue specific to OpenNMT-tf.
