### ISSUE TITLE
Installation via pip

### ISSUE THREAD

**Issue by tokestermw** [OpenNMT/OpenNMT-tf#93]
A direct pip install of the package,

```
pip install git+git://github.com/OpenNMT/OpenNMT-tf.git@v1.0.2
```

gives an error:

```
Python 3.6.4 (default, Mar  8 2018, 13:06:21)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import opennmt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/opennmt/__init__.py", line 3, in <module>
    from opennmt import decoders
ImportError: cannot import name 'decoders'
```

I think the issue is in `setup.py`, the `packages` settings is set to `["opennmt"]` instead of letting `find_packages()` find Python modules. I also noticed the `find_packages()` was removed in this commit.

https://github.com/OpenNMT/OpenNMT-tf/commit/70ffde8895810b9d880331f127143e3a5b6ddab7#diff-2eeaed663bd0d25b7e608891384b7298

Is there any reasons for this?

Thanks

**Comment by guillaumekln** [comment]
Thanks for pointing this out!

The change you referenced was incorrect and `setup.py` did not get much attention lately. I fixed this in the commit above and will also make sure to set the correct version with the next release. If this file needs other improvements, I would love a PR or feedback!

Also, let's keep this issue open until the `pip` experience is improved. For example, I would like to include the scripts from `bin` in the main package.

**Comment by tokestermw** [comment]
Thanks!

I added a PR to add the `bin` scripts to the package: https://github.com/OpenNMT/OpenNMT-tf/pull/94

It would be also be great if the package releases would be [uploaded to PyPi](http://peterdowns.com/posts/first-time-with-pypi.html).

**Comment by guillaumekln** [comment]
The `setup.py` was revisited and a package has been pushed on PyPi: https://pypi.python.org/pypi/OpenNMT-tf/1.0.3.

Thanks!
