### ISSUE TITLE
Why is the SelfAttentionEncoderlayer inconsistent with the paper?

### ISSUE THREAD

**Issue by Wenjun-Peng** [OpenNMT/OpenNMT-tf#930]
I read the code about self attention of transformer, and found it is inconsistent with paper "Attention is all you need", which contains a residual operation. Can you tell why?
This is the document and code of transformer：https://opennmt.net/OpenNMT-tf/_modules/opennmt/layers/transformer.html#SelfAttentionEncoderLayer.__init__
```
  def call(self, x, mask=None, training=None):
      """Runs the encoder layer."""
      y, _ = self.self_attention(x, mask=mask, training=training)
      y = self.ffn(y, training=training)
      return y
```

**Comment by guillaumekln** [comment]
In the layer constructor, you can see that the modules are wrapped with [`TransformerLayerWrapper`](https://opennmt.net/OpenNMT-tf/package/opennmt.layers.TransformerLayerWrapper.html) which applies the layer normalization, dropout, and residual connection.

**Comment by Wenjun-Peng** [comment]
> 

Thank you very much. Maybe I should read it more carefully next time
