### ISSUE TITLE
Comparison of OpenNMT-tf and tensor2tensor

### ISSUE THREAD

**Issue by nashid** [OpenNMT/OpenNMT-tf#931]
I have to use a Transformer network for an NMT task. However, I am not aware of any direct comparison between OpenNMT-tf and tensor2tensor. Can anyone shed light on which works better for an NMT task?

**Comment by guillaumekln** [comment]
They work similarly in the sense they are training the same model with equivalent hyperparameters. OpenNMT-tf is more focused on MT while Tensor2Tensor is more general and supports many other tasks.

**Comment by nashid** [comment]
@guillaumekln thanks a lot for your response. Do you know whether `OpenNMT-tf` provides competitive results with `Tensor2Tensor ` for a machine translation task?

**Comment by guillaumekln** [comment]
OpenNMT-tf provides the same results as Tensor2Tensor for Transformer models.
