### ISSUE TITLE
BPE support for transformer model

### ISSUE THREAD

**Issue by nashid** [OpenNMT/OpenNMT-tf#932]
I have to use a Transformer network for machine translation that supports byte pair encoding (BPE).

Can anyone confirm whether `OpenNMT-tf` supports BPE for the Transformer models?

**Comment by guillaumekln** [comment]
All NMT toolkits support BPE, since BPE is a data preprocessing step that you can apply before the training.

If you have more general questions, I suggest asking them on the [forum](https://forum.opennmt.net/). We prefer keeping the GitHub issues for bugs and feature requests.
