### ISSUE TITLE
Why BLEU score is computed during training and not during inference?

### ISSUE THREAD

**Issue by code-rex1** [OpenNMT/OpenNMT-tf#941]
It appears BLEU score is reported during training and does not report the BLEU score for inference.

What am I missing here?

**Comment by guillaumekln** [comment]
The BLEU score is computed during the evaluation. The evaluation can run at regular interval during the training or run manually using the `eval` subcommand.

The inference just runs the inference and nothing more. You can compute a score on the output if you want to.
