### ISSUE TITLE
cpp for tensorflow serving

### ISSUE THREAD

**Issue by lyzKF** [OpenNMT/OpenNMT-tf#956]
Hi, can u show a demo in cpp for https://github.com/OpenNMT/OpenNMT-tf/tree/master/examples/serving/tensorflow_serving

thank you

**Comment by guillaumekln** [comment]
Hi,

We don't have any TensorFlow C++ example.

Do you need to use TensorFlow specifically? If not, you can check out [CTranslate2](https://github.com/OpenNMT/CTranslate2) which should be simpler to compile and use from C++.

**Comment by lyzKF** [comment]
@guillaumekln  thank you
