### ISSUE TITLE
Fine-tune GPT2 model from Transformers

### ISSUE THREAD

**Issue by NeonBohdan** [OpenNMT/OpenNMT-tf#965]
As you can see [GPT2](https://huggingface.co/docs/transformers/main/en/model_doc/gpt2) in Transformers library supports both Pytorch and Tensorflow loading 

I want to preload weights of this model to OpenNMT-tf
As I saw in [ct2-transformers-converter](https://github.com/OpenNMT/CTranslate2/blob/ef4d7b6510e36c66ecd50beaa2e2dc57c2f31567/python/ctranslate2/converters/transformers.py#L398) it can be loaded for conversion. The thing is only in naming convention 

Does the same apply for Tensorflow 
And will I be able to restore OpenNMT-tf initialized model with weight from [tf_model.h5](https://huggingface.co/microsoft/DialoGPT-medium/blob/main/tf_model.h5) file that follows Transformers library architecture(even if it requires some manual work to do)?

**Comment by guillaumekln** [comment]
OpenNMT-tf cannot load the GPT2 model from the Transformers library.

The conversion script you are referring only applies to CTranslate2 for inference. There is no similar script or mechanism for OpenNMT-tf.

**Comment by NeonBohdan** [comment]
Since Transformer GPT2 and OpenNMT-tf GPT2 may share the same tensorflow layer primitives maybe it is possible to load it layer by layer by some custom script?
I'm interested in the opportunity, if it's possible I will dive into it

**Comment by guillaumekln** [comment]
Yes, the architecture should be compatible for the most part so it should be possible to write a custom script and load the weights layer by layer.

Why not finetuning directly with the Transformers library though?

**Comment by NeonBohdan** [comment]
Ok, thanks, You are right 
I liked this infrastracture so much, but it's better to finetune in Transformers
