### ISSUE TITLE
Parallel text inputter fails with compressed text files

### ISSUE THREAD

**Issue by awery** [OpenNMT/OpenNMT-tf#973]
Hello,

When trying to train a NMT model using GZIP compressed text files (see [this doc](https://opennmt.net/OpenNMT-tf/data.html#compressed-data)) with **OpenNMT-tf 2.29.0**, the following exception is raised: `RuntimeError: Parallel datasets do not have the same size`

The issue seems to lie in the `count_line` function of https://github.com/OpenNMT/OpenNMT-tf/blob/master/opennmt/utils/misc.py#L222 which is not able to deal properly with gzipped files.

Here is how to reproduce the issue with the toy-ende data from https://opennmt.net/OpenNMT-tf/quickstart.html#step-1-prepare-the-data

```
import gzip
from pathlib import Path
from opennmt.utils.misc import count_lines

def create_gzip(original_file):
    gziped_file = f'{original_file}.gz'
    
    with open(original_file, 'rt', newline="\n") as f:
        lines = f.readlines()

    with gzip.open(gziped_file, 'wt', encoding="utf-8") as f:
        for line in lines:
            f.write(line)
            
    return gziped_file

base_path = Path('/home/jovyan/mt/opennmt_toy_example/toy-ende')

print('txt src:', count_lines(base_path / "src-train.txt"))
print('txt tgt:', count_lines(base_path / "tgt-train.txt"))
print('gzip src:', count_lines(create_gzip(base_path / "src-train.txt")))
print('gzip tgt:', count_lines(create_gzip(base_path / "tgt-train.txt")))
```

This will output the following:
```
txt src: 10000
txt tgt: 10000
gzip src: 1841
gzip tgt: 2035
```

We can check that the compressed files have indeed the same number of lines:
```
zcat src-train.txt.gz | wc -l
10000
```
```
zcat tgt-train.txt.gz | wc -l
10000
```

**Comment by guillaumekln** [comment]
Thank you for reporting this issue. I opened a PR to fix the `count_lines` function.
