### ISSUE TITLE
ModuleNotFoundError: No module named 'lxml.etree'

### ISSUE THREAD

**Issue by atanumandal0491** [OpenNMT/OpenNMT-tf#980]
Hi, I am trying to install opennmt-tf in Paperspace Gradient. The installation has been completed without any error whereas import opennmt gives the error "ModuleNotFoundError: No module named 'lxml.etree'". Previously I was using google colab with no error. 
Kindly let me know is some bug with opennmt or paperspace gradient.

**Comment by guillaumekln** [comment]
We don't use the module `lxml` so this error does not seem related with OpenNMT-tf.
